// Copyright 2020-2026 ONDEWO GmbH
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.32.0
// source: ondewo/qa/qa.proto

package qa

import (
	nlu "github.com/ondewo/ondewo-vtsi-client-go/v8/api/ondewo/nlu"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message
type GetAnswerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The name of the session this query is sent to. Format:
	// <code>projects/&lt;Project ID&gt;/agent/sessions/&lt;Session ID&gt;</code>.
	// It&apos;s up to the API caller to choose an appropriate session ID. It can be a random number or
	// some type of user identifier (preferably hashed). The length of the session
	// ID must not exceed 36 bytes.
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Required. The context of the request. A message containing a string (in the form of a sentence) and a
	// language code.
	Text *nlu.TextInput `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	// Maximal number of answers returned
	MaxNumAnswers int32 `protobuf:"varint,3,opt,name=max_num_answers,json=maxNumAnswers,proto3" json:"max_num_answers,omitempty"`
	// Threshold (minimal score) to give back reader result
	ThresholdReader float32 `protobuf:"fixed32,4,opt,name=threshold_reader,json=thresholdReader,proto3" json:"threshold_reader,omitempty"`
	// Threshold (minimal score) to give back retriever result
	ThresholdRetriever float32 `protobuf:"fixed32,5,opt,name=threshold_retriever,json=thresholdRetriever,proto3" json:"threshold_retriever,omitempty"`
	// Threshold (minimal score) overall probability
	ThresholdOverall float32 `protobuf:"fixed32,6,opt,name=threshold_overall,json=thresholdOverall,proto3" json:"threshold_overall,omitempty"`
	// Reader model name
	ReaderModelName string `protobuf:"bytes,7,opt,name=reader_model_name,json=readerModelName,proto3" json:"reader_model_name,omitempty"`
	// Optional. Filters applied to the urls, to restrict the retrieved documents.
	UrlFilter     *UrlFilter `protobuf:"bytes,8,opt,name=url_filter,json=urlFilter,proto3" json:"url_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnswerRequest) Reset() {
	*x = GetAnswerRequest{}
	mi := &file_ondewo_qa_qa_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnswerRequest) ProtoMessage() {}

func (x *GetAnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_qa_qa_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnswerRequest.ProtoReflect.Descriptor instead.
func (*GetAnswerRequest) Descriptor() ([]byte, []int) {
	return file_ondewo_qa_qa_proto_rawDescGZIP(), []int{0}
}

func (x *GetAnswerRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetAnswerRequest) GetText() *nlu.TextInput {
	if x != nil {
		return x.Text
	}
	return nil
}

func (x *GetAnswerRequest) GetMaxNumAnswers() int32 {
	if x != nil {
		return x.MaxNumAnswers
	}
	return 0
}

func (x *GetAnswerRequest) GetThresholdReader() float32 {
	if x != nil {
		return x.ThresholdReader
	}
	return 0
}

func (x *GetAnswerRequest) GetThresholdRetriever() float32 {
	if x != nil {
		return x.ThresholdRetriever
	}
	return 0
}

func (x *GetAnswerRequest) GetThresholdOverall() float32 {
	if x != nil {
		return x.ThresholdOverall
	}
	return 0
}

func (x *GetAnswerRequest) GetReaderModelName() string {
	if x != nil {
		return x.ReaderModelName
	}
	return ""
}

func (x *GetAnswerRequest) GetUrlFilter() *UrlFilter {
	if x != nil {
		return x.UrlFilter
	}
	return nil
}

// Message containing the response for retrieving answers.
type GetAnswerResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The results of the conversational query or event processing.
	QueryResult   *nlu.DetectIntentResponse `protobuf:"bytes,2,opt,name=query_result,json=queryResult,proto3" json:"query_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnswerResponse) Reset() {
	*x = GetAnswerResponse{}
	mi := &file_ondewo_qa_qa_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnswerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnswerResponse) ProtoMessage() {}

func (x *GetAnswerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_qa_qa_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnswerResponse.ProtoReflect.Descriptor instead.
func (*GetAnswerResponse) Descriptor() ([]byte, []int) {
	return file_ondewo_qa_qa_proto_rawDescGZIP(), []int{1}
}

func (x *GetAnswerResponse) GetQueryResult() *nlu.DetectIntentResponse {
	if x != nil {
		return x.QueryResult
	}
	return nil
}

// Message for running a web scraper job.
type RunScraperRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of project IDs to run the scraper on.
	ProjectIds    []string `protobuf:"bytes,1,rep,name=project_ids,json=projectIds,proto3" json:"project_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunScraperRequest) Reset() {
	*x = RunScraperRequest{}
	mi := &file_ondewo_qa_qa_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunScraperRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunScraperRequest) ProtoMessage() {}

func (x *RunScraperRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_qa_qa_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunScraperRequest.ProtoReflect.Descriptor instead.
func (*RunScraperRequest) Descriptor() ([]byte, []int) {
	return file_ondewo_qa_qa_proto_rawDescGZIP(), []int{2}
}

func (x *RunScraperRequest) GetProjectIds() []string {
	if x != nil {
		return x.ProjectIds
	}
	return nil
}

// Message containing the response for running a web scraper job.
type RunScraperResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of scraper containers running the jobs.
	ScraperContainers []*RunScraperResponse_ScraperContainer `protobuf:"bytes,1,rep,name=scraper_containers,json=scraperContainers,proto3" json:"scraper_containers,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RunScraperResponse) Reset() {
	*x = RunScraperResponse{}
	mi := &file_ondewo_qa_qa_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunScraperResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunScraperResponse) ProtoMessage() {}

func (x *RunScraperResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_qa_qa_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunScraperResponse.ProtoReflect.Descriptor instead.
func (*RunScraperResponse) Descriptor() ([]byte, []int) {
	return file_ondewo_qa_qa_proto_rawDescGZIP(), []int{3}
}

func (x *RunScraperResponse) GetScraperContainers() []*RunScraperResponse_ScraperContainer {
	if x != nil {
		return x.ScraperContainers
	}
	return nil
}

// Message containing the response for running a training job.
type RunTrainingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// F1 score as a response of the training.
	F1 float32 `protobuf:"fixed32,1,opt,name=f1,proto3" json:"f1,omitempty"`
	// Accuracy as a response of the training.
	Accuracy      float32 `protobuf:"fixed32,2,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunTrainingResponse) Reset() {
	*x = RunTrainingResponse{}
	mi := &file_ondewo_qa_qa_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunTrainingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunTrainingResponse) ProtoMessage() {}

func (x *RunTrainingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_qa_qa_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunTrainingResponse.ProtoReflect.Descriptor instead.
func (*RunTrainingResponse) Descriptor() ([]byte, []int) {
	return file_ondewo_qa_qa_proto_rawDescGZIP(), []int{4}
}

func (x *RunTrainingResponse) GetF1() float32 {
	if x != nil {
		return x.F1
	}
	return 0
}

func (x *RunTrainingResponse) GetAccuracy() float32 {
	if x != nil {
		return x.Accuracy
	}
	return 0
}

// Message for defining URL filters to include and exclude from the scraping process.
type UrlFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional. List of allowed values for the metadata field <code>&apos;url&apos;</code>.
	AllowedValues []string `protobuf:"bytes,1,rep,name=allowed_values,json=allowedValues,proto3" json:"allowed_values,omitempty"`
	// Optional. Regular expression that must be matched by the metadata.
	RegexFilterInclude string `protobuf:"bytes,2,opt,name=regex_filter_include,json=regexFilterInclude,proto3" json:"regex_filter_include,omitempty"`
	// Optional. Regular expression that must not be matched by the metadata.
	RegexFilterExclude string `protobuf:"bytes,3,opt,name=regex_filter_exclude,json=regexFilterExclude,proto3" json:"regex_filter_exclude,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UrlFilter) Reset() {
	*x = UrlFilter{}
	mi := &file_ondewo_qa_qa_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UrlFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UrlFilter) ProtoMessage() {}

func (x *UrlFilter) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_qa_qa_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UrlFilter.ProtoReflect.Descriptor instead.
func (*UrlFilter) Descriptor() ([]byte, []int) {
	return file_ondewo_qa_qa_proto_rawDescGZIP(), []int{5}
}

func (x *UrlFilter) GetAllowedValues() []string {
	if x != nil {
		return x.AllowedValues
	}
	return nil
}

func (x *UrlFilter) GetRegexFilterInclude() string {
	if x != nil {
		return x.RegexFilterInclude
	}
	return ""
}

func (x *UrlFilter) GetRegexFilterExclude() string {
	if x != nil {
		return x.RegexFilterExclude
	}
	return ""
}

// Message containing the response for checking the server state.
type GetServerStateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Indicates whether the server is ready to accept requests.
	ServerIsReady bool `protobuf:"varint,1,opt,name=server_is_ready,json=serverIsReady,proto3" json:"server_is_ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerStateResponse) Reset() {
	*x = GetServerStateResponse{}
	mi := &file_ondewo_qa_qa_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerStateResponse) ProtoMessage() {}

func (x *GetServerStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_qa_qa_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerStateResponse.ProtoReflect.Descriptor instead.
func (*GetServerStateResponse) Descriptor() ([]byte, []int) {
	return file_ondewo_qa_qa_proto_rawDescGZIP(), []int{6}
}

func (x *GetServerStateResponse) GetServerIsReady() bool {
	if x != nil {
		return x.ServerIsReady
	}
	return false
}

// Message for listing project IDs in the response.
type ListProjectIdsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of project IDs.
	ProjectIds    []string `protobuf:"bytes,1,rep,name=project_ids,json=projectIds,proto3" json:"project_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectIdsResponse) Reset() {
	*x = ListProjectIdsResponse{}
	mi := &file_ondewo_qa_qa_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectIdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectIdsResponse) ProtoMessage() {}

func (x *ListProjectIdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_qa_qa_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectIdsResponse.ProtoReflect.Descriptor instead.
func (*ListProjectIdsResponse) Descriptor() ([]byte, []int) {
	return file_ondewo_qa_qa_proto_rawDescGZIP(), []int{7}
}

func (x *ListProjectIdsResponse) GetProjectIds() []string {
	if x != nil {
		return x.ProjectIds
	}
	return nil
}

// Message for requesting the configuration of a specific project.
type GetProjectConfigRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the project for which to retrieve the configuration.
	ProjectId     string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectConfigRequest) Reset() {
	*x = GetProjectConfigRequest{}
	mi := &file_ondewo_qa_qa_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectConfigRequest) ProtoMessage() {}

func (x *GetProjectConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_qa_qa_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectConfigRequest.ProtoReflect.Descriptor instead.
func (*GetProjectConfigRequest) Descriptor() ([]byte, []int) {
	return file_ondewo_qa_qa_proto_rawDescGZIP(), []int{8}
}

func (x *GetProjectConfigRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

// Message containing the response for getting the configuration of a project.
type GetProjectConfigResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Serialized configuration of the project.
	ConfigSerialized string `protobuf:"bytes,1,opt,name=config_serialized,json=configSerialized,proto3" json:"config_serialized,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetProjectConfigResponse) Reset() {
	*x = GetProjectConfigResponse{}
	mi := &file_ondewo_qa_qa_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectConfigResponse) ProtoMessage() {}

func (x *GetProjectConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_qa_qa_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectConfigResponse.ProtoReflect.Descriptor instead.
func (*GetProjectConfigResponse) Descriptor() ([]byte, []int) {
	return file_ondewo_qa_qa_proto_rawDescGZIP(), []int{9}
}

func (x *GetProjectConfigResponse) GetConfigSerialized() string {
	if x != nil {
		return x.ConfigSerialized
	}
	return ""
}

// Message for requesting a database update for specific projects.
type UpdateDatabaseRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of project IDs for which to update the database.
	ProjectIds    []string `protobuf:"bytes,1,rep,name=project_ids,json=projectIds,proto3" json:"project_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDatabaseRequest) Reset() {
	*x = UpdateDatabaseRequest{}
	mi := &file_ondewo_qa_qa_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDatabaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDatabaseRequest) ProtoMessage() {}

func (x *UpdateDatabaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_qa_qa_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDatabaseRequest.ProtoReflect.Descriptor instead.
func (*UpdateDatabaseRequest) Descriptor() ([]byte, []int) {
	return file_ondewo_qa_qa_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateDatabaseRequest) GetProjectIds() []string {
	if x != nil {
		return x.ProjectIds
	}
	return nil
}

// Message containing the response for updating the database of specific projects.
type UpdateDatabaseResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of error messages encountered during the database update.
	ErrorMessages []string `protobuf:"bytes,1,rep,name=error_messages,json=errorMessages,proto3" json:"error_messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDatabaseResponse) Reset() {
	*x = UpdateDatabaseResponse{}
	mi := &file_ondewo_qa_qa_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDatabaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDatabaseResponse) ProtoMessage() {}

func (x *UpdateDatabaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_qa_qa_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDatabaseResponse.ProtoReflect.Descriptor instead.
func (*UpdateDatabaseResponse) Descriptor() ([]byte, []int) {
	return file_ondewo_qa_qa_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateDatabaseResponse) GetErrorMessages() []string {
	if x != nil {
		return x.ErrorMessages
	}
	return nil
}

// Message representing a scraper container.
type RunScraperResponse_ScraperContainer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the Docker container running the job.
	ContainerName string `protobuf:"bytes,1,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	// ID of the Docker container running the scraping job.
	ContainerId   string `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunScraperResponse_ScraperContainer) Reset() {
	*x = RunScraperResponse_ScraperContainer{}
	mi := &file_ondewo_qa_qa_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunScraperResponse_ScraperContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunScraperResponse_ScraperContainer) ProtoMessage() {}

func (x *RunScraperResponse_ScraperContainer) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_qa_qa_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunScraperResponse_ScraperContainer.ProtoReflect.Descriptor instead.
func (*RunScraperResponse_ScraperContainer) Descriptor() ([]byte, []int) {
	return file_ondewo_qa_qa_proto_rawDescGZIP(), []int{3, 0}
}

func (x *RunScraperResponse_ScraperContainer) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *RunScraperResponse_ScraperContainer) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

var File_ondewo_qa_qa_proto protoreflect.FileDescriptor

const file_ondewo_qa_qa_proto_rawDesc = "" +
	"\n" +
	"\x12ondewo/qa/qa.proto\x12\tondewo.qa\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x18ondewo/nlu/session.proto\"\xee\x02\n" +
	"\x10GetAnswerRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12)\n" +
	"\x04text\x18\x02 \x01(\v2\x15.ondewo.nlu.TextInputR\x04text\x12&\n" +
	"\x0fmax_num_answers\x18\x03 \x01(\x05R\rmaxNumAnswers\x12)\n" +
	"\x10threshold_reader\x18\x04 \x01(\x02R\x0fthresholdReader\x12/\n" +
	"\x13threshold_retriever\x18\x05 \x01(\x02R\x12thresholdRetriever\x12+\n" +
	"\x11threshold_overall\x18\x06 \x01(\x02R\x10thresholdOverall\x12*\n" +
	"\x11reader_model_name\x18\a \x01(\tR\x0freaderModelName\x123\n" +
	"\n" +
	"url_filter\x18\b \x01(\v2\x14.ondewo.qa.UrlFilterR\turlFilter\"X\n" +
	"\x11GetAnswerResponse\x12C\n" +
	"\fquery_result\x18\x02 \x01(\v2 .ondewo.nlu.DetectIntentResponseR\vqueryResult\"4\n" +
	"\x11RunScraperRequest\x12\x1f\n" +
	"\vproject_ids\x18\x01 \x03(\tR\n" +
	"projectIds\"\xd1\x01\n" +
	"\x12RunScraperResponse\x12]\n" +
	"\x12scraper_containers\x18\x01 \x03(\v2..ondewo.qa.RunScraperResponse.ScraperContainerR\x11scraperContainers\x1a\\\n" +
	"\x10ScraperContainer\x12%\n" +
	"\x0econtainer_name\x18\x01 \x01(\tR\rcontainerName\x12!\n" +
	"\fcontainer_id\x18\x02 \x01(\tR\vcontainerId\"A\n" +
	"\x13RunTrainingResponse\x12\x0e\n" +
	"\x02f1\x18\x01 \x01(\x02R\x02f1\x12\x1a\n" +
	"\baccuracy\x18\x02 \x01(\x02R\baccuracy\"\x96\x01\n" +
	"\tUrlFilter\x12%\n" +
	"\x0eallowed_values\x18\x01 \x03(\tR\rallowedValues\x120\n" +
	"\x14regex_filter_include\x18\x02 \x01(\tR\x12regexFilterInclude\x120\n" +
	"\x14regex_filter_exclude\x18\x03 \x01(\tR\x12regexFilterExclude\"@\n" +
	"\x16GetServerStateResponse\x12&\n" +
	"\x0fserver_is_ready\x18\x01 \x01(\bR\rserverIsReady\"9\n" +
	"\x16ListProjectIdsResponse\x12\x1f\n" +
	"\vproject_ids\x18\x01 \x03(\tR\n" +
	"projectIds\"8\n" +
	"\x17GetProjectConfigRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\"G\n" +
	"\x18GetProjectConfigResponse\x12+\n" +
	"\x11config_serialized\x18\x01 \x01(\tR\x10configSerialized\"8\n" +
	"\x15UpdateDatabaseRequest\x12\x1f\n" +
	"\vproject_ids\x18\x01 \x03(\tR\n" +
	"projectIds\"?\n" +
	"\x16UpdateDatabaseResponse\x12%\n" +
	"\x0eerror_messages\x18\x01 \x03(\tR\rerrorMessages2\xe0\x05\n" +
	"\x02QA\x12V\n" +
	"\tGetAnswer\x12\x1b.ondewo.qa.GetAnswerRequest\x1a\x1c.ondewo.qa.GetAnswerResponse\"\x0e\x82\xd3\xe4\x93\x02\b:\x01*\"\x03/qa\x12a\n" +
	"\n" +
	"RunScraper\x12\x1c.ondewo.qa.RunScraperRequest\x1a\x1d.ondewo.qa.RunScraperResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/qa:RunScraper\x12q\n" +
	"\x0eUpdateDatabase\x12 .ondewo.qa.UpdateDatabaseRequest\x1a!.ondewo.qa.UpdateDatabaseResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/qa:UpdateDatabase\x12^\n" +
	"\vRunTraining\x12\x16.google.protobuf.Empty\x1a\x1e.ondewo.qa.RunTrainingResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/qa:RunTraining\x12g\n" +
	"\x0eGetServerState\x12\x16.google.protobuf.Empty\x1a!.ondewo.qa.GetServerStateResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/qa:GetServerState\x12g\n" +
	"\x0eListProjectIds\x12\x16.google.protobuf.Empty\x1a!.ondewo.qa.ListProjectIdsResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/qa:ListProjectIds\x12z\n" +
	"\x10GetProjectConfig\x12\".ondewo.qa.GetProjectConfigRequest\x1a#.ondewo.qa.GetProjectConfigResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/qa:ListProjectConfigb\x06proto3"

var (
	file_ondewo_qa_qa_proto_rawDescOnce sync.Once
	file_ondewo_qa_qa_proto_rawDescData []byte
)

func file_ondewo_qa_qa_proto_rawDescGZIP() []byte {
	file_ondewo_qa_qa_proto_rawDescOnce.Do(func() {
		file_ondewo_qa_qa_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ondewo_qa_qa_proto_rawDesc), len(file_ondewo_qa_qa_proto_rawDesc)))
	})
	return file_ondewo_qa_qa_proto_rawDescData
}

var file_ondewo_qa_qa_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_ondewo_qa_qa_proto_goTypes = []any{
	(*GetAnswerRequest)(nil),                    // 0: ondewo.qa.GetAnswerRequest
	(*GetAnswerResponse)(nil),                   // 1: ondewo.qa.GetAnswerResponse
	(*RunScraperRequest)(nil),                   // 2: ondewo.qa.RunScraperRequest
	(*RunScraperResponse)(nil),                  // 3: ondewo.qa.RunScraperResponse
	(*RunTrainingResponse)(nil),                 // 4: ondewo.qa.RunTrainingResponse
	(*UrlFilter)(nil),                           // 5: ondewo.qa.UrlFilter
	(*GetServerStateResponse)(nil),              // 6: ondewo.qa.GetServerStateResponse
	(*ListProjectIdsResponse)(nil),              // 7: ondewo.qa.ListProjectIdsResponse
	(*GetProjectConfigRequest)(nil),             // 8: ondewo.qa.GetProjectConfigRequest
	(*GetProjectConfigResponse)(nil),            // 9: ondewo.qa.GetProjectConfigResponse
	(*UpdateDatabaseRequest)(nil),               // 10: ondewo.qa.UpdateDatabaseRequest
	(*UpdateDatabaseResponse)(nil),              // 11: ondewo.qa.UpdateDatabaseResponse
	(*RunScraperResponse_ScraperContainer)(nil), // 12: ondewo.qa.RunScraperResponse.ScraperContainer
	(*nlu.TextInput)(nil),                       // 13: ondewo.nlu.TextInput
	(*nlu.DetectIntentResponse)(nil),            // 14: ondewo.nlu.DetectIntentResponse
	(*emptypb.Empty)(nil),                       // 15: google.protobuf.Empty
}
var file_ondewo_qa_qa_proto_depIdxs = []int32{
	13, // 0: ondewo.qa.GetAnswerRequest.text:type_name -> ondewo.nlu.TextInput
	5,  // 1: ondewo.qa.GetAnswerRequest.url_filter:type_name -> ondewo.qa.UrlFilter
	14, // 2: ondewo.qa.GetAnswerResponse.query_result:type_name -> ondewo.nlu.DetectIntentResponse
	12, // 3: ondewo.qa.RunScraperResponse.scraper_containers:type_name -> ondewo.qa.RunScraperResponse.ScraperContainer
	0,  // 4: ondewo.qa.QA.GetAnswer:input_type -> ondewo.qa.GetAnswerRequest
	2,  // 5: ondewo.qa.QA.RunScraper:input_type -> ondewo.qa.RunScraperRequest
	10, // 6: ondewo.qa.QA.UpdateDatabase:input_type -> ondewo.qa.UpdateDatabaseRequest
	15, // 7: ondewo.qa.QA.RunTraining:input_type -> google.protobuf.Empty
	15, // 8: ondewo.qa.QA.GetServerState:input_type -> google.protobuf.Empty
	15, // 9: ondewo.qa.QA.ListProjectIds:input_type -> google.protobuf.Empty
	8,  // 10: ondewo.qa.QA.GetProjectConfig:input_type -> ondewo.qa.GetProjectConfigRequest
	1,  // 11: ondewo.qa.QA.GetAnswer:output_type -> ondewo.qa.GetAnswerResponse
	3,  // 12: ondewo.qa.QA.RunScraper:output_type -> ondewo.qa.RunScraperResponse
	11, // 13: ondewo.qa.QA.UpdateDatabase:output_type -> ondewo.qa.UpdateDatabaseResponse
	4,  // 14: ondewo.qa.QA.RunTraining:output_type -> ondewo.qa.RunTrainingResponse
	6,  // 15: ondewo.qa.QA.GetServerState:output_type -> ondewo.qa.GetServerStateResponse
	7,  // 16: ondewo.qa.QA.ListProjectIds:output_type -> ondewo.qa.ListProjectIdsResponse
	9,  // 17: ondewo.qa.QA.GetProjectConfig:output_type -> ondewo.qa.GetProjectConfigResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_ondewo_qa_qa_proto_init() }
func file_ondewo_qa_qa_proto_init() {
	if File_ondewo_qa_qa_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ondewo_qa_qa_proto_rawDesc), len(file_ondewo_qa_qa_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ondewo_qa_qa_proto_goTypes,
		DependencyIndexes: file_ondewo_qa_qa_proto_depIdxs,
		MessageInfos:      file_ondewo_qa_qa_proto_msgTypes,
	}.Build()
	File_ondewo_qa_qa_proto = out.File
	file_ondewo_qa_qa_proto_goTypes = nil
	file_ondewo_qa_qa_proto_depIdxs = nil
}
