// Copyright 2021 ONDEWO GmbH
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.32.0
// source: ondewo/vtsi/logs.proto

package vtsi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Logs_StreamCallLogs_FullMethodName     = "/ondewo.vtsi.Logs/StreamCallLogs"
	Logs_ListCallLogs_FullMethodName       = "/ondewo.vtsi.Logs/ListCallLogs"
	Logs_GetCallLogStream_FullMethodName   = "/ondewo.vtsi.Logs/GetCallLogStream"
	Logs_ListCallLogStreams_FullMethodName = "/ondewo.vtsi.Logs/ListCallLogStreams"
	Logs_DeleteCallLogs_FullMethodName     = "/ondewo.vtsi.Logs/DeleteCallLogs"
)

// LogsClient is the client API for Logs service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// <p>ONDEWO VTSI API</p>
type LogsClient interface {
	// <p>Streams the container logs of the ondewo-sip / ondewo-csi containers of a VTSI project as
	// they are captured, in the manner of <code>docker logs --follow</code>. The stream replays
	// <code>tail_lines</code> historical entries and then follows. It stays open until the capture
	// of every matching log stream has terminated, until the client disconnects, or until the
	// server-side maximum stream duration is reached.</p>
	// <p>Entries are served from the VTSI database rather than from the docker daemon, so a
	// container that has already been removed still streams. Secrets are redacted server-side.</p>
	StreamCallLogs(ctx context.Context, in *StreamCallLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamCallLogsResponse], error)
	// <p>Returns a bounded, filtered page of captured container log entries. Supports a time window,
	// severity filtering, a regular expression, a plain-text search and cursor paging in both
	// directions for infinite scrolling. Secrets are redacted server-side.</p>
	ListCallLogs(ctx context.Context, in *ListCallLogsRequest, opts ...grpc.CallOption) (*ListCallLogsResponse, error)
	// <p>Returns the capture state of a single log stream, i.e. of one capture generation of one
	// container.</p>
	GetCallLogStream(ctx context.Context, in *GetCallLogStreamRequest, opts ...grpc.CallOption) (*CallLogStream, error)
	// <p>Lists the log streams VTSI has captured for a project. A single container yields a new log
	// stream every time it is recreated, because a recreated container is a new docker container
	// whose previous logs no longer exist.</p>
	ListCallLogStreams(ctx context.Context, in *ListCallLogStreamsRequest, opts ...grpc.CallOption) (*ListCallLogStreamsResponse, error)
	// <p>Permanently deletes captured log entries matching a filter. This is the erasure path for
	// data-subject requests: retention answers &quot;delete everything older than N days&quot;, this
	// answers &quot;delete everything for this call or this phone number&quot;.</p>
	DeleteCallLogs(ctx context.Context, in *DeleteCallLogsRequest, opts ...grpc.CallOption) (*DeleteCallLogsResponse, error)
}

type logsClient struct {
	cc grpc.ClientConnInterface
}

func NewLogsClient(cc grpc.ClientConnInterface) LogsClient {
	return &logsClient{cc}
}

func (c *logsClient) StreamCallLogs(ctx context.Context, in *StreamCallLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamCallLogsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Logs_ServiceDesc.Streams[0], Logs_StreamCallLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamCallLogsRequest, StreamCallLogsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Logs_StreamCallLogsClient = grpc.ServerStreamingClient[StreamCallLogsResponse]

func (c *logsClient) ListCallLogs(ctx context.Context, in *ListCallLogsRequest, opts ...grpc.CallOption) (*ListCallLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCallLogsResponse)
	err := c.cc.Invoke(ctx, Logs_ListCallLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logsClient) GetCallLogStream(ctx context.Context, in *GetCallLogStreamRequest, opts ...grpc.CallOption) (*CallLogStream, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallLogStream)
	err := c.cc.Invoke(ctx, Logs_GetCallLogStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logsClient) ListCallLogStreams(ctx context.Context, in *ListCallLogStreamsRequest, opts ...grpc.CallOption) (*ListCallLogStreamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCallLogStreamsResponse)
	err := c.cc.Invoke(ctx, Logs_ListCallLogStreams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logsClient) DeleteCallLogs(ctx context.Context, in *DeleteCallLogsRequest, opts ...grpc.CallOption) (*DeleteCallLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCallLogsResponse)
	err := c.cc.Invoke(ctx, Logs_DeleteCallLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogsServer is the server API for Logs service.
// All implementations must embed UnimplementedLogsServer
// for forward compatibility.
//
// <p>ONDEWO VTSI API</p>
type LogsServer interface {
	// <p>Streams the container logs of the ondewo-sip / ondewo-csi containers of a VTSI project as
	// they are captured, in the manner of <code>docker logs --follow</code>. The stream replays
	// <code>tail_lines</code> historical entries and then follows. It stays open until the capture
	// of every matching log stream has terminated, until the client disconnects, or until the
	// server-side maximum stream duration is reached.</p>
	// <p>Entries are served from the VTSI database rather than from the docker daemon, so a
	// container that has already been removed still streams. Secrets are redacted server-side.</p>
	StreamCallLogs(*StreamCallLogsRequest, grpc.ServerStreamingServer[StreamCallLogsResponse]) error
	// <p>Returns a bounded, filtered page of captured container log entries. Supports a time window,
	// severity filtering, a regular expression, a plain-text search and cursor paging in both
	// directions for infinite scrolling. Secrets are redacted server-side.</p>
	ListCallLogs(context.Context, *ListCallLogsRequest) (*ListCallLogsResponse, error)
	// <p>Returns the capture state of a single log stream, i.e. of one capture generation of one
	// container.</p>
	GetCallLogStream(context.Context, *GetCallLogStreamRequest) (*CallLogStream, error)
	// <p>Lists the log streams VTSI has captured for a project. A single container yields a new log
	// stream every time it is recreated, because a recreated container is a new docker container
	// whose previous logs no longer exist.</p>
	ListCallLogStreams(context.Context, *ListCallLogStreamsRequest) (*ListCallLogStreamsResponse, error)
	// <p>Permanently deletes captured log entries matching a filter. This is the erasure path for
	// data-subject requests: retention answers &quot;delete everything older than N days&quot;, this
	// answers &quot;delete everything for this call or this phone number&quot;.</p>
	DeleteCallLogs(context.Context, *DeleteCallLogsRequest) (*DeleteCallLogsResponse, error)
	mustEmbedUnimplementedLogsServer()
}

// UnimplementedLogsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLogsServer struct{}

func (UnimplementedLogsServer) StreamCallLogs(*StreamCallLogsRequest, grpc.ServerStreamingServer[StreamCallLogsResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamCallLogs not implemented")
}
func (UnimplementedLogsServer) ListCallLogs(context.Context, *ListCallLogsRequest) (*ListCallLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCallLogs not implemented")
}
func (UnimplementedLogsServer) GetCallLogStream(context.Context, *GetCallLogStreamRequest) (*CallLogStream, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCallLogStream not implemented")
}
func (UnimplementedLogsServer) ListCallLogStreams(context.Context, *ListCallLogStreamsRequest) (*ListCallLogStreamsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCallLogStreams not implemented")
}
func (UnimplementedLogsServer) DeleteCallLogs(context.Context, *DeleteCallLogsRequest) (*DeleteCallLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCallLogs not implemented")
}
func (UnimplementedLogsServer) mustEmbedUnimplementedLogsServer() {}
func (UnimplementedLogsServer) testEmbeddedByValue()              {}

// UnsafeLogsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogsServer will
// result in compilation errors.
type UnsafeLogsServer interface {
	mustEmbedUnimplementedLogsServer()
}

func RegisterLogsServer(s grpc.ServiceRegistrar, srv LogsServer) {
	// If the following call panics, it indicates UnimplementedLogsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Logs_ServiceDesc, srv)
}

func _Logs_StreamCallLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamCallLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LogsServer).StreamCallLogs(m, &grpc.GenericServerStream[StreamCallLogsRequest, StreamCallLogsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Logs_StreamCallLogsServer = grpc.ServerStreamingServer[StreamCallLogsResponse]

func _Logs_ListCallLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCallLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogsServer).ListCallLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Logs_ListCallLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogsServer).ListCallLogs(ctx, req.(*ListCallLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Logs_GetCallLogStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCallLogStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogsServer).GetCallLogStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Logs_GetCallLogStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogsServer).GetCallLogStream(ctx, req.(*GetCallLogStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Logs_ListCallLogStreams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCallLogStreamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogsServer).ListCallLogStreams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Logs_ListCallLogStreams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogsServer).ListCallLogStreams(ctx, req.(*ListCallLogStreamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Logs_DeleteCallLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCallLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogsServer).DeleteCallLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Logs_DeleteCallLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogsServer).DeleteCallLogs(ctx, req.(*DeleteCallLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Logs_ServiceDesc is the grpc.ServiceDesc for Logs service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Logs_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ondewo.vtsi.Logs",
	HandlerType: (*LogsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListCallLogs",
			Handler:    _Logs_ListCallLogs_Handler,
		},
		{
			MethodName: "GetCallLogStream",
			Handler:    _Logs_GetCallLogStream_Handler,
		},
		{
			MethodName: "ListCallLogStreams",
			Handler:    _Logs_ListCallLogStreams_Handler,
		},
		{
			MethodName: "DeleteCallLogs",
			Handler:    _Logs_DeleteCallLogs_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamCallLogs",
			Handler:       _Logs_StreamCallLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ondewo/vtsi/logs.proto",
}
