// Copyright 2021 ONDEWO GmbH
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.32.0
// source: ondewo/vtsi/projects.proto

package vtsi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	_ "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Status of a VtsiProject.
type VtsiProjectStatus int32

const (
	// No status specified
	VtsiProjectStatus_UNSPECIFIED VtsiProjectStatus = 0
	// Project successfully created and undeployed
	VtsiProjectStatus_UNDEPLOYED VtsiProjectStatus = 1
	// Project configuration is updating
	VtsiProjectStatus_UPDATING VtsiProjectStatus = 2
	// Project is deploying
	VtsiProjectStatus_DEPLOYING VtsiProjectStatus = 3
	// Project is deployed
	VtsiProjectStatus_DEPLOYED VtsiProjectStatus = 4
	// Project is un-deploying
	VtsiProjectStatus_UNDEPLOYING VtsiProjectStatus = 5
	// Project is currently deleting
	VtsiProjectStatus_DELETING VtsiProjectStatus = 6
	// Project is deleted
	VtsiProjectStatus_DELETED VtsiProjectStatus = 7
)

// Enum value maps for VtsiProjectStatus.
var (
	VtsiProjectStatus_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "UNDEPLOYED",
		2: "UPDATING",
		3: "DEPLOYING",
		4: "DEPLOYED",
		5: "UNDEPLOYING",
		6: "DELETING",
		7: "DELETED",
	}
	VtsiProjectStatus_value = map[string]int32{
		"UNSPECIFIED": 0,
		"UNDEPLOYED":  1,
		"UPDATING":    2,
		"DEPLOYING":   3,
		"DEPLOYED":    4,
		"UNDEPLOYING": 5,
		"DELETING":    6,
		"DELETED":     7,
	}
)

func (x VtsiProjectStatus) Enum() *VtsiProjectStatus {
	p := new(VtsiProjectStatus)
	*p = x
	return p
}

func (x VtsiProjectStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VtsiProjectStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_ondewo_vtsi_projects_proto_enumTypes[0].Descriptor()
}

func (VtsiProjectStatus) Type() protoreflect.EnumType {
	return &file_ondewo_vtsi_projects_proto_enumTypes[0]
}

func (x VtsiProjectStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VtsiProjectStatus.Descriptor instead.
func (VtsiProjectStatus) EnumDescriptor() ([]byte, []int) {
	return file_ondewo_vtsi_projects_proto_rawDescGZIP(), []int{0}
}

// Sorting mode
type VtsiProjectSortingMode int32

const (
	// The ascending sorting mode.
	// When sorting using this mode, VtsiProject objects will be arranged
	// in ascending order based on the specified criteria.
	VtsiProjectSortingMode_ASCENDING VtsiProjectSortingMode = 0
	// The descending sorting mode.
	// When sorting using this mode, VtsiProject objects will be arranged
	// in descending order based on the specified criteria.
	VtsiProjectSortingMode_DESCENDING VtsiProjectSortingMode = 1
)

// Enum value maps for VtsiProjectSortingMode.
var (
	VtsiProjectSortingMode_name = map[int32]string{
		0: "ASCENDING",
		1: "DESCENDING",
	}
	VtsiProjectSortingMode_value = map[string]int32{
		"ASCENDING":  0,
		"DESCENDING": 1,
	}
)

func (x VtsiProjectSortingMode) Enum() *VtsiProjectSortingMode {
	p := new(VtsiProjectSortingMode)
	*p = x
	return p
}

func (x VtsiProjectSortingMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VtsiProjectSortingMode) Descriptor() protoreflect.EnumDescriptor {
	return file_ondewo_vtsi_projects_proto_enumTypes[1].Descriptor()
}

func (VtsiProjectSortingMode) Type() protoreflect.EnumType {
	return &file_ondewo_vtsi_projects_proto_enumTypes[1]
}

func (x VtsiProjectSortingMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VtsiProjectSortingMode.Descriptor instead.
func (VtsiProjectSortingMode) EnumDescriptor() ([]byte, []int) {
	return file_ondewo_vtsi_projects_proto_rawDescGZIP(), []int{1}
}

// Structure of VTSI_PROJECT view
// <ul>
//
//	<li>CreateVTSI_PROJECT: VTSI_PROJECT_VIEW_SHALLOW</li>
//	<li>UpdateVTSI_PROJECT: VTSI_PROJECT_VIEW_SHALLOW</li>
//	<li>GetVTSI_PROJECT: VTSI_PROJECT_VIEW_FULL</li>
//	<li>ListVTSI_PROJECTs: VTSI_PROJECT_VIEW_SHALLOW</li>
//
// </ul>
type VtsiProjectView int32

const (
	// Unspecified VTSI_PROJECT view: the view is defined by the call:
	VtsiProjectView_VTSI_PROJECT_VIEW_UNSPECIFIED VtsiProjectView = 0
	// Full VTSI_PROJECT view: populate all the fields of the VTSI_PROJECT message including configs.
	VtsiProjectView_VTSI_PROJECT_VIEW_FULL VtsiProjectView = 1
	// Shallow VTSI_PROJECT view: populates all the fields except configs.
	VtsiProjectView_VTSI_PROJECT_VIEW_SHALLOW VtsiProjectView = 2
	// Minimum view including only VTSI_PROJECT UUID and VTSI_PROJECT display name
	VtsiProjectView_VTSI_PROJECT_VIEW_MINIMUM VtsiProjectView = 3
)

// Enum value maps for VtsiProjectView.
var (
	VtsiProjectView_name = map[int32]string{
		0: "VTSI_PROJECT_VIEW_UNSPECIFIED",
		1: "VTSI_PROJECT_VIEW_FULL",
		2: "VTSI_PROJECT_VIEW_SHALLOW",
		3: "VTSI_PROJECT_VIEW_MINIMUM",
	}
	VtsiProjectView_value = map[string]int32{
		"VTSI_PROJECT_VIEW_UNSPECIFIED": 0,
		"VTSI_PROJECT_VIEW_FULL":        1,
		"VTSI_PROJECT_VIEW_SHALLOW":     2,
		"VTSI_PROJECT_VIEW_MINIMUM":     3,
	}
)

func (x VtsiProjectView) Enum() *VtsiProjectView {
	p := new(VtsiProjectView)
	*p = x
	return p
}

func (x VtsiProjectView) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VtsiProjectView) Descriptor() protoreflect.EnumDescriptor {
	return file_ondewo_vtsi_projects_proto_enumTypes[2].Descriptor()
}

func (VtsiProjectView) Type() protoreflect.EnumType {
	return &file_ondewo_vtsi_projects_proto_enumTypes[2]
}

func (x VtsiProjectView) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VtsiProjectView.Descriptor instead.
func (VtsiProjectView) EnumDescriptor() ([]byte, []int) {
	return file_ondewo_vtsi_projects_proto_rawDescGZIP(), []int{2}
}

// Enum to specify the sorting field for VTSI projects.
// Enum defining the field by which VTSI projects can be sorted
type VtsiProjectSorting_VtsiProjectSortingField int32

const (
	// No sorting
	VtsiProjectSorting_NO_VTSI_PROJECT_SORTING VtsiProjectSorting_VtsiProjectSortingField = 0
	// Sort by project name such as <pre><code>projects/&lt;project_uuid&gt;/project</code></pre>.
	VtsiProjectSorting_SORT_VTSI_PROJECT_BY_NAME VtsiProjectSorting_VtsiProjectSortingField = 1
	// Sort by display name
	VtsiProjectSorting_SORT_VTSI_PROJECT_BY_DISPLAY_NAME VtsiProjectSorting_VtsiProjectSortingField = 2
	// Sort by creation date
	VtsiProjectSorting_SORT_VTSI_PROJECT_BY_CREATION_DATE VtsiProjectSorting_VtsiProjectSortingField = 3
	// Sort by last modified date
	VtsiProjectSorting_SORT_VTSI_PROJECT_BY_LAST_MODIFIED VtsiProjectSorting_VtsiProjectSortingField = 4
)

// Enum value maps for VtsiProjectSorting_VtsiProjectSortingField.
var (
	VtsiProjectSorting_VtsiProjectSortingField_name = map[int32]string{
		0: "NO_VTSI_PROJECT_SORTING",
		1: "SORT_VTSI_PROJECT_BY_NAME",
		2: "SORT_VTSI_PROJECT_BY_DISPLAY_NAME",
		3: "SORT_VTSI_PROJECT_BY_CREATION_DATE",
		4: "SORT_VTSI_PROJECT_BY_LAST_MODIFIED",
	}
	VtsiProjectSorting_VtsiProjectSortingField_value = map[string]int32{
		"NO_VTSI_PROJECT_SORTING":            0,
		"SORT_VTSI_PROJECT_BY_NAME":          1,
		"SORT_VTSI_PROJECT_BY_DISPLAY_NAME":  2,
		"SORT_VTSI_PROJECT_BY_CREATION_DATE": 3,
		"SORT_VTSI_PROJECT_BY_LAST_MODIFIED": 4,
	}
)

func (x VtsiProjectSorting_VtsiProjectSortingField) Enum() *VtsiProjectSorting_VtsiProjectSortingField {
	p := new(VtsiProjectSorting_VtsiProjectSortingField)
	*p = x
	return p
}

func (x VtsiProjectSorting_VtsiProjectSortingField) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VtsiProjectSorting_VtsiProjectSortingField) Descriptor() protoreflect.EnumDescriptor {
	return file_ondewo_vtsi_projects_proto_enumTypes[3].Descriptor()
}

func (VtsiProjectSorting_VtsiProjectSortingField) Type() protoreflect.EnumType {
	return &file_ondewo_vtsi_projects_proto_enumTypes[3]
}

func (x VtsiProjectSorting_VtsiProjectSortingField) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VtsiProjectSorting_VtsiProjectSortingField.Descriptor instead.
func (VtsiProjectSorting_VtsiProjectSortingField) EnumDescriptor() ([]byte, []int) {
	return file_ondewo_vtsi_projects_proto_rawDescGZIP(), []int{9, 0}
}

// The VTSI project with its configuration setting
type VtsiProject struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The project name.
	// Format: <pre><code>projects/&lt;project_uuid&gt;/project</code></pre>
	// Only when a new VtsiProject is created the name can be undefined/empty
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// OPTIONAL: The display name of the project
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// The maximum number of callers that this project can have.
	MaxCallers int32 `protobuf:"varint,3,opt,name=max_callers,json=maxCallers,proto3" json:"max_callers,omitempty"`
	// The maximum number of listeners that this project can have.
	MaxListeners int32 `protobuf:"varint,4,opt,name=max_listeners,json=maxListeners,proto3" json:"max_listeners,omitempty"`
	// Configs to start the asterisk server.
	AsteriskConfigs *AsteriskConfigs `protobuf:"bytes,5,opt,name=asterisk_configs,json=asteriskConfigs,proto3" json:"asterisk_configs,omitempty"`
	// The status of the VTSI project.
	VtsiProjectStatus VtsiProjectStatus `protobuf:"varint,6,opt,name=vtsi_project_status,json=vtsiProjectStatus,proto3,enum=ondewo.vtsi.VtsiProjectStatus" json:"vtsi_project_status,omitempty"`
	// The user who created the vtsi project. Readonly.
	CreatedBy string `protobuf:"bytes,7,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	// Creation time of the vtsi project. Readonly.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// The user who modified the vtsi project. Readonly.
	ModifiedBy string `protobuf:"bytes,9,opt,name=modified_by,json=modifiedBy,proto3" json:"modified_by,omitempty"`
	// Modification time of the vtsi project. Readonly.
	ModifiedAt *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=modified_at,json=modifiedAt,proto3" json:"modified_at,omitempty"`
	// The number of active callers in this project.
	ActiveCallers int32 `protobuf:"varint,11,opt,name=active_callers,json=activeCallers,proto3" json:"active_callers,omitempty"`
	// The number of active listeners in this project.
	ActiveListeners int32 `protobuf:"varint,12,opt,name=active_listeners,json=activeListeners,proto3" json:"active_listeners,omitempty"`
	// The port of the asterisk server
	AsteriskPort int32 `protobuf:"varint,13,opt,name=asterisk_port,json=asteriskPort,proto3" json:"asterisk_port,omitempty"`
	// Associated NLU agents.
	// Format: <pre><code>projects/&lt;Project ID&gt;/agent</code></pre>
	NluAgentNames []string `protobuf:"bytes,14,rep,name=nlu_agent_names,json=nluAgentNames,proto3" json:"nlu_agent_names,omitempty"`
	// The number of deployed callers in this project.
	DeployedCallers int32 `protobuf:"varint,15,opt,name=deployed_callers,json=deployedCallers,proto3" json:"deployed_callers,omitempty"`
	// The number of deployed listeners in this project.
	DeployedListeners int32 `protobuf:"varint,16,opt,name=deployed_listeners,json=deployedListeners,proto3" json:"deployed_listeners,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VtsiProject) Reset() {
	*x = VtsiProject{}
	mi := &file_ondewo_vtsi_projects_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VtsiProject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VtsiProject) ProtoMessage() {}

func (x *VtsiProject) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_vtsi_projects_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VtsiProject.ProtoReflect.Descriptor instead.
func (*VtsiProject) Descriptor() ([]byte, []int) {
	return file_ondewo_vtsi_projects_proto_rawDescGZIP(), []int{0}
}

func (x *VtsiProject) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VtsiProject) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *VtsiProject) GetMaxCallers() int32 {
	if x != nil {
		return x.MaxCallers
	}
	return 0
}

func (x *VtsiProject) GetMaxListeners() int32 {
	if x != nil {
		return x.MaxListeners
	}
	return 0
}

func (x *VtsiProject) GetAsteriskConfigs() *AsteriskConfigs {
	if x != nil {
		return x.AsteriskConfigs
	}
	return nil
}

func (x *VtsiProject) GetVtsiProjectStatus() VtsiProjectStatus {
	if x != nil {
		return x.VtsiProjectStatus
	}
	return VtsiProjectStatus_UNSPECIFIED
}

func (x *VtsiProject) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *VtsiProject) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *VtsiProject) GetModifiedBy() string {
	if x != nil {
		return x.ModifiedBy
	}
	return ""
}

func (x *VtsiProject) GetModifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ModifiedAt
	}
	return nil
}

func (x *VtsiProject) GetActiveCallers() int32 {
	if x != nil {
		return x.ActiveCallers
	}
	return 0
}

func (x *VtsiProject) GetActiveListeners() int32 {
	if x != nil {
		return x.ActiveListeners
	}
	return 0
}

func (x *VtsiProject) GetAsteriskPort() int32 {
	if x != nil {
		return x.AsteriskPort
	}
	return 0
}

func (x *VtsiProject) GetNluAgentNames() []string {
	if x != nil {
		return x.NluAgentNames
	}
	return nil
}

func (x *VtsiProject) GetDeployedCallers() int32 {
	if x != nil {
		return x.DeployedCallers
	}
	return 0
}

func (x *VtsiProject) GetDeployedListeners() int32 {
	if x != nil {
		return x.DeployedListeners
	}
	return 0
}

// Configuration variables for the Asterisk server
type AsteriskConfigsVariables struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SIP trunk username.
	SipTrunkUsername string `protobuf:"bytes,1,opt,name=sip_trunk_username,json=sipTrunkUsername,proto3" json:"sip_trunk_username,omitempty"`
	// SIP trunk password.
	SipTrunkPassword string `protobuf:"bytes,2,opt,name=sip_trunk_password,json=sipTrunkPassword,proto3" json:"sip_trunk_password,omitempty"`
	// SIP trunk host.
	SipTrunkHost string `protobuf:"bytes,3,opt,name=sip_trunk_host,json=sipTrunkHost,proto3" json:"sip_trunk_host,omitempty"`
	// Transfer number.
	TransferNumber string `protobuf:"bytes,4,opt,name=transfer_number,json=transferNumber,proto3" json:"transfer_number,omitempty"`
	// Transfer number host.
	TransferNumberHost string `protobuf:"bytes,5,opt,name=transfer_number_host,json=transferNumberHost,proto3" json:"transfer_number_host,omitempty"`
	// SIP trunk phone number / caller id.
	SipTrunkPhoneNumber string `protobuf:"bytes,6,opt,name=sip_trunk_phone_number,json=sipTrunkPhoneNumber,proto3" json:"sip_trunk_phone_number,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AsteriskConfigsVariables) Reset() {
	*x = AsteriskConfigsVariables{}
	mi := &file_ondewo_vtsi_projects_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AsteriskConfigsVariables) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsteriskConfigsVariables) ProtoMessage() {}

func (x *AsteriskConfigsVariables) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_vtsi_projects_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsteriskConfigsVariables.ProtoReflect.Descriptor instead.
func (*AsteriskConfigsVariables) Descriptor() ([]byte, []int) {
	return file_ondewo_vtsi_projects_proto_rawDescGZIP(), []int{1}
}

func (x *AsteriskConfigsVariables) GetSipTrunkUsername() string {
	if x != nil {
		return x.SipTrunkUsername
	}
	return ""
}

func (x *AsteriskConfigsVariables) GetSipTrunkPassword() string {
	if x != nil {
		return x.SipTrunkPassword
	}
	return ""
}

func (x *AsteriskConfigsVariables) GetSipTrunkHost() string {
	if x != nil {
		return x.SipTrunkHost
	}
	return ""
}

func (x *AsteriskConfigsVariables) GetTransferNumber() string {
	if x != nil {
		return x.TransferNumber
	}
	return ""
}

func (x *AsteriskConfigsVariables) GetTransferNumberHost() string {
	if x != nil {
		return x.TransferNumberHost
	}
	return ""
}

func (x *AsteriskConfigsVariables) GetSipTrunkPhoneNumber() string {
	if x != nil {
		return x.SipTrunkPhoneNumber
	}
	return ""
}

// Configuration files for the Asterisk server
type AsteriskConfigsFiles struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// sip.conf file as string
	SipConfFileString string `protobuf:"bytes,1,opt,name=sip_conf_file_string,json=sipConfFileString,proto3" json:"sip_conf_file_string,omitempty"`
	// extensions.conf file as string
	ExtensionsConfFileString string `protobuf:"bytes,2,opt,name=extensions_conf_file_string,json=extensionsConfFileString,proto3" json:"extensions_conf_file_string,omitempty"`
	// queues.conf file as string
	QueuesConfFileString string `protobuf:"bytes,3,opt,name=queues_conf_file_string,json=queuesConfFileString,proto3" json:"queues_conf_file_string,omitempty"`
	// modules.conf file as string
	ModulesConfFileString string `protobuf:"bytes,4,opt,name=modules_conf_file_string,json=modulesConfFileString,proto3" json:"modules_conf_file_string,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AsteriskConfigsFiles) Reset() {
	*x = AsteriskConfigsFiles{}
	mi := &file_ondewo_vtsi_projects_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AsteriskConfigsFiles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsteriskConfigsFiles) ProtoMessage() {}

func (x *AsteriskConfigsFiles) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_vtsi_projects_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsteriskConfigsFiles.ProtoReflect.Descriptor instead.
func (*AsteriskConfigsFiles) Descriptor() ([]byte, []int) {
	return file_ondewo_vtsi_projects_proto_rawDescGZIP(), []int{2}
}

func (x *AsteriskConfigsFiles) GetSipConfFileString() string {
	if x != nil {
		return x.SipConfFileString
	}
	return ""
}

func (x *AsteriskConfigsFiles) GetExtensionsConfFileString() string {
	if x != nil {
		return x.ExtensionsConfFileString
	}
	return ""
}

func (x *AsteriskConfigsFiles) GetQueuesConfFileString() string {
	if x != nil {
		return x.QueuesConfFileString
	}
	return ""
}

func (x *AsteriskConfigsFiles) GetModulesConfFileString() string {
	if x != nil {
		return x.ModulesConfFileString
	}
	return ""
}

// Configurations object for the Asterisk server
type AsteriskConfigs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to AsteriskConfigsOneof:
	//
	//	*AsteriskConfigs_AsteriskConfigsVariables
	//	*AsteriskConfigs_AsteriskConfigsFiles
	//	*AsteriskConfigs_AsteriskConfigsTargetDirectoryName
	AsteriskConfigsOneof isAsteriskConfigs_AsteriskConfigsOneof `protobuf_oneof:"asterisk_configs_oneof"`
	// OPTIONAL: The port where Asterisk should start.
	AsteriskPort int32 `protobuf:"varint,4,opt,name=asterisk_port,json=asteriskPort,proto3" json:"asterisk_port,omitempty"`
	// OPTIONAL: The Asterisk version to start, given as the docker image tag of the ONDEWO
	// Asterisk image, e.g. <pre><code>alpine-3.18-18.20.2</code></pre>.
	// The tag must match the docker tag grammar
	// <pre><code>[A-Za-z0-9_][A-Za-z0-9._-]{0,127}</code></pre>.
	// Explicitly optional: when the field is not set, the server keeps using its configured
	// default (the <pre><code>ONDEWO_VTSI_ASTERISK_IMAGE_TAG</code></pre> environment variable).
	// Sending an empty string is NOT the same as leaving it unset and is rejected.
	AsteriskVersion *string `protobuf:"bytes,5,opt,name=asterisk_version,json=asteriskVersion,proto3,oneof" json:"asterisk_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AsteriskConfigs) Reset() {
	*x = AsteriskConfigs{}
	mi := &file_ondewo_vtsi_projects_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AsteriskConfigs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsteriskConfigs) ProtoMessage() {}

func (x *AsteriskConfigs) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_vtsi_projects_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsteriskConfigs.ProtoReflect.Descriptor instead.
func (*AsteriskConfigs) Descriptor() ([]byte, []int) {
	return file_ondewo_vtsi_projects_proto_rawDescGZIP(), []int{3}
}

func (x *AsteriskConfigs) GetAsteriskConfigsOneof() isAsteriskConfigs_AsteriskConfigsOneof {
	if x != nil {
		return x.AsteriskConfigsOneof
	}
	return nil
}

func (x *AsteriskConfigs) GetAsteriskConfigsVariables() *AsteriskConfigsVariables {
	if x != nil {
		if x, ok := x.AsteriskConfigsOneof.(*AsteriskConfigs_AsteriskConfigsVariables); ok {
			return x.AsteriskConfigsVariables
		}
	}
	return nil
}

func (x *AsteriskConfigs) GetAsteriskConfigsFiles() *AsteriskConfigsFiles {
	if x != nil {
		if x, ok := x.AsteriskConfigsOneof.(*AsteriskConfigs_AsteriskConfigsFiles); ok {
			return x.AsteriskConfigsFiles
		}
	}
	return nil
}

func (x *AsteriskConfigs) GetAsteriskConfigsTargetDirectoryName() string {
	if x != nil {
		if x, ok := x.AsteriskConfigsOneof.(*AsteriskConfigs_AsteriskConfigsTargetDirectoryName); ok {
			return x.AsteriskConfigsTargetDirectoryName
		}
	}
	return ""
}

func (x *AsteriskConfigs) GetAsteriskPort() int32 {
	if x != nil {
		return x.AsteriskPort
	}
	return 0
}

func (x *AsteriskConfigs) GetAsteriskVersion() string {
	if x != nil && x.AsteriskVersion != nil {
		return *x.AsteriskVersion
	}
	return ""
}

type isAsteriskConfigs_AsteriskConfigsOneof interface {
	isAsteriskConfigs_AsteriskConfigsOneof()
}

type AsteriskConfigs_AsteriskConfigsVariables struct {
	// Configs as variables which will fill those variables using a blue print.
	AsteriskConfigsVariables *AsteriskConfigsVariables `protobuf:"bytes,1,opt,name=asterisk_configs_variables,json=asteriskConfigsVariables,proto3,oneof"`
}

type AsteriskConfigs_AsteriskConfigsFiles struct {
	// Configs as files which will set up the configs using those files.
	AsteriskConfigsFiles *AsteriskConfigsFiles `protobuf:"bytes,2,opt,name=asterisk_configs_files,json=asteriskConfigsFiles,proto3,oneof"`
}

type AsteriskConfigs_AsteriskConfigsTargetDirectoryName struct {
	// Configs will be mapped in from a preconfigured asterisk target directory.
	AsteriskConfigsTargetDirectoryName string `protobuf:"bytes,3,opt,name=asterisk_configs_target_directory_name,json=asteriskConfigsTargetDirectoryName,proto3,oneof"`
}

func (*AsteriskConfigs_AsteriskConfigsVariables) isAsteriskConfigs_AsteriskConfigsOneof() {}

func (*AsteriskConfigs_AsteriskConfigsFiles) isAsteriskConfigs_AsteriskConfigsOneof() {}

func (*AsteriskConfigs_AsteriskConfigsTargetDirectoryName) isAsteriskConfigs_AsteriskConfigsOneof() {}

// Request for creating a VTSI project
type CreateVtsiProjectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// VTSI project
	// Recommended is to leave &quot;name&quot; empty. The project name here is optional.
	// If no name is given a new parent name is created. The parent has the format:
	// <pre><code>projects/&lt;project_uuid&gt;/project</code></pre>
	VtsiProject *VtsiProject `protobuf:"bytes,1,opt,name=vtsi_project,json=vtsiProject,proto3" json:"vtsi_project,omitempty"`
	// error message if there are any.
	ErrorMessage  string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVtsiProjectRequest) Reset() {
	*x = CreateVtsiProjectRequest{}
	mi := &file_ondewo_vtsi_projects_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVtsiProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVtsiProjectRequest) ProtoMessage() {}

func (x *CreateVtsiProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_vtsi_projects_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVtsiProjectRequest.ProtoReflect.Descriptor instead.
func (*CreateVtsiProjectRequest) Descriptor() ([]byte, []int) {
	return file_ondewo_vtsi_projects_proto_rawDescGZIP(), []int{4}
}

func (x *CreateVtsiProjectRequest) GetVtsiProject() *VtsiProject {
	if x != nil {
		return x.VtsiProject
	}
	return nil
}

func (x *CreateVtsiProjectRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Response of the create project
type CreateVtsiProjectResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Vtsi project
	VtsiProject *VtsiProject `protobuf:"bytes,1,opt,name=vtsi_project,json=vtsiProject,proto3" json:"vtsi_project,omitempty"`
	// error message if there are any.
	ErrorMessage  string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVtsiProjectResponse) Reset() {
	*x = CreateVtsiProjectResponse{}
	mi := &file_ondewo_vtsi_projects_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVtsiProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVtsiProjectResponse) ProtoMessage() {}

func (x *CreateVtsiProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_vtsi_projects_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVtsiProjectResponse.ProtoReflect.Descriptor instead.
func (*CreateVtsiProjectResponse) Descriptor() ([]byte, []int) {
	return file_ondewo_vtsi_projects_proto_rawDescGZIP(), []int{5}
}

func (x *CreateVtsiProjectResponse) GetVtsiProject() *VtsiProject {
	if x != nil {
		return x.VtsiProject
	}
	return nil
}

func (x *CreateVtsiProjectResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Request to retrieve a VTSI project
type GetVtsiProjectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// VTSI project name with which to perform the call of the form <pre><code>projects/&lt;project_uuid&gt;/project</code></pre>
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Optional. Specify the view of the returned VtsiProject (full view by default)
	VtsiProjectView VtsiProjectView `protobuf:"varint,2,opt,name=vtsi_project_view,json=vtsiProjectView,proto3,enum=ondewo.vtsi.VtsiProjectView" json:"vtsi_project_view,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetVtsiProjectRequest) Reset() {
	*x = GetVtsiProjectRequest{}
	mi := &file_ondewo_vtsi_projects_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVtsiProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVtsiProjectRequest) ProtoMessage() {}

func (x *GetVtsiProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_vtsi_projects_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVtsiProjectRequest.ProtoReflect.Descriptor instead.
func (*GetVtsiProjectRequest) Descriptor() ([]byte, []int) {
	return file_ondewo_vtsi_projects_proto_rawDescGZIP(), []int{6}
}

func (x *GetVtsiProjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetVtsiProjectRequest) GetVtsiProjectView() VtsiProjectView {
	if x != nil {
		return x.VtsiProjectView
	}
	return VtsiProjectView_VTSI_PROJECT_VIEW_UNSPECIFIED
}

// Request to get the list of agents
type ListVtsiProjectsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional. Specify the view of the returned VtsiProject (full view by default)
	VtsiProjectView VtsiProjectView `protobuf:"varint,1,opt,name=vtsi_project_view,json=vtsiProjectView,proto3,enum=ondewo.vtsi.VtsiProjectView" json:"vtsi_project_view,omitempty"`
	// Optional. The next_page_token value returned from a previous list request.
	// Example: "current_index-1--page_size-20"
	PageToken *string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3,oneof" json:"page_token,omitempty"`
	// Optional. Field to define the sorting of the list of VTSI projects in the response.
	// If not specified, the default behavior is to have no sorting.
	VtsiProjectSorting *VtsiProjectSorting `protobuf:"bytes,3,opt,name=vtsi_project_sorting,json=vtsiProjectSorting,proto3,oneof" json:"vtsi_project_sorting,omitempty"`
	// Optional. Filter based on associated NLU agents.
	// Format: <pre><code>projects/&lt;Project ID&gt;/agent</code></pre>
	NluAgentNames []string `protobuf:"bytes,4,rep,name=nlu_agent_names,json=nluAgentNames,proto3" json:"nlu_agent_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVtsiProjectsRequest) Reset() {
	*x = ListVtsiProjectsRequest{}
	mi := &file_ondewo_vtsi_projects_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVtsiProjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVtsiProjectsRequest) ProtoMessage() {}

func (x *ListVtsiProjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_vtsi_projects_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVtsiProjectsRequest.ProtoReflect.Descriptor instead.
func (*ListVtsiProjectsRequest) Descriptor() ([]byte, []int) {
	return file_ondewo_vtsi_projects_proto_rawDescGZIP(), []int{7}
}

func (x *ListVtsiProjectsRequest) GetVtsiProjectView() VtsiProjectView {
	if x != nil {
		return x.VtsiProjectView
	}
	return VtsiProjectView_VTSI_PROJECT_VIEW_UNSPECIFIED
}

func (x *ListVtsiProjectsRequest) GetPageToken() string {
	if x != nil && x.PageToken != nil {
		return *x.PageToken
	}
	return ""
}

func (x *ListVtsiProjectsRequest) GetVtsiProjectSorting() *VtsiProjectSorting {
	if x != nil {
		return x.VtsiProjectSorting
	}
	return nil
}

func (x *ListVtsiProjectsRequest) GetNluAgentNames() []string {
	if x != nil {
		return x.NluAgentNames
	}
	return nil
}

// This is a protobuf message definition for the response of getting a list of VTSI projects.
type ListVtsiProjectsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of VTSI projects returned in the response.
	// Use the &apos;repeated&apos; keyword to indicate that this field can contain multiple instances of VtsiProject.
	VtsiProjects []*VtsiProject `protobuf:"bytes,1,rep,name=vtsi_projects,json=vtsiProjects,proto3" json:"vtsi_projects,omitempty"`
	// Token to retrieve the next page of results.
	// This field is a string that holds a token for fetching the next page of results.
	// If there are no more results in the list, this field will be empty.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVtsiProjectsResponse) Reset() {
	*x = ListVtsiProjectsResponse{}
	mi := &file_ondewo_vtsi_projects_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVtsiProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVtsiProjectsResponse) ProtoMessage() {}

func (x *ListVtsiProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_vtsi_projects_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVtsiProjectsResponse.ProtoReflect.Descriptor instead.
func (*ListVtsiProjectsResponse) Descriptor() ([]byte, []int) {
	return file_ondewo_vtsi_projects_proto_rawDescGZIP(), []int{8}
}

func (x *ListVtsiProjectsResponse) GetVtsiProjects() []*VtsiProject {
	if x != nil {
		return x.VtsiProjects
	}
	return nil
}

func (x *ListVtsiProjectsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// This protobuf message defines the sorting order for VTSI (Virtual Test System Infrastructure) projects.
type VtsiProjectSorting struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// sorting field for vtsi projects sorting
	SortingField *VtsiProjectSorting_VtsiProjectSortingField `protobuf:"varint,1,opt,name=sorting_field,json=sortingField,proto3,enum=ondewo.vtsi.VtsiProjectSorting_VtsiProjectSortingField,oneof" json:"sorting_field,omitempty"`
	// Sorting mode
	SortingMode   *VtsiProjectSortingMode `protobuf:"varint,2,opt,name=sorting_mode,json=sortingMode,proto3,enum=ondewo.vtsi.VtsiProjectSortingMode,oneof" json:"sorting_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VtsiProjectSorting) Reset() {
	*x = VtsiProjectSorting{}
	mi := &file_ondewo_vtsi_projects_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VtsiProjectSorting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VtsiProjectSorting) ProtoMessage() {}

func (x *VtsiProjectSorting) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_vtsi_projects_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VtsiProjectSorting.ProtoReflect.Descriptor instead.
func (*VtsiProjectSorting) Descriptor() ([]byte, []int) {
	return file_ondewo_vtsi_projects_proto_rawDescGZIP(), []int{9}
}

func (x *VtsiProjectSorting) GetSortingField() VtsiProjectSorting_VtsiProjectSortingField {
	if x != nil && x.SortingField != nil {
		return *x.SortingField
	}
	return VtsiProjectSorting_NO_VTSI_PROJECT_SORTING
}

func (x *VtsiProjectSorting) GetSortingMode() VtsiProjectSortingMode {
	if x != nil && x.SortingMode != nil {
		return *x.SortingMode
	}
	return VtsiProjectSortingMode_ASCENDING
}

// Request to updated VTSI project
type UpdateVtsiProjectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Project Configs.
	VtsiProject *VtsiProject `protobuf:"bytes,1,opt,name=vtsi_project,json=vtsiProject,proto3" json:"vtsi_project,omitempty"`
	// OPTIONAL: The mask to control which fields get updated.
	// Paths are field paths within <pre><code>vtsi_project</code></pre> and carry no leading
	// <pre><code>vtsi_project.</code></pre> prefix, e.g. <pre><code>display_name</code></pre>,
	// <pre><code>max_callers</code></pre>, <pre><code>nlu_agent_names</code></pre> or
	// <pre><code>asterisk_configs.asterisk_version</code></pre>.
	// Semantics:
	// <ul>
	//   <li>Mask unset or empty: the update is merged additively over the stored project, which is
	//       the behaviour of every release before this field existed.</li>
	//   <li>Path in the mask and set in <pre><code>vtsi_project</code></pre>: the field is written
	//       with the value sent.</li>
	//   <li>Path in the mask but NOT set in <pre><code>vtsi_project</code></pre>: the field is
	//       CLEARED, i.e. reset to its default. This is the only way to unset a field: a scalar
	//       carries no presence, so an additive merge cannot distinguish
	//       &quot;reset this to the default&quot; from &quot;say nothing about it&quot;, and the
	//       stored value survives. It is what makes an <pre><code>asterisk_version</code></pre>
	//       that has once been pinned track the deployment default again.</li>
	//   <li>Path absent from the mask: the field is left untouched, whether or not
	//       <pre><code>vtsi_project</code></pre> carries a value for it.</li>
	//   <li>Path the server does not recognise: the request is REFUSED with
	//       <pre><code>INVALID_ARGUMENT</code></pre> naming the path. It is never ignored.
	//       This matters most for the one mistake this surface invites: ONDEWO's own
	//       <pre><code>ondewo.nlu.UpdateAgentRequest</code></pre> documents the PREFIXED form
	//       (<pre><code>agent.display_name</code></pre>), so a caller who copies that sibling will
	//       send <pre><code>vtsi_project.display_name</code></pre> here. Silently ignoring it would
	//       leave the field un-cleared while the call reported success - the exact failure this
	//       field exists to remove - so an unrecognised path fails loudly at the first request
	//       instead.</li>
	// </ul>
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVtsiProjectRequest) Reset() {
	*x = UpdateVtsiProjectRequest{}
	mi := &file_ondewo_vtsi_projects_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVtsiProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVtsiProjectRequest) ProtoMessage() {}

func (x *UpdateVtsiProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_vtsi_projects_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVtsiProjectRequest.ProtoReflect.Descriptor instead.
func (*UpdateVtsiProjectRequest) Descriptor() ([]byte, []int) {
	return file_ondewo_vtsi_projects_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateVtsiProjectRequest) GetVtsiProject() *VtsiProject {
	if x != nil {
		return x.VtsiProject
	}
	return nil
}

func (x *UpdateVtsiProjectRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

// Request to updated VTSI project
type UpdateVtsiProjectResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// VTSI project name with which to perform the call of the form <pre><code>projects/&lt;project_uuid&gt;/project</code></pre>
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// error message if there are any.
	ErrorMessage  string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVtsiProjectResponse) Reset() {
	*x = UpdateVtsiProjectResponse{}
	mi := &file_ondewo_vtsi_projects_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVtsiProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVtsiProjectResponse) ProtoMessage() {}

func (x *UpdateVtsiProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_vtsi_projects_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVtsiProjectResponse.ProtoReflect.Descriptor instead.
func (*UpdateVtsiProjectResponse) Descriptor() ([]byte, []int) {
	return file_ondewo_vtsi_projects_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateVtsiProjectResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateVtsiProjectResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Request to delete a VTSI project
// If a deployed VTSI project was deleted then it was undeployed beforehand automatically
type DeleteVtsiProjectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// VTSI project name with which to perform the call of the form <pre><code>projects/&lt;project_uuid&gt;/project</code></pre>
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVtsiProjectRequest) Reset() {
	*x = DeleteVtsiProjectRequest{}
	mi := &file_ondewo_vtsi_projects_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVtsiProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVtsiProjectRequest) ProtoMessage() {}

func (x *DeleteVtsiProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_vtsi_projects_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVtsiProjectRequest.ProtoReflect.Descriptor instead.
func (*DeleteVtsiProjectRequest) Descriptor() ([]byte, []int) {
	return file_ondewo_vtsi_projects_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteVtsiProjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Response to delete a VTSI project
// If a deployed VTSI project was deleted then it was undeployed beforehand automatically
type DeleteVtsiProjectResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// VTSI project name with which to perform the call of the form <pre><code>projects/&lt;project_uuid&gt;/project</code></pre>
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// error message if there are any.
	ErrorMessage  string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVtsiProjectResponse) Reset() {
	*x = DeleteVtsiProjectResponse{}
	mi := &file_ondewo_vtsi_projects_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVtsiProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVtsiProjectResponse) ProtoMessage() {}

func (x *DeleteVtsiProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_vtsi_projects_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVtsiProjectResponse.ProtoReflect.Descriptor instead.
func (*DeleteVtsiProjectResponse) Descriptor() ([]byte, []int) {
	return file_ondewo_vtsi_projects_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteVtsiProjectResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeleteVtsiProjectResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Request to deploy a vtsi project
type DeployVtsiProjectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// VTSI project name with which to perform the call of the form <pre><code>projects/&lt;project_uuid&gt;/project</code></pre>
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployVtsiProjectRequest) Reset() {
	*x = DeployVtsiProjectRequest{}
	mi := &file_ondewo_vtsi_projects_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployVtsiProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployVtsiProjectRequest) ProtoMessage() {}

func (x *DeployVtsiProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_vtsi_projects_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployVtsiProjectRequest.ProtoReflect.Descriptor instead.
func (*DeployVtsiProjectRequest) Descriptor() ([]byte, []int) {
	return file_ondewo_vtsi_projects_proto_rawDescGZIP(), []int{14}
}

func (x *DeployVtsiProjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Response to deploy a vtsi project
type DeployVtsiProjectResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// VTSI project name with which to perform the call of the form <pre><code>projects/&lt;project_uuid&gt;/project</code></pre>
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// error message if there are any.
	ErrorMessage  string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployVtsiProjectResponse) Reset() {
	*x = DeployVtsiProjectResponse{}
	mi := &file_ondewo_vtsi_projects_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployVtsiProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployVtsiProjectResponse) ProtoMessage() {}

func (x *DeployVtsiProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_vtsi_projects_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployVtsiProjectResponse.ProtoReflect.Descriptor instead.
func (*DeployVtsiProjectResponse) Descriptor() ([]byte, []int) {
	return file_ondewo_vtsi_projects_proto_rawDescGZIP(), []int{15}
}

func (x *DeployVtsiProjectResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeployVtsiProjectResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Request to undeploy a vtsi project
type UndeployVtsiProjectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Project name of the VTSI project.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UndeployVtsiProjectRequest) Reset() {
	*x = UndeployVtsiProjectRequest{}
	mi := &file_ondewo_vtsi_projects_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UndeployVtsiProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UndeployVtsiProjectRequest) ProtoMessage() {}

func (x *UndeployVtsiProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_vtsi_projects_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UndeployVtsiProjectRequest.ProtoReflect.Descriptor instead.
func (*UndeployVtsiProjectRequest) Descriptor() ([]byte, []int) {
	return file_ondewo_vtsi_projects_proto_rawDescGZIP(), []int{16}
}

func (x *UndeployVtsiProjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Response to undeploy a vtsi project
type UndeployVtsiProjectResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// VTSI project name with which to perform the call of the form <pre><code>projects/&lt;project_uuid&gt;/project</code></pre>
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// error message if there are any.
	ErrorMessage  string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UndeployVtsiProjectResponse) Reset() {
	*x = UndeployVtsiProjectResponse{}
	mi := &file_ondewo_vtsi_projects_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UndeployVtsiProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UndeployVtsiProjectResponse) ProtoMessage() {}

func (x *UndeployVtsiProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_vtsi_projects_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UndeployVtsiProjectResponse.ProtoReflect.Descriptor instead.
func (*UndeployVtsiProjectResponse) Descriptor() ([]byte, []int) {
	return file_ondewo_vtsi_projects_proto_rawDescGZIP(), []int{17}
}

func (x *UndeployVtsiProjectResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UndeployVtsiProjectResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_ondewo_vtsi_projects_proto protoreflect.FileDescriptor

const file_ondewo_vtsi_projects_proto_rawDesc = "" +
	"\n" +
	"\x1aondewo/vtsi/projects.proto\x12\vondewo.vtsi\x1a google/protobuf/field_mask.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd4\x05\n" +
	"\vVtsiProject\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x1f\n" +
	"\vmax_callers\x18\x03 \x01(\x05R\n" +
	"maxCallers\x12#\n" +
	"\rmax_listeners\x18\x04 \x01(\x05R\fmaxListeners\x12G\n" +
	"\x10asterisk_configs\x18\x05 \x01(\v2\x1c.ondewo.vtsi.AsteriskConfigsR\x0fasteriskConfigs\x12N\n" +
	"\x13vtsi_project_status\x18\x06 \x01(\x0e2\x1e.ondewo.vtsi.VtsiProjectStatusR\x11vtsiProjectStatus\x12\x1d\n" +
	"\n" +
	"created_by\x18\a \x01(\tR\tcreatedBy\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1f\n" +
	"\vmodified_by\x18\t \x01(\tR\n" +
	"modifiedBy\x12;\n" +
	"\vmodified_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"modifiedAt\x12%\n" +
	"\x0eactive_callers\x18\v \x01(\x05R\ractiveCallers\x12)\n" +
	"\x10active_listeners\x18\f \x01(\x05R\x0factiveListeners\x12#\n" +
	"\rasterisk_port\x18\r \x01(\x05R\fasteriskPort\x12&\n" +
	"\x0fnlu_agent_names\x18\x0e \x03(\tR\rnluAgentNames\x12)\n" +
	"\x10deployed_callers\x18\x0f \x01(\x05R\x0fdeployedCallers\x12-\n" +
	"\x12deployed_listeners\x18\x10 \x01(\x05R\x11deployedListeners\"\xac\x02\n" +
	"\x18AsteriskConfigsVariables\x12,\n" +
	"\x12sip_trunk_username\x18\x01 \x01(\tR\x10sipTrunkUsername\x12,\n" +
	"\x12sip_trunk_password\x18\x02 \x01(\tR\x10sipTrunkPassword\x12$\n" +
	"\x0esip_trunk_host\x18\x03 \x01(\tR\fsipTrunkHost\x12'\n" +
	"\x0ftransfer_number\x18\x04 \x01(\tR\x0etransferNumber\x120\n" +
	"\x14transfer_number_host\x18\x05 \x01(\tR\x12transferNumberHost\x123\n" +
	"\x16sip_trunk_phone_number\x18\x06 \x01(\tR\x13sipTrunkPhoneNumber\"\xf6\x01\n" +
	"\x14AsteriskConfigsFiles\x12/\n" +
	"\x14sip_conf_file_string\x18\x01 \x01(\tR\x11sipConfFileString\x12=\n" +
	"\x1bextensions_conf_file_string\x18\x02 \x01(\tR\x18extensionsConfFileString\x125\n" +
	"\x17queues_conf_file_string\x18\x03 \x01(\tR\x14queuesConfFileString\x127\n" +
	"\x18modules_conf_file_string\x18\x04 \x01(\tR\x15modulesConfFileString\"\xad\x03\n" +
	"\x0fAsteriskConfigs\x12e\n" +
	"\x1aasterisk_configs_variables\x18\x01 \x01(\v2%.ondewo.vtsi.AsteriskConfigsVariablesH\x00R\x18asteriskConfigsVariables\x12Y\n" +
	"\x16asterisk_configs_files\x18\x02 \x01(\v2!.ondewo.vtsi.AsteriskConfigsFilesH\x00R\x14asteriskConfigsFiles\x12T\n" +
	"&asterisk_configs_target_directory_name\x18\x03 \x01(\tH\x00R\"asteriskConfigsTargetDirectoryName\x12#\n" +
	"\rasterisk_port\x18\x04 \x01(\x05R\fasteriskPort\x12.\n" +
	"\x10asterisk_version\x18\x05 \x01(\tH\x01R\x0fasteriskVersion\x88\x01\x01B\x18\n" +
	"\x16asterisk_configs_oneofB\x13\n" +
	"\x11_asterisk_version\"|\n" +
	"\x18CreateVtsiProjectRequest\x12;\n" +
	"\fvtsi_project\x18\x01 \x01(\v2\x18.ondewo.vtsi.VtsiProjectR\vvtsiProject\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"}\n" +
	"\x19CreateVtsiProjectResponse\x12;\n" +
	"\fvtsi_project\x18\x01 \x01(\v2\x18.ondewo.vtsi.VtsiProjectR\vvtsiProject\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"u\n" +
	"\x15GetVtsiProjectRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12H\n" +
	"\x11vtsi_project_view\x18\x02 \x01(\x0e2\x1c.ondewo.vtsi.VtsiProjectViewR\x0fvtsiProjectView\"\xaf\x02\n" +
	"\x17ListVtsiProjectsRequest\x12H\n" +
	"\x11vtsi_project_view\x18\x01 \x01(\x0e2\x1c.ondewo.vtsi.VtsiProjectViewR\x0fvtsiProjectView\x12\"\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tH\x00R\tpageToken\x88\x01\x01\x12V\n" +
	"\x14vtsi_project_sorting\x18\x03 \x01(\v2\x1f.ondewo.vtsi.VtsiProjectSortingH\x01R\x12vtsiProjectSorting\x88\x01\x01\x12&\n" +
	"\x0fnlu_agent_names\x18\x04 \x03(\tR\rnluAgentNamesB\r\n" +
	"\v_page_tokenB\x17\n" +
	"\x15_vtsi_project_sorting\"\x81\x01\n" +
	"\x18ListVtsiProjectsResponse\x12=\n" +
	"\rvtsi_projects\x18\x01 \x03(\v2\x18.ondewo.vtsi.VtsiProjectR\fvtsiProjects\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xb6\x03\n" +
	"\x12VtsiProjectSorting\x12a\n" +
	"\rsorting_field\x18\x01 \x01(\x0e27.ondewo.vtsi.VtsiProjectSorting.VtsiProjectSortingFieldH\x00R\fsortingField\x88\x01\x01\x12K\n" +
	"\fsorting_mode\x18\x02 \x01(\x0e2#.ondewo.vtsi.VtsiProjectSortingModeH\x01R\vsortingMode\x88\x01\x01\"\xcc\x01\n" +
	"\x17VtsiProjectSortingField\x12\x1b\n" +
	"\x17NO_VTSI_PROJECT_SORTING\x10\x00\x12\x1d\n" +
	"\x19SORT_VTSI_PROJECT_BY_NAME\x10\x01\x12%\n" +
	"!SORT_VTSI_PROJECT_BY_DISPLAY_NAME\x10\x02\x12&\n" +
	"\"SORT_VTSI_PROJECT_BY_CREATION_DATE\x10\x03\x12&\n" +
	"\"SORT_VTSI_PROJECT_BY_LAST_MODIFIED\x10\x04B\x10\n" +
	"\x0e_sorting_fieldB\x0f\n" +
	"\r_sorting_mode\"\x94\x01\n" +
	"\x18UpdateVtsiProjectRequest\x12;\n" +
	"\fvtsi_project\x18\x01 \x01(\v2\x18.ondewo.vtsi.VtsiProjectR\vvtsiProject\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"T\n" +
	"\x19UpdateVtsiProjectResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\".\n" +
	"\x18DeleteVtsiProjectRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"T\n" +
	"\x19DeleteVtsiProjectResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\".\n" +
	"\x18DeployVtsiProjectRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"T\n" +
	"\x19DeployVtsiProjectResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"0\n" +
	"\x1aUndeployVtsiProjectRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"V\n" +
	"\x1bUndeployVtsiProjectResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage*\x8b\x01\n" +
	"\x11VtsiProjectStatus\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"UNDEPLOYED\x10\x01\x12\f\n" +
	"\bUPDATING\x10\x02\x12\r\n" +
	"\tDEPLOYING\x10\x03\x12\f\n" +
	"\bDEPLOYED\x10\x04\x12\x0f\n" +
	"\vUNDEPLOYING\x10\x05\x12\f\n" +
	"\bDELETING\x10\x06\x12\v\n" +
	"\aDELETED\x10\a*7\n" +
	"\x16VtsiProjectSortingMode\x12\r\n" +
	"\tASCENDING\x10\x00\x12\x0e\n" +
	"\n" +
	"DESCENDING\x10\x01*\x8e\x01\n" +
	"\x0fVtsiProjectView\x12!\n" +
	"\x1dVTSI_PROJECT_VIEW_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16VTSI_PROJECT_VIEW_FULL\x10\x01\x12\x1d\n" +
	"\x19VTSI_PROJECT_VIEW_SHALLOW\x10\x02\x12\x1d\n" +
	"\x19VTSI_PROJECT_VIEW_MINIMUM\x10\x032\xb5\x05\n" +
	"\bProjects\x12b\n" +
	"\x11CreateVtsiProject\x12%.ondewo.vtsi.CreateVtsiProjectRequest\x1a&.ondewo.vtsi.CreateVtsiProjectResponse\x12N\n" +
	"\x0eGetVtsiProject\x12\".ondewo.vtsi.GetVtsiProjectRequest\x1a\x18.ondewo.vtsi.VtsiProject\x12b\n" +
	"\x11UpdateVtsiProject\x12%.ondewo.vtsi.UpdateVtsiProjectRequest\x1a&.ondewo.vtsi.UpdateVtsiProjectResponse\x12b\n" +
	"\x11DeleteVtsiProject\x12%.ondewo.vtsi.DeleteVtsiProjectRequest\x1a&.ondewo.vtsi.DeleteVtsiProjectResponse\x12b\n" +
	"\x11DeployVtsiProject\x12%.ondewo.vtsi.DeployVtsiProjectRequest\x1a&.ondewo.vtsi.DeployVtsiProjectResponse\x12h\n" +
	"\x13UndeployVtsiProject\x12'.ondewo.vtsi.UndeployVtsiProjectRequest\x1a(.ondewo.vtsi.UndeployVtsiProjectResponse\x12_\n" +
	"\x10ListVtsiProjects\x12$.ondewo.vtsi.ListVtsiProjectsRequest\x1a%.ondewo.vtsi.ListVtsiProjectsResponseb\x06proto3"

var (
	file_ondewo_vtsi_projects_proto_rawDescOnce sync.Once
	file_ondewo_vtsi_projects_proto_rawDescData []byte
)

func file_ondewo_vtsi_projects_proto_rawDescGZIP() []byte {
	file_ondewo_vtsi_projects_proto_rawDescOnce.Do(func() {
		file_ondewo_vtsi_projects_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ondewo_vtsi_projects_proto_rawDesc), len(file_ondewo_vtsi_projects_proto_rawDesc)))
	})
	return file_ondewo_vtsi_projects_proto_rawDescData
}

var file_ondewo_vtsi_projects_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_ondewo_vtsi_projects_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_ondewo_vtsi_projects_proto_goTypes = []any{
	(VtsiProjectStatus)(0),                          // 0: ondewo.vtsi.VtsiProjectStatus
	(VtsiProjectSortingMode)(0),                     // 1: ondewo.vtsi.VtsiProjectSortingMode
	(VtsiProjectView)(0),                            // 2: ondewo.vtsi.VtsiProjectView
	(VtsiProjectSorting_VtsiProjectSortingField)(0), // 3: ondewo.vtsi.VtsiProjectSorting.VtsiProjectSortingField
	(*VtsiProject)(nil),                             // 4: ondewo.vtsi.VtsiProject
	(*AsteriskConfigsVariables)(nil),                // 5: ondewo.vtsi.AsteriskConfigsVariables
	(*AsteriskConfigsFiles)(nil),                    // 6: ondewo.vtsi.AsteriskConfigsFiles
	(*AsteriskConfigs)(nil),                         // 7: ondewo.vtsi.AsteriskConfigs
	(*CreateVtsiProjectRequest)(nil),                // 8: ondewo.vtsi.CreateVtsiProjectRequest
	(*CreateVtsiProjectResponse)(nil),               // 9: ondewo.vtsi.CreateVtsiProjectResponse
	(*GetVtsiProjectRequest)(nil),                   // 10: ondewo.vtsi.GetVtsiProjectRequest
	(*ListVtsiProjectsRequest)(nil),                 // 11: ondewo.vtsi.ListVtsiProjectsRequest
	(*ListVtsiProjectsResponse)(nil),                // 12: ondewo.vtsi.ListVtsiProjectsResponse
	(*VtsiProjectSorting)(nil),                      // 13: ondewo.vtsi.VtsiProjectSorting
	(*UpdateVtsiProjectRequest)(nil),                // 14: ondewo.vtsi.UpdateVtsiProjectRequest
	(*UpdateVtsiProjectResponse)(nil),               // 15: ondewo.vtsi.UpdateVtsiProjectResponse
	(*DeleteVtsiProjectRequest)(nil),                // 16: ondewo.vtsi.DeleteVtsiProjectRequest
	(*DeleteVtsiProjectResponse)(nil),               // 17: ondewo.vtsi.DeleteVtsiProjectResponse
	(*DeployVtsiProjectRequest)(nil),                // 18: ondewo.vtsi.DeployVtsiProjectRequest
	(*DeployVtsiProjectResponse)(nil),               // 19: ondewo.vtsi.DeployVtsiProjectResponse
	(*UndeployVtsiProjectRequest)(nil),              // 20: ondewo.vtsi.UndeployVtsiProjectRequest
	(*UndeployVtsiProjectResponse)(nil),             // 21: ondewo.vtsi.UndeployVtsiProjectResponse
	(*timestamppb.Timestamp)(nil),                   // 22: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil),                   // 23: google.protobuf.FieldMask
}
var file_ondewo_vtsi_projects_proto_depIdxs = []int32{
	7,  // 0: ondewo.vtsi.VtsiProject.asterisk_configs:type_name -> ondewo.vtsi.AsteriskConfigs
	0,  // 1: ondewo.vtsi.VtsiProject.vtsi_project_status:type_name -> ondewo.vtsi.VtsiProjectStatus
	22, // 2: ondewo.vtsi.VtsiProject.created_at:type_name -> google.protobuf.Timestamp
	22, // 3: ondewo.vtsi.VtsiProject.modified_at:type_name -> google.protobuf.Timestamp
	5,  // 4: ondewo.vtsi.AsteriskConfigs.asterisk_configs_variables:type_name -> ondewo.vtsi.AsteriskConfigsVariables
	6,  // 5: ondewo.vtsi.AsteriskConfigs.asterisk_configs_files:type_name -> ondewo.vtsi.AsteriskConfigsFiles
	4,  // 6: ondewo.vtsi.CreateVtsiProjectRequest.vtsi_project:type_name -> ondewo.vtsi.VtsiProject
	4,  // 7: ondewo.vtsi.CreateVtsiProjectResponse.vtsi_project:type_name -> ondewo.vtsi.VtsiProject
	2,  // 8: ondewo.vtsi.GetVtsiProjectRequest.vtsi_project_view:type_name -> ondewo.vtsi.VtsiProjectView
	2,  // 9: ondewo.vtsi.ListVtsiProjectsRequest.vtsi_project_view:type_name -> ondewo.vtsi.VtsiProjectView
	13, // 10: ondewo.vtsi.ListVtsiProjectsRequest.vtsi_project_sorting:type_name -> ondewo.vtsi.VtsiProjectSorting
	4,  // 11: ondewo.vtsi.ListVtsiProjectsResponse.vtsi_projects:type_name -> ondewo.vtsi.VtsiProject
	3,  // 12: ondewo.vtsi.VtsiProjectSorting.sorting_field:type_name -> ondewo.vtsi.VtsiProjectSorting.VtsiProjectSortingField
	1,  // 13: ondewo.vtsi.VtsiProjectSorting.sorting_mode:type_name -> ondewo.vtsi.VtsiProjectSortingMode
	4,  // 14: ondewo.vtsi.UpdateVtsiProjectRequest.vtsi_project:type_name -> ondewo.vtsi.VtsiProject
	23, // 15: ondewo.vtsi.UpdateVtsiProjectRequest.update_mask:type_name -> google.protobuf.FieldMask
	8,  // 16: ondewo.vtsi.Projects.CreateVtsiProject:input_type -> ondewo.vtsi.CreateVtsiProjectRequest
	10, // 17: ondewo.vtsi.Projects.GetVtsiProject:input_type -> ondewo.vtsi.GetVtsiProjectRequest
	14, // 18: ondewo.vtsi.Projects.UpdateVtsiProject:input_type -> ondewo.vtsi.UpdateVtsiProjectRequest
	16, // 19: ondewo.vtsi.Projects.DeleteVtsiProject:input_type -> ondewo.vtsi.DeleteVtsiProjectRequest
	18, // 20: ondewo.vtsi.Projects.DeployVtsiProject:input_type -> ondewo.vtsi.DeployVtsiProjectRequest
	20, // 21: ondewo.vtsi.Projects.UndeployVtsiProject:input_type -> ondewo.vtsi.UndeployVtsiProjectRequest
	11, // 22: ondewo.vtsi.Projects.ListVtsiProjects:input_type -> ondewo.vtsi.ListVtsiProjectsRequest
	9,  // 23: ondewo.vtsi.Projects.CreateVtsiProject:output_type -> ondewo.vtsi.CreateVtsiProjectResponse
	4,  // 24: ondewo.vtsi.Projects.GetVtsiProject:output_type -> ondewo.vtsi.VtsiProject
	15, // 25: ondewo.vtsi.Projects.UpdateVtsiProject:output_type -> ondewo.vtsi.UpdateVtsiProjectResponse
	17, // 26: ondewo.vtsi.Projects.DeleteVtsiProject:output_type -> ondewo.vtsi.DeleteVtsiProjectResponse
	19, // 27: ondewo.vtsi.Projects.DeployVtsiProject:output_type -> ondewo.vtsi.DeployVtsiProjectResponse
	21, // 28: ondewo.vtsi.Projects.UndeployVtsiProject:output_type -> ondewo.vtsi.UndeployVtsiProjectResponse
	12, // 29: ondewo.vtsi.Projects.ListVtsiProjects:output_type -> ondewo.vtsi.ListVtsiProjectsResponse
	23, // [23:30] is the sub-list for method output_type
	16, // [16:23] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_ondewo_vtsi_projects_proto_init() }
func file_ondewo_vtsi_projects_proto_init() {
	if File_ondewo_vtsi_projects_proto != nil {
		return
	}
	file_ondewo_vtsi_projects_proto_msgTypes[3].OneofWrappers = []any{
		(*AsteriskConfigs_AsteriskConfigsVariables)(nil),
		(*AsteriskConfigs_AsteriskConfigsFiles)(nil),
		(*AsteriskConfigs_AsteriskConfigsTargetDirectoryName)(nil),
	}
	file_ondewo_vtsi_projects_proto_msgTypes[7].OneofWrappers = []any{}
	file_ondewo_vtsi_projects_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ondewo_vtsi_projects_proto_rawDesc), len(file_ondewo_vtsi_projects_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ondewo_vtsi_projects_proto_goTypes,
		DependencyIndexes: file_ondewo_vtsi_projects_proto_depIdxs,
		EnumInfos:         file_ondewo_vtsi_projects_proto_enumTypes,
		MessageInfos:      file_ondewo_vtsi_projects_proto_msgTypes,
	}.Build()
	File_ondewo_vtsi_projects_proto = out.File
	file_ondewo_vtsi_projects_proto_goTypes = nil
	file_ondewo_vtsi_projects_proto_depIdxs = nil
}
