// Copyright 2021 ONDEWO GmbH
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.32.0
// source: ondewo/vtsi/softphones.proto

package vtsi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Softphones_CreateSoftphoneAccount_FullMethodName     = "/ondewo.vtsi.Softphones/CreateSoftphoneAccount"
	Softphones_GetSoftphoneAccount_FullMethodName        = "/ondewo.vtsi.Softphones/GetSoftphoneAccount"
	Softphones_UpdateSoftphoneAccount_FullMethodName     = "/ondewo.vtsi.Softphones/UpdateSoftphoneAccount"
	Softphones_DeleteSoftphoneAccount_FullMethodName     = "/ondewo.vtsi.Softphones/DeleteSoftphoneAccount"
	Softphones_ListSoftphoneAccounts_FullMethodName      = "/ondewo.vtsi.Softphones/ListSoftphoneAccounts"
	Softphones_RotateSoftphoneCredentials_FullMethodName = "/ondewo.vtsi.Softphones/RotateSoftphoneCredentials"
	Softphones_ListSoftphoneCertificates_FullMethodName  = "/ondewo.vtsi.Softphones/ListSoftphoneCertificates"
	Softphones_GetSoftphoneCertificate_FullMethodName    = "/ondewo.vtsi.Softphones/GetSoftphoneCertificate"
	Softphones_RevokeSoftphoneCertificate_FullMethodName = "/ondewo.vtsi.Softphones/RevokeSoftphoneCertificate"
	Softphones_GetSoftphoneProvisioning_FullMethodName   = "/ondewo.vtsi.Softphones/GetSoftphoneProvisioning"
)

// SoftphonesClient is the client API for Softphones service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// <p>ONDEWO VTSI API</p>
// <p>Manages the SOFTPHONE ACCOUNTS of a VTSI project: SIP accounts on the project&apos;s Asterisk that
// a human uses from a softphone such as Zoiper, to call into the project&apos;s listeners or to be reached
// by the project.</p>
// <p>A softphone account is NEVER one of the <code>ondewo000N</code> accounts the per-call ondewo-sip
// containers register with: it has its own SIP credentials, its own endpoint on the Asterisk and, for
// <code>SOFTPHONE_TRANSPORT_SECURITY_CLIENT_CERTIFICATE</code>, its own client certificate issued by the
// project&apos;s SOFTPHONE certificate authority.</p>
// <p><b>Secrets are handed out exactly once.</b> The SIP password and the password-protected PKCS#12
// bundle carrying the client private key appear only in the responses of
// <code>CreateSoftphoneAccount</code> and <code>RotateSoftphoneCredentials</code>. VTSI keeps no copy of
// the private key or of the PKCS#12 password, and stores the SIP password only in the form the Asterisk
// needs to verify a SIP digest. No other RPC returns a secret; a lost private key or password is
// recovered by rotating it.</p>
// <p>Errors are reported as gRPC status codes, not as <code>error_message</code> fields:
// <code>INVALID_ARGUMENT</code> for a malformed name, filter, field mask or value;
// <code>NOT_FOUND</code> for an unknown project, account or certificate;
// <code>ALREADY_EXISTS</code> for a <code>sip_username</code> already taken in the project;
// <code>FAILED_PRECONDITION</code> when the project or the account is in a state that does not allow the
// operation (each RPC names its cases); <code>ABORTED</code> when a concurrent change to the same account
// won, in which case nothing was stored and the request can be retried.</p>
// <p><b>A change that reduces access is enforced before it is acknowledged.</b> When
// <code>UpdateSoftphoneAccount</code>, <code>DeleteSoftphoneAccount</code> or
// <code>RevokeSoftphoneCertificate</code> is stored but the running Asterisk of a deployed project could
// not be updated, the RPC fails with <code>FAILED_PRECONDITION</code>; the stored change is applied by
// the next successful change or deployment. <code>CreateSoftphoneAccount</code> and
// <code>RotateSoftphoneCredentials</code> return their one-time secrets even then.</p>
type SoftphonesClient interface {
	// <p>Creates a softphone account in a VTSI project, generates its SIP password and, for
	// <code>SOFTPHONE_TRANSPORT_SECURITY_CLIENT_CERTIFICATE</code>, issues its first client certificate.
	// The response carries the ONE-TIME secrets; they cannot be retrieved again.</p>
	// <p>If the project is deployed the account is applied to the running Asterisk; otherwise it is
	// applied on the next deployment.</p>
	// <p>Errors: <code>NOT_FOUND</code> if the project does not exist; <code>ALREADY_EXISTS</code> if the
	// <code>sip_username</code> is taken in the project; <code>INVALID_ARGUMENT</code> for an invalid or
	// reserved <code>sip_username</code>, an output-only field that was set, or an out-of-range value;
	// <code>FAILED_PRECONDITION</code> if the project is being deleted, or, for
	// <code>SOFTPHONE_TRANSPORT_SECURITY_CLIENT_CERTIFICATE</code>, if the project has no Asterisk port yet
	// or its SOFTPHONE certificate authority is unusable (a redeployment mints a new one).</p>
	// <p>The account is reachable on either TLS port only from the project&apos;s
	// <code>softphone_permit_cidrs</code> (default: the server&apos;s list, private networks unless the
	// operator changed it); see <code>AsteriskConfigsVariables.softphone_permit_cidrs</code>.</p>
	CreateSoftphoneAccount(ctx context.Context, in *CreateSoftphoneAccountRequest, opts ...grpc.CallOption) (*CreateSoftphoneAccountResponse, error)
	// <p>Returns a softphone account. Never returns a secret.</p>
	// <p>Errors: <code>NOT_FOUND</code> if the account does not exist; <code>INVALID_ARGUMENT</code> for a
	// malformed name or an unknown <code>field_mask</code> path.</p>
	GetSoftphoneAccount(ctx context.Context, in *GetSoftphoneAccountRequest, opts ...grpc.CallOption) (*SoftphoneAccount, error)
	// <p>Updates the mutable fields of a softphone account named by <code>update_mask</code>. Credentials
	// are not changed here; use <code>RotateSoftphoneCredentials</code>.</p>
	// <p>Errors: <code>NOT_FOUND</code> if the account does not exist; <code>INVALID_ARGUMENT</code> for an
	// empty mask, an unknown, output-only or immutable path, or an out-of-range value;
	// <code>FAILED_PRECONDITION</code> when switching to
	// <code>SOFTPHONE_TRANSPORT_SECURITY_CLIENT_CERTIFICATE</code> while the account has no
	// <code>SOFTPHONE_CERTIFICATE_STATUS_ACTIVE</code> certificate, or if the project is being deleted.</p>
	// <p>The account is reachable on either TLS port only from the project&apos;s
	// <code>softphone_permit_cidrs</code> (default: the server&apos;s list, private networks unless the
	// operator changed it); see <code>AsteriskConfigsVariables.softphone_permit_cidrs</code>.</p>
	UpdateSoftphoneAccount(ctx context.Context, in *UpdateSoftphoneAccountRequest, opts ...grpc.CallOption) (*SoftphoneAccount, error)
	// <p>Deletes a softphone account. Its endpoint is removed from the Asterisk, its registrations are
	// dropped and every certificate it holds is revoked. Deletion is permanent.</p>
	// <p>Errors: <code>NOT_FOUND</code> if the account does not exist.</p>
	DeleteSoftphoneAccount(ctx context.Context, in *DeleteSoftphoneAccountRequest, opts ...grpc.CallOption) (*DeleteSoftphoneAccountResponse, error)
	// <p>Lists the softphone accounts of a VTSI project, filtered, sorted and paged. Never returns a
	// secret.</p>
	// <p>Errors: <code>NOT_FOUND</code> if the project does not exist; <code>INVALID_ARGUMENT</code> for an
	// invalid filter, an unknown <code>field_mask</code> path, a negative <code>page_size</code> or a
	// <code>page_token</code> that was not issued for the same project, filter and sorting.</p>
	ListSoftphoneAccounts(ctx context.Context, in *ListSoftphoneAccountsRequest, opts ...grpc.CallOption) (*ListSoftphoneAccountsResponse, error)
	// <p>Rotates the SIP password and/or the client certificate of a softphone account and returns the new
	// ONE-TIME secrets. <b>Every rotation rotates the SIP password</b>, including one that asked only for
	// <code>rotate_certificate</code>: the Asterisk has no certificate revocation list, so a previous
	// certificate stops being usable for this account only because the password it was issued with
	// stops working. The new password takes effect immediately and drops the account&apos;s current
	// registrations, so every softphone using it must be reconfigured. A rotated certificate moves the
	// previous <code>SOFTPHONE_CERTIFICATE_STATUS_ACTIVE</code> certificate to
	// <code>SOFTPHONE_CERTIFICATE_STATUS_SUPERSEDED</code>. A rotation also unlocks an account that
	// <code>RevokeSoftphoneCertificate</code> locked (a <code>SOFTPHONE_TRANSPORT_SECURITY_CLIENT_CERTIFICATE</code>
	// account only once it again holds an ACTIVE certificate).</p>
	// <p>Rotating the certificate of a <code>SOFTPHONE_TRANSPORT_SECURITY_SERVER_TLS_ONLY</code> account is
	// allowed: it issues the certificate that a later switch to
	// <code>SOFTPHONE_TRANSPORT_SECURITY_CLIENT_CERTIFICATE</code> requires, and rotates the password too.</p>
	// <p>Errors: <code>NOT_FOUND</code> if the account does not exist; <code>INVALID_ARGUMENT</code> if
	// neither <code>rotate_sip_password</code> nor <code>rotate_certificate</code> is set;
	// <code>FAILED_PRECONDITION</code> if the project is being deleted, or, for
	// <code>rotate_certificate</code>, if the project has no Asterisk port yet or its SOFTPHONE
	// certificate authority is unusable.</p>
	RotateSoftphoneCredentials(ctx context.Context, in *RotateSoftphoneCredentialsRequest, opts ...grpc.CallOption) (*RotateSoftphoneCredentialsResponse, error)
	// <p>Lists softphone client certificates, either of one softphone account or of a whole VTSI project,
	// filtered and paged, newest first. Only public material is returned.</p>
	// <p>Errors: <code>NOT_FOUND</code> if the project or account does not exist;
	// <code>INVALID_ARGUMENT</code> if no scope is set, for an invalid filter, an unknown
	// <code>field_mask</code> path, a negative <code>page_size</code> or a foreign
	// <code>page_token</code>.</p>
	ListSoftphoneCertificates(ctx context.Context, in *ListSoftphoneCertificatesRequest, opts ...grpc.CallOption) (*ListSoftphoneCertificatesResponse, error)
	// <p>Returns one softphone client certificate. Only public material is returned.</p>
	// <p>Errors: <code>NOT_FOUND</code> if the certificate does not exist; <code>INVALID_ARGUMENT</code> for
	// a malformed name or an unknown <code>field_mask</code> path.</p>
	GetSoftphoneCertificate(ctx context.Context, in *GetSoftphoneCertificateRequest, opts ...grpc.CallOption) (*SoftphoneCertificate, error)
	// <p>Revokes a softphone client certificate. The Asterisk has no certificate revocation list, so
	// revocation is enforced on the account&apos;s SIP password rather than on the certificate: a revoked
	// certificate still completes the TLS handshake on the project&apos;s mutual-TLS port, but it no longer
	// gets its holder an account.</p>
	// <p>Revoking the ACTIVE certificate of an account LOCKS the account, whatever its transport
	// security: it is removed from the Asterisk and its registrations are dropped until
	// <code>RotateSoftphoneCredentials</code> issues a new password (and, for
	// <code>SOFTPHONE_TRANSPORT_SECURITY_CLIENT_CERTIFICATE</code>, a new certificate). Revoking a
	// SUPERSEDED certificate records the revocation only; its password was already rotated away.
	// Revoking an already revoked certificate is idempotent and keeps the original revocation time and
	// reason.</p>
	// <p>Errors: <code>NOT_FOUND</code> if the certificate does not exist; <code>INVALID_ARGUMENT</code>
	// for a malformed name or an over-long reason.</p>
	RevokeSoftphoneCertificate(ctx context.Context, in *RevokeSoftphoneCertificateRequest, opts ...grpc.CallOption) (*SoftphoneCertificate, error)
	// <p>Returns everything needed to configure a softphone for an account: server, port, transport,
	// outbound proxy, SIP identity, SRTP mode, codecs, the certificate authority to trust, which client
	// certificate to import, and step-by-step Zoiper instructions. It never contains the SIP password or
	// the private key; those were returned once by <code>CreateSoftphoneAccount</code> or
	// <code>RotateSoftphoneCredentials</code>.</p>
	// <p>Errors: <code>NOT_FOUND</code> if the account does not exist; <code>FAILED_PRECONDITION</code> if
	// the project is not <code>DEPLOYED</code> (the host and ports describe a running Asterisk), or if a
	// <code>SOFTPHONE_TRANSPORT_SECURITY_CLIENT_CERTIFICATE</code> account has no
	// <code>SOFTPHONE_CERTIFICATE_STATUS_ACTIVE</code> certificate.</p>
	GetSoftphoneProvisioning(ctx context.Context, in *GetSoftphoneProvisioningRequest, opts ...grpc.CallOption) (*SoftphoneProvisioning, error)
}

type softphonesClient struct {
	cc grpc.ClientConnInterface
}

func NewSoftphonesClient(cc grpc.ClientConnInterface) SoftphonesClient {
	return &softphonesClient{cc}
}

func (c *softphonesClient) CreateSoftphoneAccount(ctx context.Context, in *CreateSoftphoneAccountRequest, opts ...grpc.CallOption) (*CreateSoftphoneAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSoftphoneAccountResponse)
	err := c.cc.Invoke(ctx, Softphones_CreateSoftphoneAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *softphonesClient) GetSoftphoneAccount(ctx context.Context, in *GetSoftphoneAccountRequest, opts ...grpc.CallOption) (*SoftphoneAccount, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SoftphoneAccount)
	err := c.cc.Invoke(ctx, Softphones_GetSoftphoneAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *softphonesClient) UpdateSoftphoneAccount(ctx context.Context, in *UpdateSoftphoneAccountRequest, opts ...grpc.CallOption) (*SoftphoneAccount, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SoftphoneAccount)
	err := c.cc.Invoke(ctx, Softphones_UpdateSoftphoneAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *softphonesClient) DeleteSoftphoneAccount(ctx context.Context, in *DeleteSoftphoneAccountRequest, opts ...grpc.CallOption) (*DeleteSoftphoneAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSoftphoneAccountResponse)
	err := c.cc.Invoke(ctx, Softphones_DeleteSoftphoneAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *softphonesClient) ListSoftphoneAccounts(ctx context.Context, in *ListSoftphoneAccountsRequest, opts ...grpc.CallOption) (*ListSoftphoneAccountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSoftphoneAccountsResponse)
	err := c.cc.Invoke(ctx, Softphones_ListSoftphoneAccounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *softphonesClient) RotateSoftphoneCredentials(ctx context.Context, in *RotateSoftphoneCredentialsRequest, opts ...grpc.CallOption) (*RotateSoftphoneCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RotateSoftphoneCredentialsResponse)
	err := c.cc.Invoke(ctx, Softphones_RotateSoftphoneCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *softphonesClient) ListSoftphoneCertificates(ctx context.Context, in *ListSoftphoneCertificatesRequest, opts ...grpc.CallOption) (*ListSoftphoneCertificatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSoftphoneCertificatesResponse)
	err := c.cc.Invoke(ctx, Softphones_ListSoftphoneCertificates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *softphonesClient) GetSoftphoneCertificate(ctx context.Context, in *GetSoftphoneCertificateRequest, opts ...grpc.CallOption) (*SoftphoneCertificate, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SoftphoneCertificate)
	err := c.cc.Invoke(ctx, Softphones_GetSoftphoneCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *softphonesClient) RevokeSoftphoneCertificate(ctx context.Context, in *RevokeSoftphoneCertificateRequest, opts ...grpc.CallOption) (*SoftphoneCertificate, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SoftphoneCertificate)
	err := c.cc.Invoke(ctx, Softphones_RevokeSoftphoneCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *softphonesClient) GetSoftphoneProvisioning(ctx context.Context, in *GetSoftphoneProvisioningRequest, opts ...grpc.CallOption) (*SoftphoneProvisioning, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SoftphoneProvisioning)
	err := c.cc.Invoke(ctx, Softphones_GetSoftphoneProvisioning_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SoftphonesServer is the server API for Softphones service.
// All implementations must embed UnimplementedSoftphonesServer
// for forward compatibility.
//
// <p>ONDEWO VTSI API</p>
// <p>Manages the SOFTPHONE ACCOUNTS of a VTSI project: SIP accounts on the project&apos;s Asterisk that
// a human uses from a softphone such as Zoiper, to call into the project&apos;s listeners or to be reached
// by the project.</p>
// <p>A softphone account is NEVER one of the <code>ondewo000N</code> accounts the per-call ondewo-sip
// containers register with: it has its own SIP credentials, its own endpoint on the Asterisk and, for
// <code>SOFTPHONE_TRANSPORT_SECURITY_CLIENT_CERTIFICATE</code>, its own client certificate issued by the
// project&apos;s SOFTPHONE certificate authority.</p>
// <p><b>Secrets are handed out exactly once.</b> The SIP password and the password-protected PKCS#12
// bundle carrying the client private key appear only in the responses of
// <code>CreateSoftphoneAccount</code> and <code>RotateSoftphoneCredentials</code>. VTSI keeps no copy of
// the private key or of the PKCS#12 password, and stores the SIP password only in the form the Asterisk
// needs to verify a SIP digest. No other RPC returns a secret; a lost private key or password is
// recovered by rotating it.</p>
// <p>Errors are reported as gRPC status codes, not as <code>error_message</code> fields:
// <code>INVALID_ARGUMENT</code> for a malformed name, filter, field mask or value;
// <code>NOT_FOUND</code> for an unknown project, account or certificate;
// <code>ALREADY_EXISTS</code> for a <code>sip_username</code> already taken in the project;
// <code>FAILED_PRECONDITION</code> when the project or the account is in a state that does not allow the
// operation (each RPC names its cases); <code>ABORTED</code> when a concurrent change to the same account
// won, in which case nothing was stored and the request can be retried.</p>
// <p><b>A change that reduces access is enforced before it is acknowledged.</b> When
// <code>UpdateSoftphoneAccount</code>, <code>DeleteSoftphoneAccount</code> or
// <code>RevokeSoftphoneCertificate</code> is stored but the running Asterisk of a deployed project could
// not be updated, the RPC fails with <code>FAILED_PRECONDITION</code>; the stored change is applied by
// the next successful change or deployment. <code>CreateSoftphoneAccount</code> and
// <code>RotateSoftphoneCredentials</code> return their one-time secrets even then.</p>
type SoftphonesServer interface {
	// <p>Creates a softphone account in a VTSI project, generates its SIP password and, for
	// <code>SOFTPHONE_TRANSPORT_SECURITY_CLIENT_CERTIFICATE</code>, issues its first client certificate.
	// The response carries the ONE-TIME secrets; they cannot be retrieved again.</p>
	// <p>If the project is deployed the account is applied to the running Asterisk; otherwise it is
	// applied on the next deployment.</p>
	// <p>Errors: <code>NOT_FOUND</code> if the project does not exist; <code>ALREADY_EXISTS</code> if the
	// <code>sip_username</code> is taken in the project; <code>INVALID_ARGUMENT</code> for an invalid or
	// reserved <code>sip_username</code>, an output-only field that was set, or an out-of-range value;
	// <code>FAILED_PRECONDITION</code> if the project is being deleted, or, for
	// <code>SOFTPHONE_TRANSPORT_SECURITY_CLIENT_CERTIFICATE</code>, if the project has no Asterisk port yet
	// or its SOFTPHONE certificate authority is unusable (a redeployment mints a new one).</p>
	// <p>The account is reachable on either TLS port only from the project&apos;s
	// <code>softphone_permit_cidrs</code> (default: the server&apos;s list, private networks unless the
	// operator changed it); see <code>AsteriskConfigsVariables.softphone_permit_cidrs</code>.</p>
	CreateSoftphoneAccount(context.Context, *CreateSoftphoneAccountRequest) (*CreateSoftphoneAccountResponse, error)
	// <p>Returns a softphone account. Never returns a secret.</p>
	// <p>Errors: <code>NOT_FOUND</code> if the account does not exist; <code>INVALID_ARGUMENT</code> for a
	// malformed name or an unknown <code>field_mask</code> path.</p>
	GetSoftphoneAccount(context.Context, *GetSoftphoneAccountRequest) (*SoftphoneAccount, error)
	// <p>Updates the mutable fields of a softphone account named by <code>update_mask</code>. Credentials
	// are not changed here; use <code>RotateSoftphoneCredentials</code>.</p>
	// <p>Errors: <code>NOT_FOUND</code> if the account does not exist; <code>INVALID_ARGUMENT</code> for an
	// empty mask, an unknown, output-only or immutable path, or an out-of-range value;
	// <code>FAILED_PRECONDITION</code> when switching to
	// <code>SOFTPHONE_TRANSPORT_SECURITY_CLIENT_CERTIFICATE</code> while the account has no
	// <code>SOFTPHONE_CERTIFICATE_STATUS_ACTIVE</code> certificate, or if the project is being deleted.</p>
	// <p>The account is reachable on either TLS port only from the project&apos;s
	// <code>softphone_permit_cidrs</code> (default: the server&apos;s list, private networks unless the
	// operator changed it); see <code>AsteriskConfigsVariables.softphone_permit_cidrs</code>.</p>
	UpdateSoftphoneAccount(context.Context, *UpdateSoftphoneAccountRequest) (*SoftphoneAccount, error)
	// <p>Deletes a softphone account. Its endpoint is removed from the Asterisk, its registrations are
	// dropped and every certificate it holds is revoked. Deletion is permanent.</p>
	// <p>Errors: <code>NOT_FOUND</code> if the account does not exist.</p>
	DeleteSoftphoneAccount(context.Context, *DeleteSoftphoneAccountRequest) (*DeleteSoftphoneAccountResponse, error)
	// <p>Lists the softphone accounts of a VTSI project, filtered, sorted and paged. Never returns a
	// secret.</p>
	// <p>Errors: <code>NOT_FOUND</code> if the project does not exist; <code>INVALID_ARGUMENT</code> for an
	// invalid filter, an unknown <code>field_mask</code> path, a negative <code>page_size</code> or a
	// <code>page_token</code> that was not issued for the same project, filter and sorting.</p>
	ListSoftphoneAccounts(context.Context, *ListSoftphoneAccountsRequest) (*ListSoftphoneAccountsResponse, error)
	// <p>Rotates the SIP password and/or the client certificate of a softphone account and returns the new
	// ONE-TIME secrets. <b>Every rotation rotates the SIP password</b>, including one that asked only for
	// <code>rotate_certificate</code>: the Asterisk has no certificate revocation list, so a previous
	// certificate stops being usable for this account only because the password it was issued with
	// stops working. The new password takes effect immediately and drops the account&apos;s current
	// registrations, so every softphone using it must be reconfigured. A rotated certificate moves the
	// previous <code>SOFTPHONE_CERTIFICATE_STATUS_ACTIVE</code> certificate to
	// <code>SOFTPHONE_CERTIFICATE_STATUS_SUPERSEDED</code>. A rotation also unlocks an account that
	// <code>RevokeSoftphoneCertificate</code> locked (a <code>SOFTPHONE_TRANSPORT_SECURITY_CLIENT_CERTIFICATE</code>
	// account only once it again holds an ACTIVE certificate).</p>
	// <p>Rotating the certificate of a <code>SOFTPHONE_TRANSPORT_SECURITY_SERVER_TLS_ONLY</code> account is
	// allowed: it issues the certificate that a later switch to
	// <code>SOFTPHONE_TRANSPORT_SECURITY_CLIENT_CERTIFICATE</code> requires, and rotates the password too.</p>
	// <p>Errors: <code>NOT_FOUND</code> if the account does not exist; <code>INVALID_ARGUMENT</code> if
	// neither <code>rotate_sip_password</code> nor <code>rotate_certificate</code> is set;
	// <code>FAILED_PRECONDITION</code> if the project is being deleted, or, for
	// <code>rotate_certificate</code>, if the project has no Asterisk port yet or its SOFTPHONE
	// certificate authority is unusable.</p>
	RotateSoftphoneCredentials(context.Context, *RotateSoftphoneCredentialsRequest) (*RotateSoftphoneCredentialsResponse, error)
	// <p>Lists softphone client certificates, either of one softphone account or of a whole VTSI project,
	// filtered and paged, newest first. Only public material is returned.</p>
	// <p>Errors: <code>NOT_FOUND</code> if the project or account does not exist;
	// <code>INVALID_ARGUMENT</code> if no scope is set, for an invalid filter, an unknown
	// <code>field_mask</code> path, a negative <code>page_size</code> or a foreign
	// <code>page_token</code>.</p>
	ListSoftphoneCertificates(context.Context, *ListSoftphoneCertificatesRequest) (*ListSoftphoneCertificatesResponse, error)
	// <p>Returns one softphone client certificate. Only public material is returned.</p>
	// <p>Errors: <code>NOT_FOUND</code> if the certificate does not exist; <code>INVALID_ARGUMENT</code> for
	// a malformed name or an unknown <code>field_mask</code> path.</p>
	GetSoftphoneCertificate(context.Context, *GetSoftphoneCertificateRequest) (*SoftphoneCertificate, error)
	// <p>Revokes a softphone client certificate. The Asterisk has no certificate revocation list, so
	// revocation is enforced on the account&apos;s SIP password rather than on the certificate: a revoked
	// certificate still completes the TLS handshake on the project&apos;s mutual-TLS port, but it no longer
	// gets its holder an account.</p>
	// <p>Revoking the ACTIVE certificate of an account LOCKS the account, whatever its transport
	// security: it is removed from the Asterisk and its registrations are dropped until
	// <code>RotateSoftphoneCredentials</code> issues a new password (and, for
	// <code>SOFTPHONE_TRANSPORT_SECURITY_CLIENT_CERTIFICATE</code>, a new certificate). Revoking a
	// SUPERSEDED certificate records the revocation only; its password was already rotated away.
	// Revoking an already revoked certificate is idempotent and keeps the original revocation time and
	// reason.</p>
	// <p>Errors: <code>NOT_FOUND</code> if the certificate does not exist; <code>INVALID_ARGUMENT</code>
	// for a malformed name or an over-long reason.</p>
	RevokeSoftphoneCertificate(context.Context, *RevokeSoftphoneCertificateRequest) (*SoftphoneCertificate, error)
	// <p>Returns everything needed to configure a softphone for an account: server, port, transport,
	// outbound proxy, SIP identity, SRTP mode, codecs, the certificate authority to trust, which client
	// certificate to import, and step-by-step Zoiper instructions. It never contains the SIP password or
	// the private key; those were returned once by <code>CreateSoftphoneAccount</code> or
	// <code>RotateSoftphoneCredentials</code>.</p>
	// <p>Errors: <code>NOT_FOUND</code> if the account does not exist; <code>FAILED_PRECONDITION</code> if
	// the project is not <code>DEPLOYED</code> (the host and ports describe a running Asterisk), or if a
	// <code>SOFTPHONE_TRANSPORT_SECURITY_CLIENT_CERTIFICATE</code> account has no
	// <code>SOFTPHONE_CERTIFICATE_STATUS_ACTIVE</code> certificate.</p>
	GetSoftphoneProvisioning(context.Context, *GetSoftphoneProvisioningRequest) (*SoftphoneProvisioning, error)
	mustEmbedUnimplementedSoftphonesServer()
}

// UnimplementedSoftphonesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSoftphonesServer struct{}

func (UnimplementedSoftphonesServer) CreateSoftphoneAccount(context.Context, *CreateSoftphoneAccountRequest) (*CreateSoftphoneAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSoftphoneAccount not implemented")
}
func (UnimplementedSoftphonesServer) GetSoftphoneAccount(context.Context, *GetSoftphoneAccountRequest) (*SoftphoneAccount, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSoftphoneAccount not implemented")
}
func (UnimplementedSoftphonesServer) UpdateSoftphoneAccount(context.Context, *UpdateSoftphoneAccountRequest) (*SoftphoneAccount, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSoftphoneAccount not implemented")
}
func (UnimplementedSoftphonesServer) DeleteSoftphoneAccount(context.Context, *DeleteSoftphoneAccountRequest) (*DeleteSoftphoneAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSoftphoneAccount not implemented")
}
func (UnimplementedSoftphonesServer) ListSoftphoneAccounts(context.Context, *ListSoftphoneAccountsRequest) (*ListSoftphoneAccountsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSoftphoneAccounts not implemented")
}
func (UnimplementedSoftphonesServer) RotateSoftphoneCredentials(context.Context, *RotateSoftphoneCredentialsRequest) (*RotateSoftphoneCredentialsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RotateSoftphoneCredentials not implemented")
}
func (UnimplementedSoftphonesServer) ListSoftphoneCertificates(context.Context, *ListSoftphoneCertificatesRequest) (*ListSoftphoneCertificatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSoftphoneCertificates not implemented")
}
func (UnimplementedSoftphonesServer) GetSoftphoneCertificate(context.Context, *GetSoftphoneCertificateRequest) (*SoftphoneCertificate, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSoftphoneCertificate not implemented")
}
func (UnimplementedSoftphonesServer) RevokeSoftphoneCertificate(context.Context, *RevokeSoftphoneCertificateRequest) (*SoftphoneCertificate, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeSoftphoneCertificate not implemented")
}
func (UnimplementedSoftphonesServer) GetSoftphoneProvisioning(context.Context, *GetSoftphoneProvisioningRequest) (*SoftphoneProvisioning, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSoftphoneProvisioning not implemented")
}
func (UnimplementedSoftphonesServer) mustEmbedUnimplementedSoftphonesServer() {}
func (UnimplementedSoftphonesServer) testEmbeddedByValue()                    {}

// UnsafeSoftphonesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SoftphonesServer will
// result in compilation errors.
type UnsafeSoftphonesServer interface {
	mustEmbedUnimplementedSoftphonesServer()
}

func RegisterSoftphonesServer(s grpc.ServiceRegistrar, srv SoftphonesServer) {
	// If the following call panics, it indicates UnimplementedSoftphonesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Softphones_ServiceDesc, srv)
}

func _Softphones_CreateSoftphoneAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSoftphoneAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SoftphonesServer).CreateSoftphoneAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Softphones_CreateSoftphoneAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SoftphonesServer).CreateSoftphoneAccount(ctx, req.(*CreateSoftphoneAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Softphones_GetSoftphoneAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSoftphoneAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SoftphonesServer).GetSoftphoneAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Softphones_GetSoftphoneAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SoftphonesServer).GetSoftphoneAccount(ctx, req.(*GetSoftphoneAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Softphones_UpdateSoftphoneAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSoftphoneAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SoftphonesServer).UpdateSoftphoneAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Softphones_UpdateSoftphoneAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SoftphonesServer).UpdateSoftphoneAccount(ctx, req.(*UpdateSoftphoneAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Softphones_DeleteSoftphoneAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSoftphoneAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SoftphonesServer).DeleteSoftphoneAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Softphones_DeleteSoftphoneAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SoftphonesServer).DeleteSoftphoneAccount(ctx, req.(*DeleteSoftphoneAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Softphones_ListSoftphoneAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSoftphoneAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SoftphonesServer).ListSoftphoneAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Softphones_ListSoftphoneAccounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SoftphonesServer).ListSoftphoneAccounts(ctx, req.(*ListSoftphoneAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Softphones_RotateSoftphoneCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateSoftphoneCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SoftphonesServer).RotateSoftphoneCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Softphones_RotateSoftphoneCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SoftphonesServer).RotateSoftphoneCredentials(ctx, req.(*RotateSoftphoneCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Softphones_ListSoftphoneCertificates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSoftphoneCertificatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SoftphonesServer).ListSoftphoneCertificates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Softphones_ListSoftphoneCertificates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SoftphonesServer).ListSoftphoneCertificates(ctx, req.(*ListSoftphoneCertificatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Softphones_GetSoftphoneCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSoftphoneCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SoftphonesServer).GetSoftphoneCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Softphones_GetSoftphoneCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SoftphonesServer).GetSoftphoneCertificate(ctx, req.(*GetSoftphoneCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Softphones_RevokeSoftphoneCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeSoftphoneCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SoftphonesServer).RevokeSoftphoneCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Softphones_RevokeSoftphoneCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SoftphonesServer).RevokeSoftphoneCertificate(ctx, req.(*RevokeSoftphoneCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Softphones_GetSoftphoneProvisioning_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSoftphoneProvisioningRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SoftphonesServer).GetSoftphoneProvisioning(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Softphones_GetSoftphoneProvisioning_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SoftphonesServer).GetSoftphoneProvisioning(ctx, req.(*GetSoftphoneProvisioningRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Softphones_ServiceDesc is the grpc.ServiceDesc for Softphones service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Softphones_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ondewo.vtsi.Softphones",
	HandlerType: (*SoftphonesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSoftphoneAccount",
			Handler:    _Softphones_CreateSoftphoneAccount_Handler,
		},
		{
			MethodName: "GetSoftphoneAccount",
			Handler:    _Softphones_GetSoftphoneAccount_Handler,
		},
		{
			MethodName: "UpdateSoftphoneAccount",
			Handler:    _Softphones_UpdateSoftphoneAccount_Handler,
		},
		{
			MethodName: "DeleteSoftphoneAccount",
			Handler:    _Softphones_DeleteSoftphoneAccount_Handler,
		},
		{
			MethodName: "ListSoftphoneAccounts",
			Handler:    _Softphones_ListSoftphoneAccounts_Handler,
		},
		{
			MethodName: "RotateSoftphoneCredentials",
			Handler:    _Softphones_RotateSoftphoneCredentials_Handler,
		},
		{
			MethodName: "ListSoftphoneCertificates",
			Handler:    _Softphones_ListSoftphoneCertificates_Handler,
		},
		{
			MethodName: "GetSoftphoneCertificate",
			Handler:    _Softphones_GetSoftphoneCertificate_Handler,
		},
		{
			MethodName: "RevokeSoftphoneCertificate",
			Handler:    _Softphones_RevokeSoftphoneCertificate_Handler,
		},
		{
			MethodName: "GetSoftphoneProvisioning",
			Handler:    _Softphones_GetSoftphoneProvisioning_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ondewo/vtsi/softphones.proto",
}
