// Copyright 2023 ONDEWO GmbH
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.https://ondewo.slack.com/archives/CAWPP61NY

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.32.0
// source: ondewo/s2t/speech-to-text.proto

package s2t

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Speech2Text_TranscribeFile_FullMethodName                = "/ondewo.s2t.Speech2Text/TranscribeFile"
	Speech2Text_TranscribeStream_FullMethodName              = "/ondewo.s2t.Speech2Text/TranscribeStream"
	Speech2Text_GetS2TPipeline_FullMethodName                = "/ondewo.s2t.Speech2Text/GetS2tPipeline"
	Speech2Text_CreateS2TPipeline_FullMethodName             = "/ondewo.s2t.Speech2Text/CreateS2tPipeline"
	Speech2Text_DeleteS2TPipeline_FullMethodName             = "/ondewo.s2t.Speech2Text/DeleteS2tPipeline"
	Speech2Text_UpdateS2TPipeline_FullMethodName             = "/ondewo.s2t.Speech2Text/UpdateS2tPipeline"
	Speech2Text_ListS2TPipelines_FullMethodName              = "/ondewo.s2t.Speech2Text/ListS2tPipelines"
	Speech2Text_ListS2TLanguages_FullMethodName              = "/ondewo.s2t.Speech2Text/ListS2tLanguages"
	Speech2Text_ListS2TDomains_FullMethodName                = "/ondewo.s2t.Speech2Text/ListS2tDomains"
	Speech2Text_GetServiceInfo_FullMethodName                = "/ondewo.s2t.Speech2Text/GetServiceInfo"
	Speech2Text_ListS2TLanguageModels_FullMethodName         = "/ondewo.s2t.Speech2Text/ListS2tLanguageModels"
	Speech2Text_CreateUserLanguageModel_FullMethodName       = "/ondewo.s2t.Speech2Text/CreateUserLanguageModel"
	Speech2Text_DeleteUserLanguageModel_FullMethodName       = "/ondewo.s2t.Speech2Text/DeleteUserLanguageModel"
	Speech2Text_AddDataToUserLanguageModel_FullMethodName    = "/ondewo.s2t.Speech2Text/AddDataToUserLanguageModel"
	Speech2Text_TrainUserLanguageModel_FullMethodName        = "/ondewo.s2t.Speech2Text/TrainUserLanguageModel"
	Speech2Text_ListS2TNormalizationPipelines_FullMethodName = "/ondewo.s2t.Speech2Text/ListS2tNormalizationPipelines"
)

// Speech2TextClient is the client API for Speech2Text service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// <p>Speech-to-text service</p>
type Speech2TextClient interface {
	// <p>Transcribes an audio file</p>
	TranscribeFile(ctx context.Context, in *TranscribeFileRequest, opts ...grpc.CallOption) (*TranscribeFileResponse, error)
	// <p>Transcribes an audio stream.</p>
	TranscribeStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TranscribeStreamRequest, TranscribeStreamResponse], error)
	// <p>Gets a speech to text pipeline corresponding to the id specified in <code>S2tPipelineId</code>. If no corresponding id is
	// found, raises <code>ModuleNotFoundError</code> in server.</p>
	GetS2TPipeline(ctx context.Context, in *S2TPipelineId, opts ...grpc.CallOption) (*Speech2TextConfig, error)
	// <p>Creates a new speech to text pipeline from a <code>Speech2TextConfig</code> and registers the new pipeline in the server.</p>
	CreateS2TPipeline(ctx context.Context, in *Speech2TextConfig, opts ...grpc.CallOption) (*S2TPipelineId, error)
	// <p>Deletes a pipeline corresponding to the id parsed in <code>S2tPipelineId</code>. If no corresponding id is
	// found, raises <code>ModuleNotFoundError</code> in server.</p>
	DeleteS2TPipeline(ctx context.Context, in *S2TPipelineId, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// <p>Updates a pipeline with the id specified in <code>Speech2TextConfig</code> with the new config. If no corresponding id is
	// found, raises <code>ModuleNotFoundError</code> in server.</p>
	UpdateS2TPipeline(ctx context.Context, in *Speech2TextConfig, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// <p>Lists all speech to text pipelines.</p>
	ListS2TPipelines(ctx context.Context, in *ListS2TPipelinesRequest, opts ...grpc.CallOption) (*ListS2TPipelinesResponse, error)
	// <p>Returns a message containing a list of all languages for which there exist pipelines.</p>
	ListS2TLanguages(ctx context.Context, in *ListS2TLanguagesRequest, opts ...grpc.CallOption) (*ListS2TLanguagesResponse, error)
	// <p>Returns a message containing a list of all domains for which there exist pipelines.</p>
	ListS2TDomains(ctx context.Context, in *ListS2TDomainsRequest, opts ...grpc.CallOption) (*ListS2TDomainsResponse, error)
	// <p>Returns a message containing the version of the running speech to text server.</p>
	GetServiceInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*S2TGetServiceInfoResponse, error)
	// <p>Given a list of pipeline ids, returns a list of <code>LanguageModelPipelineId</code> messages containing the pipeline
	// id and a list of the language models loaded in the pipeline.</p>
	ListS2TLanguageModels(ctx context.Context, in *ListS2TLanguageModelsRequest, opts ...grpc.CallOption) (*ListS2TLanguageModelsResponse, error)
	// <p>Create a user language model.</p>
	CreateUserLanguageModel(ctx context.Context, in *CreateUserLanguageModelRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// <p>Delete a user language model.</p>
	DeleteUserLanguageModel(ctx context.Context, in *DeleteUserLanguageModelRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// <p>Add data to a user language model.</p>
	AddDataToUserLanguageModel(ctx context.Context, in *AddDataToUserLanguageModelRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// <p>Train a user language model.</p>
	TrainUserLanguageModel(ctx context.Context, in *TrainUserLanguageModelRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// <p>Retrieves a list of normalization pipelines based on specific requirements.</p>
	ListS2TNormalizationPipelines(ctx context.Context, in *ListS2TNormalizationPipelinesRequest, opts ...grpc.CallOption) (*ListS2TNormalizationPipelinesResponse, error)
}

type speech2TextClient struct {
	cc grpc.ClientConnInterface
}

func NewSpeech2TextClient(cc grpc.ClientConnInterface) Speech2TextClient {
	return &speech2TextClient{cc}
}

func (c *speech2TextClient) TranscribeFile(ctx context.Context, in *TranscribeFileRequest, opts ...grpc.CallOption) (*TranscribeFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TranscribeFileResponse)
	err := c.cc.Invoke(ctx, Speech2Text_TranscribeFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *speech2TextClient) TranscribeStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TranscribeStreamRequest, TranscribeStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Speech2Text_ServiceDesc.Streams[0], Speech2Text_TranscribeStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TranscribeStreamRequest, TranscribeStreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Speech2Text_TranscribeStreamClient = grpc.BidiStreamingClient[TranscribeStreamRequest, TranscribeStreamResponse]

func (c *speech2TextClient) GetS2TPipeline(ctx context.Context, in *S2TPipelineId, opts ...grpc.CallOption) (*Speech2TextConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Speech2TextConfig)
	err := c.cc.Invoke(ctx, Speech2Text_GetS2TPipeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *speech2TextClient) CreateS2TPipeline(ctx context.Context, in *Speech2TextConfig, opts ...grpc.CallOption) (*S2TPipelineId, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(S2TPipelineId)
	err := c.cc.Invoke(ctx, Speech2Text_CreateS2TPipeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *speech2TextClient) DeleteS2TPipeline(ctx context.Context, in *S2TPipelineId, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Speech2Text_DeleteS2TPipeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *speech2TextClient) UpdateS2TPipeline(ctx context.Context, in *Speech2TextConfig, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Speech2Text_UpdateS2TPipeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *speech2TextClient) ListS2TPipelines(ctx context.Context, in *ListS2TPipelinesRequest, opts ...grpc.CallOption) (*ListS2TPipelinesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListS2TPipelinesResponse)
	err := c.cc.Invoke(ctx, Speech2Text_ListS2TPipelines_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *speech2TextClient) ListS2TLanguages(ctx context.Context, in *ListS2TLanguagesRequest, opts ...grpc.CallOption) (*ListS2TLanguagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListS2TLanguagesResponse)
	err := c.cc.Invoke(ctx, Speech2Text_ListS2TLanguages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *speech2TextClient) ListS2TDomains(ctx context.Context, in *ListS2TDomainsRequest, opts ...grpc.CallOption) (*ListS2TDomainsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListS2TDomainsResponse)
	err := c.cc.Invoke(ctx, Speech2Text_ListS2TDomains_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *speech2TextClient) GetServiceInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*S2TGetServiceInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(S2TGetServiceInfoResponse)
	err := c.cc.Invoke(ctx, Speech2Text_GetServiceInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *speech2TextClient) ListS2TLanguageModels(ctx context.Context, in *ListS2TLanguageModelsRequest, opts ...grpc.CallOption) (*ListS2TLanguageModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListS2TLanguageModelsResponse)
	err := c.cc.Invoke(ctx, Speech2Text_ListS2TLanguageModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *speech2TextClient) CreateUserLanguageModel(ctx context.Context, in *CreateUserLanguageModelRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Speech2Text_CreateUserLanguageModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *speech2TextClient) DeleteUserLanguageModel(ctx context.Context, in *DeleteUserLanguageModelRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Speech2Text_DeleteUserLanguageModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *speech2TextClient) AddDataToUserLanguageModel(ctx context.Context, in *AddDataToUserLanguageModelRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Speech2Text_AddDataToUserLanguageModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *speech2TextClient) TrainUserLanguageModel(ctx context.Context, in *TrainUserLanguageModelRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Speech2Text_TrainUserLanguageModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *speech2TextClient) ListS2TNormalizationPipelines(ctx context.Context, in *ListS2TNormalizationPipelinesRequest, opts ...grpc.CallOption) (*ListS2TNormalizationPipelinesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListS2TNormalizationPipelinesResponse)
	err := c.cc.Invoke(ctx, Speech2Text_ListS2TNormalizationPipelines_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Speech2TextServer is the server API for Speech2Text service.
// All implementations must embed UnimplementedSpeech2TextServer
// for forward compatibility.
//
// <p>Speech-to-text service</p>
type Speech2TextServer interface {
	// <p>Transcribes an audio file</p>
	TranscribeFile(context.Context, *TranscribeFileRequest) (*TranscribeFileResponse, error)
	// <p>Transcribes an audio stream.</p>
	TranscribeStream(grpc.BidiStreamingServer[TranscribeStreamRequest, TranscribeStreamResponse]) error
	// <p>Gets a speech to text pipeline corresponding to the id specified in <code>S2tPipelineId</code>. If no corresponding id is
	// found, raises <code>ModuleNotFoundError</code> in server.</p>
	GetS2TPipeline(context.Context, *S2TPipelineId) (*Speech2TextConfig, error)
	// <p>Creates a new speech to text pipeline from a <code>Speech2TextConfig</code> and registers the new pipeline in the server.</p>
	CreateS2TPipeline(context.Context, *Speech2TextConfig) (*S2TPipelineId, error)
	// <p>Deletes a pipeline corresponding to the id parsed in <code>S2tPipelineId</code>. If no corresponding id is
	// found, raises <code>ModuleNotFoundError</code> in server.</p>
	DeleteS2TPipeline(context.Context, *S2TPipelineId) (*emptypb.Empty, error)
	// <p>Updates a pipeline with the id specified in <code>Speech2TextConfig</code> with the new config. If no corresponding id is
	// found, raises <code>ModuleNotFoundError</code> in server.</p>
	UpdateS2TPipeline(context.Context, *Speech2TextConfig) (*emptypb.Empty, error)
	// <p>Lists all speech to text pipelines.</p>
	ListS2TPipelines(context.Context, *ListS2TPipelinesRequest) (*ListS2TPipelinesResponse, error)
	// <p>Returns a message containing a list of all languages for which there exist pipelines.</p>
	ListS2TLanguages(context.Context, *ListS2TLanguagesRequest) (*ListS2TLanguagesResponse, error)
	// <p>Returns a message containing a list of all domains for which there exist pipelines.</p>
	ListS2TDomains(context.Context, *ListS2TDomainsRequest) (*ListS2TDomainsResponse, error)
	// <p>Returns a message containing the version of the running speech to text server.</p>
	GetServiceInfo(context.Context, *emptypb.Empty) (*S2TGetServiceInfoResponse, error)
	// <p>Given a list of pipeline ids, returns a list of <code>LanguageModelPipelineId</code> messages containing the pipeline
	// id and a list of the language models loaded in the pipeline.</p>
	ListS2TLanguageModels(context.Context, *ListS2TLanguageModelsRequest) (*ListS2TLanguageModelsResponse, error)
	// <p>Create a user language model.</p>
	CreateUserLanguageModel(context.Context, *CreateUserLanguageModelRequest) (*emptypb.Empty, error)
	// <p>Delete a user language model.</p>
	DeleteUserLanguageModel(context.Context, *DeleteUserLanguageModelRequest) (*emptypb.Empty, error)
	// <p>Add data to a user language model.</p>
	AddDataToUserLanguageModel(context.Context, *AddDataToUserLanguageModelRequest) (*emptypb.Empty, error)
	// <p>Train a user language model.</p>
	TrainUserLanguageModel(context.Context, *TrainUserLanguageModelRequest) (*emptypb.Empty, error)
	// <p>Retrieves a list of normalization pipelines based on specific requirements.</p>
	ListS2TNormalizationPipelines(context.Context, *ListS2TNormalizationPipelinesRequest) (*ListS2TNormalizationPipelinesResponse, error)
	mustEmbedUnimplementedSpeech2TextServer()
}

// UnimplementedSpeech2TextServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSpeech2TextServer struct{}

func (UnimplementedSpeech2TextServer) TranscribeFile(context.Context, *TranscribeFileRequest) (*TranscribeFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TranscribeFile not implemented")
}
func (UnimplementedSpeech2TextServer) TranscribeStream(grpc.BidiStreamingServer[TranscribeStreamRequest, TranscribeStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method TranscribeStream not implemented")
}
func (UnimplementedSpeech2TextServer) GetS2TPipeline(context.Context, *S2TPipelineId) (*Speech2TextConfig, error) {
	return nil, status.Error(codes.Unimplemented, "method GetS2TPipeline not implemented")
}
func (UnimplementedSpeech2TextServer) CreateS2TPipeline(context.Context, *Speech2TextConfig) (*S2TPipelineId, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateS2TPipeline not implemented")
}
func (UnimplementedSpeech2TextServer) DeleteS2TPipeline(context.Context, *S2TPipelineId) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteS2TPipeline not implemented")
}
func (UnimplementedSpeech2TextServer) UpdateS2TPipeline(context.Context, *Speech2TextConfig) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateS2TPipeline not implemented")
}
func (UnimplementedSpeech2TextServer) ListS2TPipelines(context.Context, *ListS2TPipelinesRequest) (*ListS2TPipelinesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListS2TPipelines not implemented")
}
func (UnimplementedSpeech2TextServer) ListS2TLanguages(context.Context, *ListS2TLanguagesRequest) (*ListS2TLanguagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListS2TLanguages not implemented")
}
func (UnimplementedSpeech2TextServer) ListS2TDomains(context.Context, *ListS2TDomainsRequest) (*ListS2TDomainsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListS2TDomains not implemented")
}
func (UnimplementedSpeech2TextServer) GetServiceInfo(context.Context, *emptypb.Empty) (*S2TGetServiceInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetServiceInfo not implemented")
}
func (UnimplementedSpeech2TextServer) ListS2TLanguageModels(context.Context, *ListS2TLanguageModelsRequest) (*ListS2TLanguageModelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListS2TLanguageModels not implemented")
}
func (UnimplementedSpeech2TextServer) CreateUserLanguageModel(context.Context, *CreateUserLanguageModelRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUserLanguageModel not implemented")
}
func (UnimplementedSpeech2TextServer) DeleteUserLanguageModel(context.Context, *DeleteUserLanguageModelRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteUserLanguageModel not implemented")
}
func (UnimplementedSpeech2TextServer) AddDataToUserLanguageModel(context.Context, *AddDataToUserLanguageModelRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AddDataToUserLanguageModel not implemented")
}
func (UnimplementedSpeech2TextServer) TrainUserLanguageModel(context.Context, *TrainUserLanguageModelRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method TrainUserLanguageModel not implemented")
}
func (UnimplementedSpeech2TextServer) ListS2TNormalizationPipelines(context.Context, *ListS2TNormalizationPipelinesRequest) (*ListS2TNormalizationPipelinesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListS2TNormalizationPipelines not implemented")
}
func (UnimplementedSpeech2TextServer) mustEmbedUnimplementedSpeech2TextServer() {}
func (UnimplementedSpeech2TextServer) testEmbeddedByValue()                     {}

// UnsafeSpeech2TextServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Speech2TextServer will
// result in compilation errors.
type UnsafeSpeech2TextServer interface {
	mustEmbedUnimplementedSpeech2TextServer()
}

func RegisterSpeech2TextServer(s grpc.ServiceRegistrar, srv Speech2TextServer) {
	// If the following call panics, it indicates UnimplementedSpeech2TextServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Speech2Text_ServiceDesc, srv)
}

func _Speech2Text_TranscribeFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TranscribeFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Speech2TextServer).TranscribeFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Speech2Text_TranscribeFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Speech2TextServer).TranscribeFile(ctx, req.(*TranscribeFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Speech2Text_TranscribeStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(Speech2TextServer).TranscribeStream(&grpc.GenericServerStream[TranscribeStreamRequest, TranscribeStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Speech2Text_TranscribeStreamServer = grpc.BidiStreamingServer[TranscribeStreamRequest, TranscribeStreamResponse]

func _Speech2Text_GetS2TPipeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(S2TPipelineId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Speech2TextServer).GetS2TPipeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Speech2Text_GetS2TPipeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Speech2TextServer).GetS2TPipeline(ctx, req.(*S2TPipelineId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Speech2Text_CreateS2TPipeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Speech2TextConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Speech2TextServer).CreateS2TPipeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Speech2Text_CreateS2TPipeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Speech2TextServer).CreateS2TPipeline(ctx, req.(*Speech2TextConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _Speech2Text_DeleteS2TPipeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(S2TPipelineId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Speech2TextServer).DeleteS2TPipeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Speech2Text_DeleteS2TPipeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Speech2TextServer).DeleteS2TPipeline(ctx, req.(*S2TPipelineId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Speech2Text_UpdateS2TPipeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Speech2TextConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Speech2TextServer).UpdateS2TPipeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Speech2Text_UpdateS2TPipeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Speech2TextServer).UpdateS2TPipeline(ctx, req.(*Speech2TextConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _Speech2Text_ListS2TPipelines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListS2TPipelinesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Speech2TextServer).ListS2TPipelines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Speech2Text_ListS2TPipelines_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Speech2TextServer).ListS2TPipelines(ctx, req.(*ListS2TPipelinesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Speech2Text_ListS2TLanguages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListS2TLanguagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Speech2TextServer).ListS2TLanguages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Speech2Text_ListS2TLanguages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Speech2TextServer).ListS2TLanguages(ctx, req.(*ListS2TLanguagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Speech2Text_ListS2TDomains_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListS2TDomainsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Speech2TextServer).ListS2TDomains(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Speech2Text_ListS2TDomains_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Speech2TextServer).ListS2TDomains(ctx, req.(*ListS2TDomainsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Speech2Text_GetServiceInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Speech2TextServer).GetServiceInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Speech2Text_GetServiceInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Speech2TextServer).GetServiceInfo(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Speech2Text_ListS2TLanguageModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListS2TLanguageModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Speech2TextServer).ListS2TLanguageModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Speech2Text_ListS2TLanguageModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Speech2TextServer).ListS2TLanguageModels(ctx, req.(*ListS2TLanguageModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Speech2Text_CreateUserLanguageModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserLanguageModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Speech2TextServer).CreateUserLanguageModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Speech2Text_CreateUserLanguageModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Speech2TextServer).CreateUserLanguageModel(ctx, req.(*CreateUserLanguageModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Speech2Text_DeleteUserLanguageModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserLanguageModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Speech2TextServer).DeleteUserLanguageModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Speech2Text_DeleteUserLanguageModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Speech2TextServer).DeleteUserLanguageModel(ctx, req.(*DeleteUserLanguageModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Speech2Text_AddDataToUserLanguageModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDataToUserLanguageModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Speech2TextServer).AddDataToUserLanguageModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Speech2Text_AddDataToUserLanguageModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Speech2TextServer).AddDataToUserLanguageModel(ctx, req.(*AddDataToUserLanguageModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Speech2Text_TrainUserLanguageModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrainUserLanguageModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Speech2TextServer).TrainUserLanguageModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Speech2Text_TrainUserLanguageModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Speech2TextServer).TrainUserLanguageModel(ctx, req.(*TrainUserLanguageModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Speech2Text_ListS2TNormalizationPipelines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListS2TNormalizationPipelinesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Speech2TextServer).ListS2TNormalizationPipelines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Speech2Text_ListS2TNormalizationPipelines_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Speech2TextServer).ListS2TNormalizationPipelines(ctx, req.(*ListS2TNormalizationPipelinesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Speech2Text_ServiceDesc is the grpc.ServiceDesc for Speech2Text service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Speech2Text_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ondewo.s2t.Speech2Text",
	HandlerType: (*Speech2TextServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TranscribeFile",
			Handler:    _Speech2Text_TranscribeFile_Handler,
		},
		{
			MethodName: "GetS2tPipeline",
			Handler:    _Speech2Text_GetS2TPipeline_Handler,
		},
		{
			MethodName: "CreateS2tPipeline",
			Handler:    _Speech2Text_CreateS2TPipeline_Handler,
		},
		{
			MethodName: "DeleteS2tPipeline",
			Handler:    _Speech2Text_DeleteS2TPipeline_Handler,
		},
		{
			MethodName: "UpdateS2tPipeline",
			Handler:    _Speech2Text_UpdateS2TPipeline_Handler,
		},
		{
			MethodName: "ListS2tPipelines",
			Handler:    _Speech2Text_ListS2TPipelines_Handler,
		},
		{
			MethodName: "ListS2tLanguages",
			Handler:    _Speech2Text_ListS2TLanguages_Handler,
		},
		{
			MethodName: "ListS2tDomains",
			Handler:    _Speech2Text_ListS2TDomains_Handler,
		},
		{
			MethodName: "GetServiceInfo",
			Handler:    _Speech2Text_GetServiceInfo_Handler,
		},
		{
			MethodName: "ListS2tLanguageModels",
			Handler:    _Speech2Text_ListS2TLanguageModels_Handler,
		},
		{
			MethodName: "CreateUserLanguageModel",
			Handler:    _Speech2Text_CreateUserLanguageModel_Handler,
		},
		{
			MethodName: "DeleteUserLanguageModel",
			Handler:    _Speech2Text_DeleteUserLanguageModel_Handler,
		},
		{
			MethodName: "AddDataToUserLanguageModel",
			Handler:    _Speech2Text_AddDataToUserLanguageModel_Handler,
		},
		{
			MethodName: "TrainUserLanguageModel",
			Handler:    _Speech2Text_TrainUserLanguageModel_Handler,
		},
		{
			MethodName: "ListS2tNormalizationPipelines",
			Handler:    _Speech2Text_ListS2TNormalizationPipelines_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TranscribeStream",
			Handler:       _Speech2Text_TranscribeStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "ondewo/s2t/speech-to-text.proto",
}
