// Copyright 2020-2026 ONDEWO GmbH
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.32.0
// source: ondewo/nlu/ccai_project.proto

package nlu

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Status of a Call Center AI (CCAI service) Project.
type CcaiProjectStatus int32

const (
	// No status specified
	CcaiProjectStatus_CCAI_PROJECT_STATUS_UNSPECIFIED CcaiProjectStatus = 0
	// Project successfully created and undeployed
	CcaiProjectStatus_CCAI_PROJECT_STATUS_UNDEPLOYED CcaiProjectStatus = 1
	// Project configuration is updating
	CcaiProjectStatus_CCAI_PROJECT_STATUS_UPDATING CcaiProjectStatus = 2
	// Project is deploying
	CcaiProjectStatus_CCAI_PROJECT_STATUS_DEPLOYING CcaiProjectStatus = 3
	// Project is deployed
	CcaiProjectStatus_CCAI_PROJECT_STATUS_DEPLOYED CcaiProjectStatus = 4
	// Project is un-deploying
	CcaiProjectStatus_CCAI_PROJECT_STATUS_UNDEPLOYING CcaiProjectStatus = 5
	// Project is currently deleting
	CcaiProjectStatus_CCAI_PROJECT_STATUS_DELETING CcaiProjectStatus = 6
	// Project is deleted
	CcaiProjectStatus_CCAI_PROJECT_STATUS_DELETED CcaiProjectStatus = 7
)

// Enum value maps for CcaiProjectStatus.
var (
	CcaiProjectStatus_name = map[int32]string{
		0: "CCAI_PROJECT_STATUS_UNSPECIFIED",
		1: "CCAI_PROJECT_STATUS_UNDEPLOYED",
		2: "CCAI_PROJECT_STATUS_UPDATING",
		3: "CCAI_PROJECT_STATUS_DEPLOYING",
		4: "CCAI_PROJECT_STATUS_DEPLOYED",
		5: "CCAI_PROJECT_STATUS_UNDEPLOYING",
		6: "CCAI_PROJECT_STATUS_DELETING",
		7: "CCAI_PROJECT_STATUS_DELETED",
	}
	CcaiProjectStatus_value = map[string]int32{
		"CCAI_PROJECT_STATUS_UNSPECIFIED": 0,
		"CCAI_PROJECT_STATUS_UNDEPLOYED":  1,
		"CCAI_PROJECT_STATUS_UPDATING":    2,
		"CCAI_PROJECT_STATUS_DEPLOYING":   3,
		"CCAI_PROJECT_STATUS_DEPLOYED":    4,
		"CCAI_PROJECT_STATUS_UNDEPLOYING": 5,
		"CCAI_PROJECT_STATUS_DELETING":    6,
		"CCAI_PROJECT_STATUS_DELETED":     7,
	}
)

func (x CcaiProjectStatus) Enum() *CcaiProjectStatus {
	p := new(CcaiProjectStatus)
	*p = x
	return p
}

func (x CcaiProjectStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CcaiProjectStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_ondewo_nlu_ccai_project_proto_enumTypes[0].Descriptor()
}

func (CcaiProjectStatus) Type() protoreflect.EnumType {
	return &file_ondewo_nlu_ccai_project_proto_enumTypes[0]
}

func (x CcaiProjectStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CcaiProjectStatus.Descriptor instead.
func (CcaiProjectStatus) EnumDescriptor() ([]byte, []int) {
	return file_ondewo_nlu_ccai_project_proto_rawDescGZIP(), []int{0}
}

// Defines the types of CCAI (Call Center AI) services available in the system.
//
// Each service type represents a specific capability or module within the ONDEWO platform
// that enables comprehensive call center and customer interaction management. Services can be
// composed in workflows and are identified by their type, language code, and provider configuration.
type CcaiServiceType int32

const (
	// No service type specified or unknown type
	CcaiServiceType_CCAI_SERVICE_TYPE_UNSPECIFIED CcaiServiceType = 0
	// ONDEWO Agent Interaction Manager (AIM)
	// Orchestrates multi-channel agent interactions, conversation routing, and workforce management.
	// Handles inbound/outbound call distribution, chat routing, and agent state management.
	CcaiServiceType_CCAI_SERVICE_TYPE_ONDEWO_AIM CcaiServiceType = 1
	// ONDEWO Business Process Intelligence (BPI)
	// Analyzes call center processes, identifies optimization opportunities, and monitors compliance.
	// Enables workflow automation, process mining, and performance benchmarking.
	CcaiServiceType_CCAI_SERVICE_TYPE_ONDEWO_BPI CcaiServiceType = 2
	// ONDEWO Customer Service Intelligence (CSI)
	// Provides customer service analytics, sentiment analysis, and interaction quality scoring.
	// Generates insights from call recordings, transcripts, and customer feedback.
	CcaiServiceType_CCAI_SERVICE_TYPE_ONDEWO_CSI CcaiServiceType = 3
	// ONDEWO Natural Language Understanding (NLU)
	// Core natural language processing service for intent recognition, entity extraction, and dialogue management.
	// Essential for conversational AI and automated customer interactions.
	CcaiServiceType_CCAI_SERVICE_TYPE_ONDEWO_NLU CcaiServiceType = 4
	// ONDEWO Speech-to-Text (S2T)
	// Converts audio speech to written text with high accuracy and multi-language support.
	// Integrates with voice channels for real-time transcription during calls.
	CcaiServiceType_CCAI_SERVICE_TYPE_ONDEWO_S2T CcaiServiceType = 5
	// ONDEWO Session Initiation Protocol (SIP)
	// Manages VoIP signaling, call establishment, call control, and telephony infrastructure.
	// Handles SIP trunk integration, PBX connectivity, and call routing logic.
	CcaiServiceType_CCAI_SERVICE_TYPE_ONDEWO_SIP CcaiServiceType = 6
	// ONDEWO Text-to-Speech (T2S)
	// Converts written text to natural-sounding audio speech with multiple voice options.
	// Enables voice-based responses, IVR prompts, and notification delivery.
	CcaiServiceType_CCAI_SERVICE_TYPE_ONDEWO_T2S CcaiServiceType = 7
	// ONDEWO VOIP Telephone System Integration (VTSI)
	// Provides virtual telephony infrastructure for testing, simulation, and call management.
	// Enables stress testing, scenario simulation, and quality assurance for voice applications.
	CcaiServiceType_CCAI_SERVICE_TYPE_ONDEWO_VTSI CcaiServiceType = 8
	// ONDEWO VOIP Telephone System Integration (VTSI) with RabbitMQ
	// Extended VTSI service with RabbitMQ message queue integration for asynchronous processing.
	// Enables decoupled, scalable call handling and event streaming.
	CcaiServiceType_CCAI_SERVICE_TYPE_ONDEWO_VTSI_RABBITMQ CcaiServiceType = 9
	// ONDEWO NLU Question Answering (QA)
	// Provides intelligent question-answering capabilities for knowledge base queries.
	// Enables automated FAQ handling and self-service customer support.
	CcaiServiceType_CCAI_SERVICE_TYPE_ONDEWO_NLU_QA CcaiServiceType = 10
	// ONDEWO NLU Webhook
	// Enables webhook-based event integration for NLU events and external notifications.
	// Allows real-time integration with third-party systems and custom workflows.
	CcaiServiceType_CCAI_SERVICE_TYPE_ONDEWO_NLU_WEBHOOK CcaiServiceType = 11
	// ONDEWO Survey
	// Manages survey campaigns, customer feedback collection, and satisfaction measurements.
	// Supports post-call surveys and voice-based survey delivery.
	CcaiServiceType_CCAI_SERVICE_TYPE_ONDEWO_SURVEY CcaiServiceType = 12
	// ONDEWO NLU Large Language Model (LLM)
	// Integrates large language models for advanced NLP tasks and generative AI capabilities.
	// Enables contextual responses, content generation, and semantic understanding.
	CcaiServiceType_CCAI_SERVICE_TYPE_ONDEWO_NLU_LLM CcaiServiceType = 13
	// ONDEWO NLU Web Search
	// Performs real-time internet search queries and retrieves current information.
	// Enables agents to access live data during customer interactions.
	CcaiServiceType_CCAI_SERVICE_TYPE_ONDEWO_NLU_WEBSEARCH CcaiServiceType = 14
	// ONDEWO Agent Interaction Manager (AIM) WebChat
	// Enables live chat interactions via web browsers for customer support.
	// Manages web-based messaging channels with agent assignment and routing.
	CcaiServiceType_CCAI_SERVICE_TYPE_ONDEWO_AIM_WEBCHAT CcaiServiceType = 15
	// ONDEWO Agent Interaction Manager (AIM) WebPhone
	// Enables VoIP phone interactions directly through web browsers without additional software.
	// Supports WebRTC-based calling for modern browser environments.
	CcaiServiceType_CCAI_SERVICE_TYPE_ONDEWO_AIM_WEBPHONE CcaiServiceType = 16
	// ONDEWO NLU Vector Store
	// Manages vector embeddings and semantic search capabilities for knowledge retrieval.
	// Enables similarity matching and context-aware information lookup.
	CcaiServiceType_CCAI_SERVICE_TYPE_ONDEWO_NLU_VECTORSTORE CcaiServiceType = 17
	// ONDEWO NLU LLM Agent
	// Autonomous agent powered by large language models with tool-calling capabilities.
	// Enables complex, multi-step tasks and dynamic decision-making in customer interactions.
	CcaiServiceType_CCAI_SERVICE_TYPE_ONDEWO_NLU_LLM_AGENT CcaiServiceType = 18
	// ONDEWO NLU LLM Model Context Protocol (MCP)
	// Integrates large language models with the Model Context Protocol standard for tool usage.
	// Enables standardized integration with external tools and data sources.
	CcaiServiceType_CCAI_SERVICE_TYPE_ONDEWO_NLU_LLM_MCP CcaiServiceType = 19
	// ONDEWO NLU LLM Retrieval-Augmented Generation (RAG)
	// Enhances large language model responses with document and knowledge base retrieval.
	// Enables grounded, factual responses backed by organizational knowledge.
	CcaiServiceType_CCAI_SERVICE_TYPE_ONDEWO_NLU_LLM_RAG CcaiServiceType = 20
	// ONDEWO Analytics
	// Provides comprehensive analytics and metrics for call center operations and KPI tracking.
	// Enables real-time dashboards, historical analysis, and predictive insights.
	CcaiServiceType_CCAI_SERVICE_TYPE_ONDEWO_ANALYTICS CcaiServiceType = 21
	// ONDEWO Analytics Dashboard
	// Visual dashboard for displaying analytics, KPIs, and performance metrics.
	// Provides interactive reports for supervisors, managers, and executives.
	CcaiServiceType_CCAI_SERVICE_TYPE_ONDEWO_ANALYTICS_DASHBOARD CcaiServiceType = 22
	// ONDEWO VOIP Telephone System Integration (VTSI) Outbound Calling
	// Handles outbound call campaigns and call management.
	// Enables sales outreach, follow-ups, and proactive customer communication.
	CcaiServiceType_CCAI_SERVICE_TYPE_ONDEWO_VTSI_OUTBOUND_CAMPAIGN CcaiServiceType = 23
	// ONDEWO VOIP Telephone System Integration (VTSI) Inbound Campaign
	// Manages inbound call campaigns and call routing for marketing or support purposes.
	// Enables targeted call handling and customer engagement strategies.
	CcaiServiceType_CCAI_SERVICE_TYPE_ONDEWO_VTSI_INBOUND_CAMPAIGN CcaiServiceType = 24
)

// Enum value maps for CcaiServiceType.
var (
	CcaiServiceType_name = map[int32]string{
		0:  "CCAI_SERVICE_TYPE_UNSPECIFIED",
		1:  "CCAI_SERVICE_TYPE_ONDEWO_AIM",
		2:  "CCAI_SERVICE_TYPE_ONDEWO_BPI",
		3:  "CCAI_SERVICE_TYPE_ONDEWO_CSI",
		4:  "CCAI_SERVICE_TYPE_ONDEWO_NLU",
		5:  "CCAI_SERVICE_TYPE_ONDEWO_S2T",
		6:  "CCAI_SERVICE_TYPE_ONDEWO_SIP",
		7:  "CCAI_SERVICE_TYPE_ONDEWO_T2S",
		8:  "CCAI_SERVICE_TYPE_ONDEWO_VTSI",
		9:  "CCAI_SERVICE_TYPE_ONDEWO_VTSI_RABBITMQ",
		10: "CCAI_SERVICE_TYPE_ONDEWO_NLU_QA",
		11: "CCAI_SERVICE_TYPE_ONDEWO_NLU_WEBHOOK",
		12: "CCAI_SERVICE_TYPE_ONDEWO_SURVEY",
		13: "CCAI_SERVICE_TYPE_ONDEWO_NLU_LLM",
		14: "CCAI_SERVICE_TYPE_ONDEWO_NLU_WEBSEARCH",
		15: "CCAI_SERVICE_TYPE_ONDEWO_AIM_WEBCHAT",
		16: "CCAI_SERVICE_TYPE_ONDEWO_AIM_WEBPHONE",
		17: "CCAI_SERVICE_TYPE_ONDEWO_NLU_VECTORSTORE",
		18: "CCAI_SERVICE_TYPE_ONDEWO_NLU_LLM_AGENT",
		19: "CCAI_SERVICE_TYPE_ONDEWO_NLU_LLM_MCP",
		20: "CCAI_SERVICE_TYPE_ONDEWO_NLU_LLM_RAG",
		21: "CCAI_SERVICE_TYPE_ONDEWO_ANALYTICS",
		22: "CCAI_SERVICE_TYPE_ONDEWO_ANALYTICS_DASHBOARD",
		23: "CCAI_SERVICE_TYPE_ONDEWO_VTSI_OUTBOUND_CAMPAIGN",
		24: "CCAI_SERVICE_TYPE_ONDEWO_VTSI_INBOUND_CAMPAIGN",
	}
	CcaiServiceType_value = map[string]int32{
		"CCAI_SERVICE_TYPE_UNSPECIFIED":                   0,
		"CCAI_SERVICE_TYPE_ONDEWO_AIM":                    1,
		"CCAI_SERVICE_TYPE_ONDEWO_BPI":                    2,
		"CCAI_SERVICE_TYPE_ONDEWO_CSI":                    3,
		"CCAI_SERVICE_TYPE_ONDEWO_NLU":                    4,
		"CCAI_SERVICE_TYPE_ONDEWO_S2T":                    5,
		"CCAI_SERVICE_TYPE_ONDEWO_SIP":                    6,
		"CCAI_SERVICE_TYPE_ONDEWO_T2S":                    7,
		"CCAI_SERVICE_TYPE_ONDEWO_VTSI":                   8,
		"CCAI_SERVICE_TYPE_ONDEWO_VTSI_RABBITMQ":          9,
		"CCAI_SERVICE_TYPE_ONDEWO_NLU_QA":                 10,
		"CCAI_SERVICE_TYPE_ONDEWO_NLU_WEBHOOK":            11,
		"CCAI_SERVICE_TYPE_ONDEWO_SURVEY":                 12,
		"CCAI_SERVICE_TYPE_ONDEWO_NLU_LLM":                13,
		"CCAI_SERVICE_TYPE_ONDEWO_NLU_WEBSEARCH":          14,
		"CCAI_SERVICE_TYPE_ONDEWO_AIM_WEBCHAT":            15,
		"CCAI_SERVICE_TYPE_ONDEWO_AIM_WEBPHONE":           16,
		"CCAI_SERVICE_TYPE_ONDEWO_NLU_VECTORSTORE":        17,
		"CCAI_SERVICE_TYPE_ONDEWO_NLU_LLM_AGENT":          18,
		"CCAI_SERVICE_TYPE_ONDEWO_NLU_LLM_MCP":            19,
		"CCAI_SERVICE_TYPE_ONDEWO_NLU_LLM_RAG":            20,
		"CCAI_SERVICE_TYPE_ONDEWO_ANALYTICS":              21,
		"CCAI_SERVICE_TYPE_ONDEWO_ANALYTICS_DASHBOARD":    22,
		"CCAI_SERVICE_TYPE_ONDEWO_VTSI_OUTBOUND_CAMPAIGN": 23,
		"CCAI_SERVICE_TYPE_ONDEWO_VTSI_INBOUND_CAMPAIGN":  24,
	}
)

func (x CcaiServiceType) Enum() *CcaiServiceType {
	p := new(CcaiServiceType)
	*p = x
	return p
}

func (x CcaiServiceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CcaiServiceType) Descriptor() protoreflect.EnumDescriptor {
	return file_ondewo_nlu_ccai_project_proto_enumTypes[1].Descriptor()
}

func (CcaiServiceType) Type() protoreflect.EnumType {
	return &file_ondewo_nlu_ccai_project_proto_enumTypes[1]
}

func (x CcaiServiceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CcaiServiceType.Descriptor instead.
func (CcaiServiceType) EnumDescriptor() ([]byte, []int) {
	return file_ondewo_nlu_ccai_project_proto_rawDescGZIP(), []int{1}
}

type CcaiServiceProvider int32

const (
	// No specified provider or placeholder
	CcaiServiceProvider_NO_CCAI_SERVICE_PROVIDER CcaiServiceProvider = 0
	// ONDEWO provider for CCAI service services
	// <a href="https://www.ondewo.com/">ONDEWO</a>
	CcaiServiceProvider_CCAI_SERVICE_PROVIDER_ONDEWO CcaiServiceProvider = 1
	// Google as the CCAI service provider, utilizing Google&apos;s conversational AI capabilities
	// <a href="https://deepmind.google/technologies/gemini/">Google Gemini</a>
	CcaiServiceProvider_CCAI_SERVICE_PROVIDER_GOOGLE_GEMINI CcaiServiceProvider = 2
	// Microsoft Azure as the CCAI service provider, using Microsoft&apos;s Azure cognitive services
	// <a href="https://azure.microsoft.com/en-us/products/cognitive-services/openai-service/">Azure OpenAI</a>
	CcaiServiceProvider_CCAI_SERVICE_PROVIDER_MICROSOFT_AZURE_OPENAI CcaiServiceProvider = 3
	// Microsoft AutoGen as the CCAI service provider
	// <a href="https://github.com/microsoft/autogen">AutoGen</a>
	CcaiServiceProvider_CCAI_SERVICE_PROVIDER_MICROSOFT_AUTOGEN CcaiServiceProvider = 4
	// Ollama as the CCAI service provider, typically associated with specific OLLAMA AI tools
	// <a href="https://github.com/ollama/ollama">Ollama</a>
	CcaiServiceProvider_CCAI_SERVICE_PROVIDER_OLLAMA CcaiServiceProvider = 5
	// OpenAI as the CCAI service provider, commonly used for models such as GPT
	// <a href="https://openai.com/">OpenAI</a>
	CcaiServiceProvider_CCAI_SERVICE_PROVIDER_OPENAI CcaiServiceProvider = 6
	// Anthropic as the CCAI service provider, used with AI models from Anthropic
	// <a href="https://www.anthropic.com/">Anthropic</a>
	CcaiServiceProvider_CCAI_SERVICE_PROVIDER_ANTHROPIC CcaiServiceProvider = 7
	// Hugging Face as the CCAI service provider, often used for open-source NLP models
	// <a href="https://huggingface.co/">Hugging Face</a>
	CcaiServiceProvider_CCAI_SERVICE_PROVIDER_HUGGINGFACE CcaiServiceProvider = 8
	// IBM as the CCAI service provider, such as IBM Watson for conversational AI
	// <a href="https://www.ibm.com/watson">IBM Watson</a>
	CcaiServiceProvider_CCAI_SERVICE_PROVIDER_IBM CcaiServiceProvider = 9
	// Haystack as the CCAI service provider, e.g., for question answering and conversations
	// <a href="https://github.com/deepset-ai/haystack">Haystack</a>
	CcaiServiceProvider_CCAI_SERVICE_PROVIDER_HAYSTACK CcaiServiceProvider = 10
	// LangChain as the CCAI service provider
	// <a href="https://github.com/langchain-ai/langchain">LangChain</a>
	CcaiServiceProvider_CCAI_SERVICE_PROVIDER_LANGCHAIN CcaiServiceProvider = 11
	// Amazon AWS as the CCAI service provider, using Amazon&apos;s AI/ML services
	// <a href="https://aws.amazon.com/machine-learning/">AWS AI Services</a>
	CcaiServiceProvider_CCAI_SERVICE_PROVIDER_AMAZON CcaiServiceProvider = 12
	// Mistral as the CCAI service provider, using Mistral&apos;s services
	// <a href="https://mistral.ai/">Mistral</a>
	CcaiServiceProvider_CCAI_SERVICE_PROVIDER_MISTRAL CcaiServiceProvider = 13
	// DuckDuckGo Websearch API
	// <a href="https://duckduckgo.com/api">DuckDuckGo API</a>
	CcaiServiceProvider_CCAI_SERVICE_PROVIDER_DUCKDUCKGO CcaiServiceProvider = 14
	// Google PSE Websearch API
	// <a href="https://programmablesearchengine.google.com/">Google Programmable Search Engine</a>
	CcaiServiceProvider_CCAI_SERVICE_PROVIDER_GOOGLE_PSE CcaiServiceProvider = 15
	// Jina Websearch API
	// <a href="https://github.com/jina-ai/jina">Jina AI</a>
	CcaiServiceProvider_CCAI_SERVICE_PROVIDER_JINA CcaiServiceProvider = 16
	// Tavily Websearch API
	// <a href="https://tavily.com/">Tavily API</a>
	CcaiServiceProvider_CCAI_SERVICE_PROVIDER_TAVILY CcaiServiceProvider = 17
	// ElasticSearch vector database service
	// <a href="https://www.elastic.co/">ElasticSearch</a>
	CcaiServiceProvider_CCAI_SERVICE_PROVIDER_ELASTICSEARCH CcaiServiceProvider = 18
	// Milvus vector database service
	// <a href="https://milvus.io/">Milvus</a>
	CcaiServiceProvider_CCAI_SERVICE_PROVIDER_MILVUS CcaiServiceProvider = 19
	// Qdrant vector database service
	// <a href="https://qdrant.tech/">Qdrant</a>
	CcaiServiceProvider_CCAI_SERVICE_PROVIDER_QDRANT CcaiServiceProvider = 20
	// Chroma vector database service
	// <a href="https://github.com/chroma-core/chroma">ChromaDB</a>
	CcaiServiceProvider_CCAI_SERVICE_PROVIDER_CHROMA CcaiServiceProvider = 21
	// Google CCAI service provider
	// <a href="https://cloud.google.com/ai">Google Cloud AI</a>
	CcaiServiceProvider_CCAI_SERVICE_PROVIDER_GOOGLE CcaiServiceProvider = 22
	// Microsoft CCAI service provider
	// <a href="https://www.microsoft.com/en-us/ai">Microsoft AI</a>
	CcaiServiceProvider_CCAI_SERVICE_PROVIDER_MICROSOFT CcaiServiceProvider = 23
	// Deepgram as the CCAI service provider for speech processing
	// <a href="https://deepgram.com/">Deepgram</a>
	CcaiServiceProvider_CCAI_SERVICE_PROVIDER_DEEPGRAM CcaiServiceProvider = 24
	// ElevenLabs as the CCAI service provider for voice synthesis
	// <a href="https://elevenlabs.io/">ElevenLabs</a>
	CcaiServiceProvider_CCAI_SERVICE_PROVIDER_ELEVENLABS CcaiServiceProvider = 25
	// Hugging Face Text Generation Inference (TGI) as the CCAI service provider
	// <a href="https://github.com/huggingface/text-generation-inference">Text Generation Inference</a>
	CcaiServiceProvider_CCAI_SERVICE_PROVIDER_HUGGINGFACE_TGI CcaiServiceProvider = 26
	// Hugging Face Text Embedding Inference (TGE) as the CCAI service provider
	// <a href="https://github.com/huggingface/text-embeddings-inference">Text Embeddings Inference</a>
	CcaiServiceProvider_CCAI_SERVICE_PROVIDER_HUGGINGFACE_TGE CcaiServiceProvider = 27
	// Hugging Face SmolAgents as the CCAI service provider
	// <a href="https://github.com/huggingface/smolagents">SmolAgents</a>
	CcaiServiceProvider_CCAI_SERVICE_PROVIDER_HUGGINGFACE_SMOLAGENTS CcaiServiceProvider = 28
	// Google Agent Development Kit (ADK) as the CCAI service provider
	// <a href="https://google.github.io/adk-docs/">Google Agent Development Kit (ADK)</a>
	CcaiServiceProvider_CCAI_SERVICE_PROVIDER_GOOGLE_AGENT_DEVELOPMENT_KIT CcaiServiceProvider = 29
	// Model Context Protocol as the CCAI service provider, enabling integration with services following
	// the Model Context Protocol standard.
	// <a href="https://modelcontextprotocol.io/introduction">MCP</a>
	CcaiServiceProvider_CCAI_SERVICE_PROVIDER_MODEL_CONTEXT_PROTOCOL CcaiServiceProvider = 30
	// Opensearch as the CCAI service provider, enabling integration with Opensearch vector database and search services
	// <a href="https://opensearch.org/">Opensearch</a>
	CcaiServiceProvider_CCAI_SERVICE_PROVIDER_OPENSEARCH CcaiServiceProvider = 31
	// Grok as the CCAI service provider, commonly used for models such as Grok-1
	// <a href="https://grok.x.ai/">Grok</a>
	CcaiServiceProvider_CCAI_SERVICE_PROVIDER_GROK CcaiServiceProvider = 32
	// PostgreSQL as the CCAI service provider, enabling integration with PostgreSQL databases
	// <a href="https://www.postgresql.org/">PostgreSQL</a>
	CcaiServiceProvider_CCAI_SERVICE_PROVIDER_POSTGRES CcaiServiceProvider = 33
	// Microsoft Agent Framework as the CCAI service provider
	// <a href="https://github.com/microsoft/agent-framework">Microsoft Agent Framework</a>
	CcaiServiceProvider_CCAI_SERVICE_PROVIDER_MICROSOFT_AGENT_FRAMEWORK CcaiServiceProvider = 34
)

// Enum value maps for CcaiServiceProvider.
var (
	CcaiServiceProvider_name = map[int32]string{
		0:  "NO_CCAI_SERVICE_PROVIDER",
		1:  "CCAI_SERVICE_PROVIDER_ONDEWO",
		2:  "CCAI_SERVICE_PROVIDER_GOOGLE_GEMINI",
		3:  "CCAI_SERVICE_PROVIDER_MICROSOFT_AZURE_OPENAI",
		4:  "CCAI_SERVICE_PROVIDER_MICROSOFT_AUTOGEN",
		5:  "CCAI_SERVICE_PROVIDER_OLLAMA",
		6:  "CCAI_SERVICE_PROVIDER_OPENAI",
		7:  "CCAI_SERVICE_PROVIDER_ANTHROPIC",
		8:  "CCAI_SERVICE_PROVIDER_HUGGINGFACE",
		9:  "CCAI_SERVICE_PROVIDER_IBM",
		10: "CCAI_SERVICE_PROVIDER_HAYSTACK",
		11: "CCAI_SERVICE_PROVIDER_LANGCHAIN",
		12: "CCAI_SERVICE_PROVIDER_AMAZON",
		13: "CCAI_SERVICE_PROVIDER_MISTRAL",
		14: "CCAI_SERVICE_PROVIDER_DUCKDUCKGO",
		15: "CCAI_SERVICE_PROVIDER_GOOGLE_PSE",
		16: "CCAI_SERVICE_PROVIDER_JINA",
		17: "CCAI_SERVICE_PROVIDER_TAVILY",
		18: "CCAI_SERVICE_PROVIDER_ELASTICSEARCH",
		19: "CCAI_SERVICE_PROVIDER_MILVUS",
		20: "CCAI_SERVICE_PROVIDER_QDRANT",
		21: "CCAI_SERVICE_PROVIDER_CHROMA",
		22: "CCAI_SERVICE_PROVIDER_GOOGLE",
		23: "CCAI_SERVICE_PROVIDER_MICROSOFT",
		24: "CCAI_SERVICE_PROVIDER_DEEPGRAM",
		25: "CCAI_SERVICE_PROVIDER_ELEVENLABS",
		26: "CCAI_SERVICE_PROVIDER_HUGGINGFACE_TGI",
		27: "CCAI_SERVICE_PROVIDER_HUGGINGFACE_TGE",
		28: "CCAI_SERVICE_PROVIDER_HUGGINGFACE_SMOLAGENTS",
		29: "CCAI_SERVICE_PROVIDER_GOOGLE_AGENT_DEVELOPMENT_KIT",
		30: "CCAI_SERVICE_PROVIDER_MODEL_CONTEXT_PROTOCOL",
		31: "CCAI_SERVICE_PROVIDER_OPENSEARCH",
		32: "CCAI_SERVICE_PROVIDER_GROK",
		33: "CCAI_SERVICE_PROVIDER_POSTGRES",
		34: "CCAI_SERVICE_PROVIDER_MICROSOFT_AGENT_FRAMEWORK",
	}
	CcaiServiceProvider_value = map[string]int32{
		"NO_CCAI_SERVICE_PROVIDER":                           0,
		"CCAI_SERVICE_PROVIDER_ONDEWO":                       1,
		"CCAI_SERVICE_PROVIDER_GOOGLE_GEMINI":                2,
		"CCAI_SERVICE_PROVIDER_MICROSOFT_AZURE_OPENAI":       3,
		"CCAI_SERVICE_PROVIDER_MICROSOFT_AUTOGEN":            4,
		"CCAI_SERVICE_PROVIDER_OLLAMA":                       5,
		"CCAI_SERVICE_PROVIDER_OPENAI":                       6,
		"CCAI_SERVICE_PROVIDER_ANTHROPIC":                    7,
		"CCAI_SERVICE_PROVIDER_HUGGINGFACE":                  8,
		"CCAI_SERVICE_PROVIDER_IBM":                          9,
		"CCAI_SERVICE_PROVIDER_HAYSTACK":                     10,
		"CCAI_SERVICE_PROVIDER_LANGCHAIN":                    11,
		"CCAI_SERVICE_PROVIDER_AMAZON":                       12,
		"CCAI_SERVICE_PROVIDER_MISTRAL":                      13,
		"CCAI_SERVICE_PROVIDER_DUCKDUCKGO":                   14,
		"CCAI_SERVICE_PROVIDER_GOOGLE_PSE":                   15,
		"CCAI_SERVICE_PROVIDER_JINA":                         16,
		"CCAI_SERVICE_PROVIDER_TAVILY":                       17,
		"CCAI_SERVICE_PROVIDER_ELASTICSEARCH":                18,
		"CCAI_SERVICE_PROVIDER_MILVUS":                       19,
		"CCAI_SERVICE_PROVIDER_QDRANT":                       20,
		"CCAI_SERVICE_PROVIDER_CHROMA":                       21,
		"CCAI_SERVICE_PROVIDER_GOOGLE":                       22,
		"CCAI_SERVICE_PROVIDER_MICROSOFT":                    23,
		"CCAI_SERVICE_PROVIDER_DEEPGRAM":                     24,
		"CCAI_SERVICE_PROVIDER_ELEVENLABS":                   25,
		"CCAI_SERVICE_PROVIDER_HUGGINGFACE_TGI":              26,
		"CCAI_SERVICE_PROVIDER_HUGGINGFACE_TGE":              27,
		"CCAI_SERVICE_PROVIDER_HUGGINGFACE_SMOLAGENTS":       28,
		"CCAI_SERVICE_PROVIDER_GOOGLE_AGENT_DEVELOPMENT_KIT": 29,
		"CCAI_SERVICE_PROVIDER_MODEL_CONTEXT_PROTOCOL":       30,
		"CCAI_SERVICE_PROVIDER_OPENSEARCH":                   31,
		"CCAI_SERVICE_PROVIDER_GROK":                         32,
		"CCAI_SERVICE_PROVIDER_POSTGRES":                     33,
		"CCAI_SERVICE_PROVIDER_MICROSOFT_AGENT_FRAMEWORK":    34,
	}
)

func (x CcaiServiceProvider) Enum() *CcaiServiceProvider {
	p := new(CcaiServiceProvider)
	*p = x
	return p
}

func (x CcaiServiceProvider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CcaiServiceProvider) Descriptor() protoreflect.EnumDescriptor {
	return file_ondewo_nlu_ccai_project_proto_enumTypes[2].Descriptor()
}

func (CcaiServiceProvider) Type() protoreflect.EnumType {
	return &file_ondewo_nlu_ccai_project_proto_enumTypes[2]
}

func (x CcaiServiceProvider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CcaiServiceProvider.Descriptor instead.
func (CcaiServiceProvider) EnumDescriptor() ([]byte, []int) {
	return file_ondewo_nlu_ccai_project_proto_rawDescGZIP(), []int{2}
}

// CcaiProjectView defines what the CcaiProject message contains
type CcaiProjectView int32

const (
	// Unspecified CCAI_PROJECT view: the view is defined by the call:
	CcaiProjectView_CCAI_PROJECT_VIEW_UNSPECIFIED CcaiProjectView = 0
	// Full CCAI_PROJECT view: populate all the fields of the CCAI_PROJECT message including configs.
	CcaiProjectView_CCAI_PROJECT_VIEW_FULL CcaiProjectView = 1
	// Shallow CCAI_PROJECT view: populates all the fields except configs.
	CcaiProjectView_CCAI_PROJECT_VIEW_SHALLOW CcaiProjectView = 2
	// Minimum view including only CCAI_PROJECT UUID and CCAI_PROJECT display name
	CcaiProjectView_CCAI_PROJECT_VIEW_MINIMUM CcaiProjectView = 3
)

// Enum value maps for CcaiProjectView.
var (
	CcaiProjectView_name = map[int32]string{
		0: "CCAI_PROJECT_VIEW_UNSPECIFIED",
		1: "CCAI_PROJECT_VIEW_FULL",
		2: "CCAI_PROJECT_VIEW_SHALLOW",
		3: "CCAI_PROJECT_VIEW_MINIMUM",
	}
	CcaiProjectView_value = map[string]int32{
		"CCAI_PROJECT_VIEW_UNSPECIFIED": 0,
		"CCAI_PROJECT_VIEW_FULL":        1,
		"CCAI_PROJECT_VIEW_SHALLOW":     2,
		"CCAI_PROJECT_VIEW_MINIMUM":     3,
	}
)

func (x CcaiProjectView) Enum() *CcaiProjectView {
	p := new(CcaiProjectView)
	*p = x
	return p
}

func (x CcaiProjectView) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CcaiProjectView) Descriptor() protoreflect.EnumDescriptor {
	return file_ondewo_nlu_ccai_project_proto_enumTypes[3].Descriptor()
}

func (CcaiProjectView) Type() protoreflect.EnumType {
	return &file_ondewo_nlu_ccai_project_proto_enumTypes[3]
}

func (x CcaiProjectView) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CcaiProjectView.Descriptor instead.
func (CcaiProjectView) EnumDescriptor() ([]byte, []int) {
	return file_ondewo_nlu_ccai_project_proto_rawDescGZIP(), []int{3}
}

// Enum to specify the sorting field for CCAI service projects.
type CcaiProjectSorting_CcaiProjectSortingField int32

const (
	// No sorting
	CcaiProjectSorting_NO_CCAI_PROJECT_SORTING CcaiProjectSorting_CcaiProjectSortingField = 0
	// Sort by project name such as <pre><code>projects/&lt;project_uuid&gt;/project</code></pre>
	CcaiProjectSorting_SORT_CCAI_PROJECT_BY_NAME CcaiProjectSorting_CcaiProjectSortingField = 1
	// Sort by display name
	CcaiProjectSorting_SORT_CCAI_PROJECT_BY_DISPLAY_NAME CcaiProjectSorting_CcaiProjectSortingField = 2
	// Sort by creation date
	CcaiProjectSorting_SORT_CCAI_PROJECT_BY_CREATION_DATE CcaiProjectSorting_CcaiProjectSortingField = 3
	// Sort by last modified date
	CcaiProjectSorting_SORT_CCAI_PROJECT_BY_LAST_MODIFIED CcaiProjectSorting_CcaiProjectSortingField = 4
)

// Enum value maps for CcaiProjectSorting_CcaiProjectSortingField.
var (
	CcaiProjectSorting_CcaiProjectSortingField_name = map[int32]string{
		0: "NO_CCAI_PROJECT_SORTING",
		1: "SORT_CCAI_PROJECT_BY_NAME",
		2: "SORT_CCAI_PROJECT_BY_DISPLAY_NAME",
		3: "SORT_CCAI_PROJECT_BY_CREATION_DATE",
		4: "SORT_CCAI_PROJECT_BY_LAST_MODIFIED",
	}
	CcaiProjectSorting_CcaiProjectSortingField_value = map[string]int32{
		"NO_CCAI_PROJECT_SORTING":            0,
		"SORT_CCAI_PROJECT_BY_NAME":          1,
		"SORT_CCAI_PROJECT_BY_DISPLAY_NAME":  2,
		"SORT_CCAI_PROJECT_BY_CREATION_DATE": 3,
		"SORT_CCAI_PROJECT_BY_LAST_MODIFIED": 4,
	}
)

func (x CcaiProjectSorting_CcaiProjectSortingField) Enum() *CcaiProjectSorting_CcaiProjectSortingField {
	p := new(CcaiProjectSorting_CcaiProjectSortingField)
	*p = x
	return p
}

func (x CcaiProjectSorting_CcaiProjectSortingField) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CcaiProjectSorting_CcaiProjectSortingField) Descriptor() protoreflect.EnumDescriptor {
	return file_ondewo_nlu_ccai_project_proto_enumTypes[4].Descriptor()
}

func (CcaiProjectSorting_CcaiProjectSortingField) Type() protoreflect.EnumType {
	return &file_ondewo_nlu_ccai_project_proto_enumTypes[4]
}

func (x CcaiProjectSorting_CcaiProjectSortingField) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CcaiProjectSorting_CcaiProjectSortingField.Descriptor instead.
func (CcaiProjectSorting_CcaiProjectSortingField) EnumDescriptor() ([]byte, []int) {
	return file_ondewo_nlu_ccai_project_proto_rawDescGZIP(), []int{9, 0}
}

// Message representing a CCAI service project
type CcaiProject struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource name of the CCAI service project
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Required. The display name of this ccai project.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Optional. Resource name of the user who is the owner of the project.
	OwnerName string `protobuf:"bytes,3,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
	// Map of two letter language codes to lists of CcaiServiceList
	// Two-letter language codes following ISO 639-1 (see <a href="https://en.wikipedia.org/wiki/ISO_639-1">https://en.wikipedia.org/wiki/ISO_639-1</a>)
	CcaiServicesMap map[string]*CcaiServiceList `protobuf:"bytes,4,rep,name=ccai_services_map,json=ccaiServicesMap,proto3" json:"ccai_services_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The status of the ccai project.
	CcaiProjectStatus CcaiProjectStatus `protobuf:"varint,5,opt,name=ccai_project_status,json=ccaiProjectStatus,proto3,enum=ondewo.nlu.CcaiProjectStatus" json:"ccai_project_status,omitempty"`
	// Creation date and time. Read-only field.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Modification date and time. Read-only field.
	ModifiedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=modified_at,json=modifiedAt,proto3" json:"modified_at,omitempty"`
	// User id in the form of a valid UUID.
	CreatedBy string `protobuf:"bytes,8,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	// User id in the form of a valid UUID.
	ModifiedBy string `protobuf:"bytes,9,opt,name=modified_by,json=modifiedBy,proto3" json:"modified_by,omitempty"`
	// Required. Associated NLU agent
	// Format: <pre><code>projects/&lt;project_uuid&gt;/agent</code></pre>
	NluProjectName string `protobuf:"bytes,10,opt,name=nlu_project_name,json=nluProjectName,proto3" json:"nlu_project_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CcaiProject) Reset() {
	*x = CcaiProject{}
	mi := &file_ondewo_nlu_ccai_project_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CcaiProject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CcaiProject) ProtoMessage() {}

func (x *CcaiProject) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_nlu_ccai_project_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CcaiProject.ProtoReflect.Descriptor instead.
func (*CcaiProject) Descriptor() ([]byte, []int) {
	return file_ondewo_nlu_ccai_project_proto_rawDescGZIP(), []int{0}
}

func (x *CcaiProject) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CcaiProject) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CcaiProject) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

func (x *CcaiProject) GetCcaiServicesMap() map[string]*CcaiServiceList {
	if x != nil {
		return x.CcaiServicesMap
	}
	return nil
}

func (x *CcaiProject) GetCcaiProjectStatus() CcaiProjectStatus {
	if x != nil {
		return x.CcaiProjectStatus
	}
	return CcaiProjectStatus_CCAI_PROJECT_STATUS_UNSPECIFIED
}

func (x *CcaiProject) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CcaiProject) GetModifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ModifiedAt
	}
	return nil
}

func (x *CcaiProject) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *CcaiProject) GetModifiedBy() string {
	if x != nil {
		return x.ModifiedBy
	}
	return ""
}

func (x *CcaiProject) GetNluProjectName() string {
	if x != nil {
		return x.NluProjectName
	}
	return ""
}

// Message representing a list of CCAI service services
type CcaiServiceList struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CCAI service services
	CcaiServices  []*CcaiService `protobuf:"bytes,1,rep,name=ccai_services,json=ccaiServices,proto3" json:"ccai_services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CcaiServiceList) Reset() {
	*x = CcaiServiceList{}
	mi := &file_ondewo_nlu_ccai_project_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CcaiServiceList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CcaiServiceList) ProtoMessage() {}

func (x *CcaiServiceList) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_nlu_ccai_project_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CcaiServiceList.ProtoReflect.Descriptor instead.
func (*CcaiServiceList) Descriptor() ([]byte, []int) {
	return file_ondewo_nlu_ccai_project_proto_rawDescGZIP(), []int{1}
}

func (x *CcaiServiceList) GetCcaiServices() []*CcaiService {
	if x != nil {
		return x.CcaiServices
	}
	return nil
}

// Definition of a Call Center AI (CCAI service) Service.
type CcaiService struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource name of the service. Must be unique.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Display name for better identification.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Language code representing the service language
	// Format (e.g., "en" for English, "de" for German).
	LanguageCode string `protobuf:"bytes,3,opt,name=language_code,json=languageCode,proto3" json:"language_code,omitempty"`
	// gRPC host for communication with the specified port.
	GrpcHost string `protobuf:"bytes,4,opt,name=grpc_host,json=grpcHost,proto3" json:"grpc_host,omitempty"`
	// Port for gRPC communication.
	GrpcPort int32 `protobuf:"varint,5,opt,name=grpc_port,json=grpcPort,proto3" json:"grpc_port,omitempty"`
	// Web gRPC host for web-based communication with the specified port.
	WebgrpcHost string `protobuf:"bytes,6,opt,name=webgrpc_host,json=webgrpcHost,proto3" json:"webgrpc_host,omitempty"`
	// Port for web gRPC communication.
	WebgrpcPort int32 `protobuf:"varint,7,opt,name=webgrpc_port,json=webgrpcPort,proto3" json:"webgrpc_port,omitempty"`
	// Path to the gRPC certificate for secure communication.
	GrpcCert string `protobuf:"bytes,8,opt,name=grpc_cert,json=grpcCert,proto3" json:"grpc_cert,omitempty"`
	// Additional host for communication, if needed.
	Host string `protobuf:"bytes,9,opt,name=host,proto3" json:"host,omitempty"`
	// Port for additional communication.
	Port int32 `protobuf:"varint,10,opt,name=port,proto3" json:"port,omitempty"`
	// Another additional port for communication if required.
	Port2 int32 `protobuf:"varint,11,opt,name=port2,proto3" json:"port2,omitempty"`
	// Http basic auth token
	HttpBasicAuthToken string `protobuf:"bytes,12,opt,name=http_basic_auth_token,json=httpBasicAuthToken,proto3" json:"http_basic_auth_token,omitempty"`
	// Account name for authentication.
	AccountName string `protobuf:"bytes,13,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	// Password for the specified account for authentication.
	AccountPassword string `protobuf:"bytes,14,opt,name=account_password,json=accountPassword,proto3" json:"account_password,omitempty"`
	// API key for accessing the service, if applicable.
	ApiKey string `protobuf:"bytes,15,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	// Type of CCAI service service (e.g., TEXT_TO_SPEECH, SPEECH_TO_TEXT).
	CcaiServiceType CcaiServiceType `protobuf:"varint,16,opt,name=ccai_service_type,json=ccaiServiceType,proto3,enum=ondewo.nlu.CcaiServiceType" json:"ccai_service_type,omitempty"`
	// Resource name of the ccai_project the ccai_service belongs to
	CcaiProjectName string `protobuf:"bytes,17,opt,name=ccai_project_name,json=ccaiProjectName,proto3" json:"ccai_project_name,omitempty"`
	// Detailed configuration of the CcaiService
	CcaiServiceConfig *structpb.Struct `protobuf:"bytes,18,opt,name=ccai_service_config,json=ccaiServiceConfig,proto3" json:"ccai_service_config,omitempty"`
	// Creation date and time of the service. Read-only field.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,19,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Modification date and time of the service. Read-only field.
	ModifiedAt *timestamppb.Timestamp `protobuf:"bytes,20,opt,name=modified_at,json=modifiedAt,proto3" json:"modified_at,omitempty"`
	// User ID of the creator in the form of a valid UUID. Read-only field.
	CreatedBy string `protobuf:"bytes,21,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	// User ID of the last modifier in the form of a valid UUID. Read-only field.
	ModifiedBy string `protobuf:"bytes,22,opt,name=modified_by,json=modifiedBy,proto3" json:"modified_by,omitempty"`
	// Optional. The headers of the request message
	Headers *structpb.Struct `protobuf:"bytes,23,opt,name=headers,proto3" json:"headers,omitempty"`
	// Provider of the ccai service
	CcaiServiceProvider CcaiServiceProvider `protobuf:"varint,24,opt,name=ccai_service_provider,json=ccaiServiceProvider,proto3,enum=ondewo.nlu.CcaiServiceProvider" json:"ccai_service_provider,omitempty"`
	// Index indicating the hierarchical position of a service within the service hierarchy.
	// The index follows a tree-like structure, where each level of depth is separated by a &quot;_&quot;.
	// For example:
	// <ul>
	//   <li>&quot;1&quot; represents a top-level service</li>
	//   <li>&quot;1_1&quot; represents a sub-service under &quot;1&quot;</li>
	//   <li>&quot;1_1_1&quot; represents a sub-service under &quot;1.1&quot;</li>
	// </ul>
	// This structure allows for easy representation and organization of services in nested workflows.
	//
	// If CcaiService have the same service_hierarchy they are executed in parallel.
	// For example:
	// <ul>
	//   <li>&quot;1&quot; Service A</li>
	//   <li>&quot;1_1&quot; Service B</li>
	//   <li>&quot;1_1&quot; Service C</li>
	// </ul>
	//
	// Service B and C will be executed in parallel and the Service A receives both results of service B and C.
	// The variable for the return value of a service is {{OUTPUT_SERVICE_service_hierarchy}}. So in the example
	// above the outputs of the services are {{OUTPUT_SERVICE_1}}, {{OUTPUT_SERVICE_1_1}}, and {{OUTPUT_SERVICE_1_2}}.
	ServiceHierarchy string `protobuf:"bytes,25,opt,name=service_hierarchy,json=serviceHierarchy,proto3" json:"service_hierarchy,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CcaiService) Reset() {
	*x = CcaiService{}
	mi := &file_ondewo_nlu_ccai_project_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CcaiService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CcaiService) ProtoMessage() {}

func (x *CcaiService) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_nlu_ccai_project_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CcaiService.ProtoReflect.Descriptor instead.
func (*CcaiService) Descriptor() ([]byte, []int) {
	return file_ondewo_nlu_ccai_project_proto_rawDescGZIP(), []int{2}
}

func (x *CcaiService) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CcaiService) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CcaiService) GetLanguageCode() string {
	if x != nil {
		return x.LanguageCode
	}
	return ""
}

func (x *CcaiService) GetGrpcHost() string {
	if x != nil {
		return x.GrpcHost
	}
	return ""
}

func (x *CcaiService) GetGrpcPort() int32 {
	if x != nil {
		return x.GrpcPort
	}
	return 0
}

func (x *CcaiService) GetWebgrpcHost() string {
	if x != nil {
		return x.WebgrpcHost
	}
	return ""
}

func (x *CcaiService) GetWebgrpcPort() int32 {
	if x != nil {
		return x.WebgrpcPort
	}
	return 0
}

func (x *CcaiService) GetGrpcCert() string {
	if x != nil {
		return x.GrpcCert
	}
	return ""
}

func (x *CcaiService) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *CcaiService) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *CcaiService) GetPort2() int32 {
	if x != nil {
		return x.Port2
	}
	return 0
}

func (x *CcaiService) GetHttpBasicAuthToken() string {
	if x != nil {
		return x.HttpBasicAuthToken
	}
	return ""
}

func (x *CcaiService) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *CcaiService) GetAccountPassword() string {
	if x != nil {
		return x.AccountPassword
	}
	return ""
}

func (x *CcaiService) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *CcaiService) GetCcaiServiceType() CcaiServiceType {
	if x != nil {
		return x.CcaiServiceType
	}
	return CcaiServiceType_CCAI_SERVICE_TYPE_UNSPECIFIED
}

func (x *CcaiService) GetCcaiProjectName() string {
	if x != nil {
		return x.CcaiProjectName
	}
	return ""
}

func (x *CcaiService) GetCcaiServiceConfig() *structpb.Struct {
	if x != nil {
		return x.CcaiServiceConfig
	}
	return nil
}

func (x *CcaiService) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CcaiService) GetModifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ModifiedAt
	}
	return nil
}

func (x *CcaiService) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *CcaiService) GetModifiedBy() string {
	if x != nil {
		return x.ModifiedBy
	}
	return ""
}

func (x *CcaiService) GetHeaders() *structpb.Struct {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *CcaiService) GetCcaiServiceProvider() CcaiServiceProvider {
	if x != nil {
		return x.CcaiServiceProvider
	}
	return CcaiServiceProvider_NO_CCAI_SERVICE_PROVIDER
}

func (x *CcaiService) GetServiceHierarchy() string {
	if x != nil {
		return x.ServiceHierarchy
	}
	return ""
}

// Request to create a Call Center AI (CCAI service) project.
type CreateCcaiProjectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The CCAI service project to be created.
	CcaiProject *CcaiProject `protobuf:"bytes,1,opt,name=ccai_project,json=ccaiProject,proto3" json:"ccai_project,omitempty"`
	// Required. The nlu agent project of this CcaiProject.
	// Format: <pre><code>projects/&lt;project_uuid&gt;/agent</code></pre>
	NluProjectName string `protobuf:"bytes,4,opt,name=nlu_project_name,json=nluProjectName,proto3" json:"nlu_project_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateCcaiProjectRequest) Reset() {
	*x = CreateCcaiProjectRequest{}
	mi := &file_ondewo_nlu_ccai_project_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCcaiProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCcaiProjectRequest) ProtoMessage() {}

func (x *CreateCcaiProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_nlu_ccai_project_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCcaiProjectRequest.ProtoReflect.Descriptor instead.
func (*CreateCcaiProjectRequest) Descriptor() ([]byte, []int) {
	return file_ondewo_nlu_ccai_project_proto_rawDescGZIP(), []int{3}
}

func (x *CreateCcaiProjectRequest) GetCcaiProject() *CcaiProject {
	if x != nil {
		return x.CcaiProject
	}
	return nil
}

func (x *CreateCcaiProjectRequest) GetNluProjectName() string {
	if x != nil {
		return x.NluProjectName
	}
	return ""
}

// Response after attempting to create a Call Center AI (CCAI service) project.
type CreateCcaiProjectResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The created CCAI service project.
	CcaiProject *CcaiProject `protobuf:"bytes,1,opt,name=ccai_project,json=ccaiProject,proto3" json:"ccai_project,omitempty"`
	// Error message if the creation is unsuccessful.
	ErrorMessage  string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCcaiProjectResponse) Reset() {
	*x = CreateCcaiProjectResponse{}
	mi := &file_ondewo_nlu_ccai_project_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCcaiProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCcaiProjectResponse) ProtoMessage() {}

func (x *CreateCcaiProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_nlu_ccai_project_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCcaiProjectResponse.ProtoReflect.Descriptor instead.
func (*CreateCcaiProjectResponse) Descriptor() ([]byte, []int) {
	return file_ondewo_nlu_ccai_project_proto_rawDescGZIP(), []int{4}
}

func (x *CreateCcaiProjectResponse) GetCcaiProject() *CcaiProject {
	if x != nil {
		return x.CcaiProject
	}
	return nil
}

func (x *CreateCcaiProjectResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Request to retrieve a CCAI service project
type GetCcaiProjectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CCAI service project name with which to perform the call of the form <pre><code>projects/&lt;project_uuid&gt;/project</code></pre>
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Optional. Specify the view of the returned CcaiProject (full view by default)
	CcaiProjectView CcaiProjectView `protobuf:"varint,2,opt,name=ccai_project_view,json=ccaiProjectView,proto3,enum=ondewo.nlu.CcaiProjectView" json:"ccai_project_view,omitempty"`
	// Filter which services should be included in the returned CcaiProject
	CcaiServiceFilter *CcaiServiceFilter `protobuf:"bytes,3,opt,name=ccai_service_filter,json=ccaiServiceFilter,proto3" json:"ccai_service_filter,omitempty"`
	// Required. The nlu agent project of this CcaiProject.
	// Format: <pre><code>projects/&lt;project_uuid&gt;/agent</code></pre>
	NluProjectName string `protobuf:"bytes,4,opt,name=nlu_project_name,json=nluProjectName,proto3" json:"nlu_project_name,omitempty"`
	// Optional. The mask to control which fields gets returned.
	FieldMask     *fieldmaskpb.FieldMask `protobuf:"bytes,5,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCcaiProjectRequest) Reset() {
	*x = GetCcaiProjectRequest{}
	mi := &file_ondewo_nlu_ccai_project_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCcaiProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCcaiProjectRequest) ProtoMessage() {}

func (x *GetCcaiProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_nlu_ccai_project_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCcaiProjectRequest.ProtoReflect.Descriptor instead.
func (*GetCcaiProjectRequest) Descriptor() ([]byte, []int) {
	return file_ondewo_nlu_ccai_project_proto_rawDescGZIP(), []int{5}
}

func (x *GetCcaiProjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetCcaiProjectRequest) GetCcaiProjectView() CcaiProjectView {
	if x != nil {
		return x.CcaiProjectView
	}
	return CcaiProjectView_CCAI_PROJECT_VIEW_UNSPECIFIED
}

func (x *GetCcaiProjectRequest) GetCcaiServiceFilter() *CcaiServiceFilter {
	if x != nil {
		return x.CcaiServiceFilter
	}
	return nil
}

func (x *GetCcaiProjectRequest) GetNluProjectName() string {
	if x != nil {
		return x.NluProjectName
	}
	return ""
}

func (x *GetCcaiProjectRequest) GetFieldMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.FieldMask
	}
	return nil
}

// Request to retrieve a CCAI service project
type GetCcaiServiceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CCAI service project name with which to perform the call of the form
	// <pre><code>projects/&lt;project_uuid&gt;/ccai/services/&lt;service_uuid&gt;</code></pre>
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Required. The nlu agent project of this CcaiProject.
	// Format: <pre><code>projects/&lt;project_uuid&gt;/agent</code></pre>
	NluProjectName string `protobuf:"bytes,4,opt,name=nlu_project_name,json=nluProjectName,proto3" json:"nlu_project_name,omitempty"`
	// Optional. The mask to control which fields gets returned.
	FieldMask     *fieldmaskpb.FieldMask `protobuf:"bytes,5,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCcaiServiceRequest) Reset() {
	*x = GetCcaiServiceRequest{}
	mi := &file_ondewo_nlu_ccai_project_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCcaiServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCcaiServiceRequest) ProtoMessage() {}

func (x *GetCcaiServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_nlu_ccai_project_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCcaiServiceRequest.ProtoReflect.Descriptor instead.
func (*GetCcaiServiceRequest) Descriptor() ([]byte, []int) {
	return file_ondewo_nlu_ccai_project_proto_rawDescGZIP(), []int{6}
}

func (x *GetCcaiServiceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetCcaiServiceRequest) GetNluProjectName() string {
	if x != nil {
		return x.NluProjectName
	}
	return ""
}

func (x *GetCcaiServiceRequest) GetFieldMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.FieldMask
	}
	return nil
}

// Request to get the list of agents
type ListCcaiProjectsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional. Specify the view of the returned CcaiProject (full view by default)
	CcaiProjectView CcaiProjectView `protobuf:"varint,1,opt,name=ccai_project_view,json=ccaiProjectView,proto3,enum=ondewo.nlu.CcaiProjectView" json:"ccai_project_view,omitempty"`
	// Filter which services should be included in the CcaiProject
	CcaiServiceFilter *CcaiServiceFilter `protobuf:"bytes,2,opt,name=ccai_service_filter,json=ccaiServiceFilter,proto3" json:"ccai_service_filter,omitempty"`
	// Optional. Field to define the sorting of the list of CCAI service projects in the response.
	// If not specified, the default behavior is to have no sorting.
	CcaiProjectSorting *CcaiProjectSorting `protobuf:"bytes,3,opt,name=ccai_project_sorting,json=ccaiProjectSorting,proto3" json:"ccai_project_sorting,omitempty"`
	// Optional. The next_page_token value returned from a previous list request.
	// Example: &quot;current_index-1--page_size-20&quot;
	// The page token to support pagination.
	// Pagination allows you to retrieve a large result set in smaller, more manageable portions.
	// The page token is a string representing the current index and page size.
	//
	// Valid page token strings:
	// <ul>
	//   <li>&quot;&quot; (empty string) - Retrieves the first page.</li>
	//   <li>&quot;current_index-0--page_size-20&quot; - Retrieves the first page with a page size of 20.</li>
	//   <li>&quot;current_index-1--page_size-20&quot; - Retrieves the second page with a page size of 20.</li>
	// </ul>
	//
	// Index starts at 0.
	//
	// Examples of valid page token strings:
	// <ul>
	//   <li>&quot;&quot;</li>
	//   <li>&quot;current_index-0--page_size-20&quot;</li>
	//   <li>&quot;current_index-1--page_size-20&quot;</li>
	//   <li>&quot;current_index-10--page_size-20&quot;</li>
	// </ul>
	//
	// Examples of invalid page token strings:
	// <ul>
	//   <li>&quot;1&quot;</li>
	//   <li>&quot;current_index-0--page_size-20&quot;</li>
	//   <li>&quot;current_index--1--page_size-20&quot;</li>
	//   <li>&quot;current_index1--page_size-20&quot;</li>
	//   <li>&quot;current_index-1--page_size--20&quot;</li>
	// </ul>
	PageToken string `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Required. The nlu agent project of this CcaiProject.
	// Format: <pre><code>projects/&lt;project_uuid&gt;/agent</code></pre>
	NluProjectName string `protobuf:"bytes,5,opt,name=nlu_project_name,json=nluProjectName,proto3" json:"nlu_project_name,omitempty"`
	// Optional. The mask to control which fields gets returned.
	FieldMask     *fieldmaskpb.FieldMask `protobuf:"bytes,6,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCcaiProjectsRequest) Reset() {
	*x = ListCcaiProjectsRequest{}
	mi := &file_ondewo_nlu_ccai_project_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCcaiProjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCcaiProjectsRequest) ProtoMessage() {}

func (x *ListCcaiProjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_nlu_ccai_project_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCcaiProjectsRequest.ProtoReflect.Descriptor instead.
func (*ListCcaiProjectsRequest) Descriptor() ([]byte, []int) {
	return file_ondewo_nlu_ccai_project_proto_rawDescGZIP(), []int{7}
}

func (x *ListCcaiProjectsRequest) GetCcaiProjectView() CcaiProjectView {
	if x != nil {
		return x.CcaiProjectView
	}
	return CcaiProjectView_CCAI_PROJECT_VIEW_UNSPECIFIED
}

func (x *ListCcaiProjectsRequest) GetCcaiServiceFilter() *CcaiServiceFilter {
	if x != nil {
		return x.CcaiServiceFilter
	}
	return nil
}

func (x *ListCcaiProjectsRequest) GetCcaiProjectSorting() *CcaiProjectSorting {
	if x != nil {
		return x.CcaiProjectSorting
	}
	return nil
}

func (x *ListCcaiProjectsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListCcaiProjectsRequest) GetNluProjectName() string {
	if x != nil {
		return x.NluProjectName
	}
	return ""
}

func (x *ListCcaiProjectsRequest) GetFieldMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.FieldMask
	}
	return nil
}

// This is a protobuf message definition for the response of getting a list of CCAI service projects.
type ListCcaiProjectsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of CCAI service projects returned in the response.
	// Use the 'repeated' keyword to indicate that this field can contain multiple instances of CcaiProject.
	CcaiProjects []*CcaiProject `protobuf:"bytes,1,rep,name=ccai_projects,json=ccaiProjects,proto3" json:"ccai_projects,omitempty"`
	// The next_page_token is used to retrieve the next page of a returned result,
	// e.g. next_page_token is current_index-2
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCcaiProjectsResponse) Reset() {
	*x = ListCcaiProjectsResponse{}
	mi := &file_ondewo_nlu_ccai_project_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCcaiProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCcaiProjectsResponse) ProtoMessage() {}

func (x *ListCcaiProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_nlu_ccai_project_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCcaiProjectsResponse.ProtoReflect.Descriptor instead.
func (*ListCcaiProjectsResponse) Descriptor() ([]byte, []int) {
	return file_ondewo_nlu_ccai_project_proto_rawDescGZIP(), []int{8}
}

func (x *ListCcaiProjectsResponse) GetCcaiProjects() []*CcaiProject {
	if x != nil {
		return x.CcaiProjects
	}
	return nil
}

func (x *ListCcaiProjectsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// This protobuf message defines the sorting order for CCAI service (VOIP Telephone System Integration) projects.
type CcaiProjectSorting struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// sorting field for ccai projects sorting
	SortingField CcaiProjectSorting_CcaiProjectSortingField `protobuf:"varint,1,opt,name=sorting_field,json=sortingField,proto3,enum=ondewo.nlu.CcaiProjectSorting_CcaiProjectSortingField" json:"sorting_field,omitempty"`
	// Sorting mode
	SortingMode   SortingMode `protobuf:"varint,2,opt,name=sorting_mode,json=sortingMode,proto3,enum=ondewo.nlu.SortingMode" json:"sorting_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CcaiProjectSorting) Reset() {
	*x = CcaiProjectSorting{}
	mi := &file_ondewo_nlu_ccai_project_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CcaiProjectSorting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CcaiProjectSorting) ProtoMessage() {}

func (x *CcaiProjectSorting) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_nlu_ccai_project_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CcaiProjectSorting.ProtoReflect.Descriptor instead.
func (*CcaiProjectSorting) Descriptor() ([]byte, []int) {
	return file_ondewo_nlu_ccai_project_proto_rawDescGZIP(), []int{9}
}

func (x *CcaiProjectSorting) GetSortingField() CcaiProjectSorting_CcaiProjectSortingField {
	if x != nil {
		return x.SortingField
	}
	return CcaiProjectSorting_NO_CCAI_PROJECT_SORTING
}

func (x *CcaiProjectSorting) GetSortingMode() SortingMode {
	if x != nil {
		return x.SortingMode
	}
	return SortingMode_ASCENDING
}

// Filter which services should be included in the returned CcaiProject
type CcaiServiceFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Language codes of the projects for which services are filtered.
	LanguageCodes []string `protobuf:"bytes,1,rep,name=language_codes,json=languageCodes,proto3" json:"language_codes,omitempty"`
	// Type of CCAI service service
	CcaiServiceTypes []CcaiServiceType `protobuf:"varint,2,rep,packed,name=ccai_service_types,json=ccaiServiceTypes,proto3,enum=ondewo.nlu.CcaiServiceType" json:"ccai_service_types,omitempty"`
	// Type of CCAI service providers
	CcaiServiceProviders []CcaiServiceProvider `protobuf:"varint,3,rep,packed,name=ccai_service_providers,json=ccaiServiceProviders,proto3,enum=ondewo.nlu.CcaiServiceProvider" json:"ccai_service_providers,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CcaiServiceFilter) Reset() {
	*x = CcaiServiceFilter{}
	mi := &file_ondewo_nlu_ccai_project_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CcaiServiceFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CcaiServiceFilter) ProtoMessage() {}

func (x *CcaiServiceFilter) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_nlu_ccai_project_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CcaiServiceFilter.ProtoReflect.Descriptor instead.
func (*CcaiServiceFilter) Descriptor() ([]byte, []int) {
	return file_ondewo_nlu_ccai_project_proto_rawDescGZIP(), []int{10}
}

func (x *CcaiServiceFilter) GetLanguageCodes() []string {
	if x != nil {
		return x.LanguageCodes
	}
	return nil
}

func (x *CcaiServiceFilter) GetCcaiServiceTypes() []CcaiServiceType {
	if x != nil {
		return x.CcaiServiceTypes
	}
	return nil
}

func (x *CcaiServiceFilter) GetCcaiServiceProviders() []CcaiServiceProvider {
	if x != nil {
		return x.CcaiServiceProviders
	}
	return nil
}

// Request to updated CCAI service project
type UpdateCcaiProjectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The CcaiProject that should be updated
	CcaiProject *CcaiProject `protobuf:"bytes,1,opt,name=ccai_project,json=ccaiProject,proto3" json:"ccai_project,omitempty"`
	// Filter which services should be updated in the CcaiProject
	CcaiServiceFilter *CcaiServiceFilter `protobuf:"bytes,2,opt,name=ccai_service_filter,json=ccaiServiceFilter,proto3" json:"ccai_service_filter,omitempty"`
	// Optional. The mask to control which fields get updated.
	UpdateMask *fieldmaskpb.FieldMask `protobuf:"bytes,3,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	// Required. The nlu agent project of this CcaiProject.
	// Format: <pre><code>projects/&lt;project_uuid&gt;/agent</code></pre>
	NluProjectName string `protobuf:"bytes,4,opt,name=nlu_project_name,json=nluProjectName,proto3" json:"nlu_project_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateCcaiProjectRequest) Reset() {
	*x = UpdateCcaiProjectRequest{}
	mi := &file_ondewo_nlu_ccai_project_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCcaiProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCcaiProjectRequest) ProtoMessage() {}

func (x *UpdateCcaiProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_nlu_ccai_project_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCcaiProjectRequest.ProtoReflect.Descriptor instead.
func (*UpdateCcaiProjectRequest) Descriptor() ([]byte, []int) {
	return file_ondewo_nlu_ccai_project_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateCcaiProjectRequest) GetCcaiProject() *CcaiProject {
	if x != nil {
		return x.CcaiProject
	}
	return nil
}

func (x *UpdateCcaiProjectRequest) GetCcaiServiceFilter() *CcaiServiceFilter {
	if x != nil {
		return x.CcaiServiceFilter
	}
	return nil
}

func (x *UpdateCcaiProjectRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

func (x *UpdateCcaiProjectRequest) GetNluProjectName() string {
	if x != nil {
		return x.NluProjectName
	}
	return ""
}

// Request to updated CCAI service project
type UpdateCcaiProjectResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CCAI service project name with which to perform the call of the form <pre><code>projects/&lt;project_uuid&gt;/project</code></pre>
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// error message if there are any.
	ErrorMessage  string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCcaiProjectResponse) Reset() {
	*x = UpdateCcaiProjectResponse{}
	mi := &file_ondewo_nlu_ccai_project_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCcaiProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCcaiProjectResponse) ProtoMessage() {}

func (x *UpdateCcaiProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_nlu_ccai_project_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCcaiProjectResponse.ProtoReflect.Descriptor instead.
func (*UpdateCcaiProjectResponse) Descriptor() ([]byte, []int) {
	return file_ondewo_nlu_ccai_project_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateCcaiProjectResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCcaiProjectResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Request to delete a CCAI service project
// If a deployed CCAI service project was deleted then it was undeployed beforehand automatically
type DeleteCcaiProjectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CCAI service project name with which to perform the call of the form <pre><code>projects/&lt;project_uuid&gt;/project</code></pre>
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Required. The nlu agent project of this CcaiProject.
	// Format: <pre><code>projects/&lt;project_uuid&gt;/agent</code></pre>
	NluProjectName string `protobuf:"bytes,4,opt,name=nlu_project_name,json=nluProjectName,proto3" json:"nlu_project_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteCcaiProjectRequest) Reset() {
	*x = DeleteCcaiProjectRequest{}
	mi := &file_ondewo_nlu_ccai_project_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCcaiProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCcaiProjectRequest) ProtoMessage() {}

func (x *DeleteCcaiProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_nlu_ccai_project_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCcaiProjectRequest.ProtoReflect.Descriptor instead.
func (*DeleteCcaiProjectRequest) Descriptor() ([]byte, []int) {
	return file_ondewo_nlu_ccai_project_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteCcaiProjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeleteCcaiProjectRequest) GetNluProjectName() string {
	if x != nil {
		return x.NluProjectName
	}
	return ""
}

// Response to delete a CCAI service project
// If a deployed CCAI service project was deleted then it was undeployed beforehand automatically
type DeleteCcaiProjectResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CCAI service project name with which to perform the call of the form <pre><code>projects/&lt;project_uuid&gt;/project</code></pre>
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// error message if there are any.
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Required. The nlu agent project of this CcaiProject.
	// Format: <pre><code>projects/&lt;project_uuid&gt;/agent</code></pre>
	NluProjectName string `protobuf:"bytes,4,opt,name=nlu_project_name,json=nluProjectName,proto3" json:"nlu_project_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteCcaiProjectResponse) Reset() {
	*x = DeleteCcaiProjectResponse{}
	mi := &file_ondewo_nlu_ccai_project_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCcaiProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCcaiProjectResponse) ProtoMessage() {}

func (x *DeleteCcaiProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_nlu_ccai_project_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCcaiProjectResponse.ProtoReflect.Descriptor instead.
func (*DeleteCcaiProjectResponse) Descriptor() ([]byte, []int) {
	return file_ondewo_nlu_ccai_project_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteCcaiProjectResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeleteCcaiProjectResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *DeleteCcaiProjectResponse) GetNluProjectName() string {
	if x != nil {
		return x.NluProjectName
	}
	return ""
}

var File_ondewo_nlu_ccai_project_proto protoreflect.FileDescriptor

const file_ondewo_nlu_ccai_project_proto_rawDesc = "" +
	"\n" +
	"\x1dondewo/nlu/ccai_project.proto\x12\n" +
	"ondewo.nlu\x1a google/protobuf/field_mask.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17ondewo/nlu/common.proto\"\xcf\x04\n" +
	"\vCcaiProject\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x1d\n" +
	"\n" +
	"owner_name\x18\x03 \x01(\tR\townerName\x12X\n" +
	"\x11ccai_services_map\x18\x04 \x03(\v2,.ondewo.nlu.CcaiProject.CcaiServicesMapEntryR\x0fccaiServicesMap\x12M\n" +
	"\x13ccai_project_status\x18\x05 \x01(\x0e2\x1d.ondewo.nlu.CcaiProjectStatusR\x11ccaiProjectStatus\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12;\n" +
	"\vmodified_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"modifiedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\b \x01(\tR\tcreatedBy\x12\x1f\n" +
	"\vmodified_by\x18\t \x01(\tR\n" +
	"modifiedBy\x12(\n" +
	"\x10nlu_project_name\x18\n" +
	" \x01(\tR\x0enluProjectName\x1a_\n" +
	"\x14CcaiServicesMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.ondewo.nlu.CcaiServiceListR\x05value:\x028\x01\"O\n" +
	"\x0fCcaiServiceList\x12<\n" +
	"\rccai_services\x18\x01 \x03(\v2\x17.ondewo.nlu.CcaiServiceR\fccaiServices\"\x89\b\n" +
	"\vCcaiService\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12#\n" +
	"\rlanguage_code\x18\x03 \x01(\tR\flanguageCode\x12\x1b\n" +
	"\tgrpc_host\x18\x04 \x01(\tR\bgrpcHost\x12\x1b\n" +
	"\tgrpc_port\x18\x05 \x01(\x05R\bgrpcPort\x12!\n" +
	"\fwebgrpc_host\x18\x06 \x01(\tR\vwebgrpcHost\x12!\n" +
	"\fwebgrpc_port\x18\a \x01(\x05R\vwebgrpcPort\x12\x1b\n" +
	"\tgrpc_cert\x18\b \x01(\tR\bgrpcCert\x12\x12\n" +
	"\x04host\x18\t \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\n" +
	" \x01(\x05R\x04port\x12\x14\n" +
	"\x05port2\x18\v \x01(\x05R\x05port2\x121\n" +
	"\x15http_basic_auth_token\x18\f \x01(\tR\x12httpBasicAuthToken\x12!\n" +
	"\faccount_name\x18\r \x01(\tR\vaccountName\x12)\n" +
	"\x10account_password\x18\x0e \x01(\tR\x0faccountPassword\x12\x17\n" +
	"\aapi_key\x18\x0f \x01(\tR\x06apiKey\x12G\n" +
	"\x11ccai_service_type\x18\x10 \x01(\x0e2\x1b.ondewo.nlu.CcaiServiceTypeR\x0fccaiServiceType\x12*\n" +
	"\x11ccai_project_name\x18\x11 \x01(\tR\x0fccaiProjectName\x12G\n" +
	"\x13ccai_service_config\x18\x12 \x01(\v2\x17.google.protobuf.StructR\x11ccaiServiceConfig\x129\n" +
	"\n" +
	"created_at\x18\x13 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12;\n" +
	"\vmodified_at\x18\x14 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"modifiedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\x15 \x01(\tR\tcreatedBy\x12\x1f\n" +
	"\vmodified_by\x18\x16 \x01(\tR\n" +
	"modifiedBy\x121\n" +
	"\aheaders\x18\x17 \x01(\v2\x17.google.protobuf.StructR\aheaders\x12S\n" +
	"\x15ccai_service_provider\x18\x18 \x01(\x0e2\x1f.ondewo.nlu.CcaiServiceProviderR\x13ccaiServiceProvider\x12+\n" +
	"\x11service_hierarchy\x18\x19 \x01(\tR\x10serviceHierarchy\"\x80\x01\n" +
	"\x18CreateCcaiProjectRequest\x12:\n" +
	"\fccai_project\x18\x01 \x01(\v2\x17.ondewo.nlu.CcaiProjectR\vccaiProject\x12(\n" +
	"\x10nlu_project_name\x18\x04 \x01(\tR\x0enluProjectName\"|\n" +
	"\x19CreateCcaiProjectResponse\x12:\n" +
	"\fccai_project\x18\x01 \x01(\v2\x17.ondewo.nlu.CcaiProjectR\vccaiProject\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\xa8\x02\n" +
	"\x15GetCcaiProjectRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12G\n" +
	"\x11ccai_project_view\x18\x02 \x01(\x0e2\x1b.ondewo.nlu.CcaiProjectViewR\x0fccaiProjectView\x12M\n" +
	"\x13ccai_service_filter\x18\x03 \x01(\v2\x1d.ondewo.nlu.CcaiServiceFilterR\x11ccaiServiceFilter\x12(\n" +
	"\x10nlu_project_name\x18\x04 \x01(\tR\x0enluProjectName\x129\n" +
	"\n" +
	"field_mask\x18\x05 \x01(\v2\x1a.google.protobuf.FieldMaskR\tfieldMask\"\x90\x01\n" +
	"\x15GetCcaiServiceRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12(\n" +
	"\x10nlu_project_name\x18\x04 \x01(\tR\x0enluProjectName\x129\n" +
	"\n" +
	"field_mask\x18\x05 \x01(\v2\x1a.google.protobuf.FieldMaskR\tfieldMask\"\x87\x03\n" +
	"\x17ListCcaiProjectsRequest\x12G\n" +
	"\x11ccai_project_view\x18\x01 \x01(\x0e2\x1b.ondewo.nlu.CcaiProjectViewR\x0fccaiProjectView\x12M\n" +
	"\x13ccai_service_filter\x18\x02 \x01(\v2\x1d.ondewo.nlu.CcaiServiceFilterR\x11ccaiServiceFilter\x12P\n" +
	"\x14ccai_project_sorting\x18\x03 \x01(\v2\x1e.ondewo.nlu.CcaiProjectSortingR\x12ccaiProjectSorting\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\x12(\n" +
	"\x10nlu_project_name\x18\x05 \x01(\tR\x0enluProjectName\x129\n" +
	"\n" +
	"field_mask\x18\x06 \x01(\v2\x1a.google.protobuf.FieldMaskR\tfieldMask\"\x80\x01\n" +
	"\x18ListCcaiProjectsResponse\x12<\n" +
	"\rccai_projects\x18\x01 \x03(\v2\x17.ondewo.nlu.CcaiProjectR\fccaiProjects\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xfc\x02\n" +
	"\x12CcaiProjectSorting\x12[\n" +
	"\rsorting_field\x18\x01 \x01(\x0e26.ondewo.nlu.CcaiProjectSorting.CcaiProjectSortingFieldR\fsortingField\x12:\n" +
	"\fsorting_mode\x18\x02 \x01(\x0e2\x17.ondewo.nlu.SortingModeR\vsortingMode\"\xcc\x01\n" +
	"\x17CcaiProjectSortingField\x12\x1b\n" +
	"\x17NO_CCAI_PROJECT_SORTING\x10\x00\x12\x1d\n" +
	"\x19SORT_CCAI_PROJECT_BY_NAME\x10\x01\x12%\n" +
	"!SORT_CCAI_PROJECT_BY_DISPLAY_NAME\x10\x02\x12&\n" +
	"\"SORT_CCAI_PROJECT_BY_CREATION_DATE\x10\x03\x12&\n" +
	"\"SORT_CCAI_PROJECT_BY_LAST_MODIFIED\x10\x04\"\xdc\x01\n" +
	"\x11CcaiServiceFilter\x12%\n" +
	"\x0elanguage_codes\x18\x01 \x03(\tR\rlanguageCodes\x12I\n" +
	"\x12ccai_service_types\x18\x02 \x03(\x0e2\x1b.ondewo.nlu.CcaiServiceTypeR\x10ccaiServiceTypes\x12U\n" +
	"\x16ccai_service_providers\x18\x03 \x03(\x0e2\x1f.ondewo.nlu.CcaiServiceProviderR\x14ccaiServiceProviders\"\x8c\x02\n" +
	"\x18UpdateCcaiProjectRequest\x12:\n" +
	"\fccai_project\x18\x01 \x01(\v2\x17.ondewo.nlu.CcaiProjectR\vccaiProject\x12M\n" +
	"\x13ccai_service_filter\x18\x02 \x01(\v2\x1d.ondewo.nlu.CcaiServiceFilterR\x11ccaiServiceFilter\x12;\n" +
	"\vupdate_mask\x18\x03 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\x12(\n" +
	"\x10nlu_project_name\x18\x04 \x01(\tR\x0enluProjectName\"T\n" +
	"\x19UpdateCcaiProjectResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"X\n" +
	"\x18DeleteCcaiProjectRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12(\n" +
	"\x10nlu_project_name\x18\x04 \x01(\tR\x0enluProjectName\"~\n" +
	"\x19DeleteCcaiProjectResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12(\n" +
	"\x10nlu_project_name\x18\x04 \x01(\tR\x0enluProjectName*\xab\x02\n" +
	"\x11CcaiProjectStatus\x12#\n" +
	"\x1fCCAI_PROJECT_STATUS_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eCCAI_PROJECT_STATUS_UNDEPLOYED\x10\x01\x12 \n" +
	"\x1cCCAI_PROJECT_STATUS_UPDATING\x10\x02\x12!\n" +
	"\x1dCCAI_PROJECT_STATUS_DEPLOYING\x10\x03\x12 \n" +
	"\x1cCCAI_PROJECT_STATUS_DEPLOYED\x10\x04\x12#\n" +
	"\x1fCCAI_PROJECT_STATUS_UNDEPLOYING\x10\x05\x12 \n" +
	"\x1cCCAI_PROJECT_STATUS_DELETING\x10\x06\x12\x1f\n" +
	"\x1bCCAI_PROJECT_STATUS_DELETED\x10\a*\xfd\a\n" +
	"\x0fCcaiServiceType\x12!\n" +
	"\x1dCCAI_SERVICE_TYPE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cCCAI_SERVICE_TYPE_ONDEWO_AIM\x10\x01\x12 \n" +
	"\x1cCCAI_SERVICE_TYPE_ONDEWO_BPI\x10\x02\x12 \n" +
	"\x1cCCAI_SERVICE_TYPE_ONDEWO_CSI\x10\x03\x12 \n" +
	"\x1cCCAI_SERVICE_TYPE_ONDEWO_NLU\x10\x04\x12 \n" +
	"\x1cCCAI_SERVICE_TYPE_ONDEWO_S2T\x10\x05\x12 \n" +
	"\x1cCCAI_SERVICE_TYPE_ONDEWO_SIP\x10\x06\x12 \n" +
	"\x1cCCAI_SERVICE_TYPE_ONDEWO_T2S\x10\a\x12!\n" +
	"\x1dCCAI_SERVICE_TYPE_ONDEWO_VTSI\x10\b\x12*\n" +
	"&CCAI_SERVICE_TYPE_ONDEWO_VTSI_RABBITMQ\x10\t\x12#\n" +
	"\x1fCCAI_SERVICE_TYPE_ONDEWO_NLU_QA\x10\n" +
	"\x12(\n" +
	"$CCAI_SERVICE_TYPE_ONDEWO_NLU_WEBHOOK\x10\v\x12#\n" +
	"\x1fCCAI_SERVICE_TYPE_ONDEWO_SURVEY\x10\f\x12$\n" +
	" CCAI_SERVICE_TYPE_ONDEWO_NLU_LLM\x10\r\x12*\n" +
	"&CCAI_SERVICE_TYPE_ONDEWO_NLU_WEBSEARCH\x10\x0e\x12(\n" +
	"$CCAI_SERVICE_TYPE_ONDEWO_AIM_WEBCHAT\x10\x0f\x12)\n" +
	"%CCAI_SERVICE_TYPE_ONDEWO_AIM_WEBPHONE\x10\x10\x12,\n" +
	"(CCAI_SERVICE_TYPE_ONDEWO_NLU_VECTORSTORE\x10\x11\x12*\n" +
	"&CCAI_SERVICE_TYPE_ONDEWO_NLU_LLM_AGENT\x10\x12\x12(\n" +
	"$CCAI_SERVICE_TYPE_ONDEWO_NLU_LLM_MCP\x10\x13\x12(\n" +
	"$CCAI_SERVICE_TYPE_ONDEWO_NLU_LLM_RAG\x10\x14\x12&\n" +
	"\"CCAI_SERVICE_TYPE_ONDEWO_ANALYTICS\x10\x15\x120\n" +
	",CCAI_SERVICE_TYPE_ONDEWO_ANALYTICS_DASHBOARD\x10\x16\x123\n" +
	"/CCAI_SERVICE_TYPE_ONDEWO_VTSI_OUTBOUND_CAMPAIGN\x10\x17\x122\n" +
	".CCAI_SERVICE_TYPE_ONDEWO_VTSI_INBOUND_CAMPAIGN\x10\x18*\xd9\n" +
	"\n" +
	"\x13CcaiServiceProvider\x12\x1c\n" +
	"\x18NO_CCAI_SERVICE_PROVIDER\x10\x00\x12 \n" +
	"\x1cCCAI_SERVICE_PROVIDER_ONDEWO\x10\x01\x12'\n" +
	"#CCAI_SERVICE_PROVIDER_GOOGLE_GEMINI\x10\x02\x120\n" +
	",CCAI_SERVICE_PROVIDER_MICROSOFT_AZURE_OPENAI\x10\x03\x12+\n" +
	"'CCAI_SERVICE_PROVIDER_MICROSOFT_AUTOGEN\x10\x04\x12 \n" +
	"\x1cCCAI_SERVICE_PROVIDER_OLLAMA\x10\x05\x12 \n" +
	"\x1cCCAI_SERVICE_PROVIDER_OPENAI\x10\x06\x12#\n" +
	"\x1fCCAI_SERVICE_PROVIDER_ANTHROPIC\x10\a\x12%\n" +
	"!CCAI_SERVICE_PROVIDER_HUGGINGFACE\x10\b\x12\x1d\n" +
	"\x19CCAI_SERVICE_PROVIDER_IBM\x10\t\x12\"\n" +
	"\x1eCCAI_SERVICE_PROVIDER_HAYSTACK\x10\n" +
	"\x12#\n" +
	"\x1fCCAI_SERVICE_PROVIDER_LANGCHAIN\x10\v\x12 \n" +
	"\x1cCCAI_SERVICE_PROVIDER_AMAZON\x10\f\x12!\n" +
	"\x1dCCAI_SERVICE_PROVIDER_MISTRAL\x10\r\x12$\n" +
	" CCAI_SERVICE_PROVIDER_DUCKDUCKGO\x10\x0e\x12$\n" +
	" CCAI_SERVICE_PROVIDER_GOOGLE_PSE\x10\x0f\x12\x1e\n" +
	"\x1aCCAI_SERVICE_PROVIDER_JINA\x10\x10\x12 \n" +
	"\x1cCCAI_SERVICE_PROVIDER_TAVILY\x10\x11\x12'\n" +
	"#CCAI_SERVICE_PROVIDER_ELASTICSEARCH\x10\x12\x12 \n" +
	"\x1cCCAI_SERVICE_PROVIDER_MILVUS\x10\x13\x12 \n" +
	"\x1cCCAI_SERVICE_PROVIDER_QDRANT\x10\x14\x12 \n" +
	"\x1cCCAI_SERVICE_PROVIDER_CHROMA\x10\x15\x12 \n" +
	"\x1cCCAI_SERVICE_PROVIDER_GOOGLE\x10\x16\x12#\n" +
	"\x1fCCAI_SERVICE_PROVIDER_MICROSOFT\x10\x17\x12\"\n" +
	"\x1eCCAI_SERVICE_PROVIDER_DEEPGRAM\x10\x18\x12$\n" +
	" CCAI_SERVICE_PROVIDER_ELEVENLABS\x10\x19\x12)\n" +
	"%CCAI_SERVICE_PROVIDER_HUGGINGFACE_TGI\x10\x1a\x12)\n" +
	"%CCAI_SERVICE_PROVIDER_HUGGINGFACE_TGE\x10\x1b\x120\n" +
	",CCAI_SERVICE_PROVIDER_HUGGINGFACE_SMOLAGENTS\x10\x1c\x126\n" +
	"2CCAI_SERVICE_PROVIDER_GOOGLE_AGENT_DEVELOPMENT_KIT\x10\x1d\x120\n" +
	",CCAI_SERVICE_PROVIDER_MODEL_CONTEXT_PROTOCOL\x10\x1e\x12$\n" +
	" CCAI_SERVICE_PROVIDER_OPENSEARCH\x10\x1f\x12\x1e\n" +
	"\x1aCCAI_SERVICE_PROVIDER_GROK\x10 \x12\"\n" +
	"\x1eCCAI_SERVICE_PROVIDER_POSTGRES\x10!\x123\n" +
	"/CCAI_SERVICE_PROVIDER_MICROSOFT_AGENT_FRAMEWORK\x10\"*\x8e\x01\n" +
	"\x0fCcaiProjectView\x12!\n" +
	"\x1dCCAI_PROJECT_VIEW_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16CCAI_PROJECT_VIEW_FULL\x10\x01\x12\x1d\n" +
	"\x19CCAI_PROJECT_VIEW_SHALLOW\x10\x02\x12\x1d\n" +
	"\x19CCAI_PROJECT_VIEW_MINIMUM\x10\x032\xaf\x04\n" +
	"\fCcaiProjects\x12L\n" +
	"\x0eGetCcaiProject\x12!.ondewo.nlu.GetCcaiProjectRequest\x1a\x17.ondewo.nlu.CcaiProject\x12`\n" +
	"\x11CreateCcaiProject\x12$.ondewo.nlu.CreateCcaiProjectRequest\x1a%.ondewo.nlu.CreateCcaiProjectResponse\x12`\n" +
	"\x11DeleteCcaiProject\x12$.ondewo.nlu.DeleteCcaiProjectRequest\x1a%.ondewo.nlu.DeleteCcaiProjectResponse\x12]\n" +
	"\x10ListCcaiProjects\x12#.ondewo.nlu.ListCcaiProjectsRequest\x1a$.ondewo.nlu.ListCcaiProjectsResponse\x12`\n" +
	"\x11UpdateCcaiProject\x12$.ondewo.nlu.UpdateCcaiProjectRequest\x1a%.ondewo.nlu.UpdateCcaiProjectResponse\x12L\n" +
	"\x0eGetCcaiService\x12!.ondewo.nlu.GetCcaiServiceRequest\x1a\x17.ondewo.nlu.CcaiServiceb\x06proto3"

var (
	file_ondewo_nlu_ccai_project_proto_rawDescOnce sync.Once
	file_ondewo_nlu_ccai_project_proto_rawDescData []byte
)

func file_ondewo_nlu_ccai_project_proto_rawDescGZIP() []byte {
	file_ondewo_nlu_ccai_project_proto_rawDescOnce.Do(func() {
		file_ondewo_nlu_ccai_project_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ondewo_nlu_ccai_project_proto_rawDesc), len(file_ondewo_nlu_ccai_project_proto_rawDesc)))
	})
	return file_ondewo_nlu_ccai_project_proto_rawDescData
}

var file_ondewo_nlu_ccai_project_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_ondewo_nlu_ccai_project_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_ondewo_nlu_ccai_project_proto_goTypes = []any{
	(CcaiProjectStatus)(0),                          // 0: ondewo.nlu.CcaiProjectStatus
	(CcaiServiceType)(0),                            // 1: ondewo.nlu.CcaiServiceType
	(CcaiServiceProvider)(0),                        // 2: ondewo.nlu.CcaiServiceProvider
	(CcaiProjectView)(0),                            // 3: ondewo.nlu.CcaiProjectView
	(CcaiProjectSorting_CcaiProjectSortingField)(0), // 4: ondewo.nlu.CcaiProjectSorting.CcaiProjectSortingField
	(*CcaiProject)(nil),                             // 5: ondewo.nlu.CcaiProject
	(*CcaiServiceList)(nil),                         // 6: ondewo.nlu.CcaiServiceList
	(*CcaiService)(nil),                             // 7: ondewo.nlu.CcaiService
	(*CreateCcaiProjectRequest)(nil),                // 8: ondewo.nlu.CreateCcaiProjectRequest
	(*CreateCcaiProjectResponse)(nil),               // 9: ondewo.nlu.CreateCcaiProjectResponse
	(*GetCcaiProjectRequest)(nil),                   // 10: ondewo.nlu.GetCcaiProjectRequest
	(*GetCcaiServiceRequest)(nil),                   // 11: ondewo.nlu.GetCcaiServiceRequest
	(*ListCcaiProjectsRequest)(nil),                 // 12: ondewo.nlu.ListCcaiProjectsRequest
	(*ListCcaiProjectsResponse)(nil),                // 13: ondewo.nlu.ListCcaiProjectsResponse
	(*CcaiProjectSorting)(nil),                      // 14: ondewo.nlu.CcaiProjectSorting
	(*CcaiServiceFilter)(nil),                       // 15: ondewo.nlu.CcaiServiceFilter
	(*UpdateCcaiProjectRequest)(nil),                // 16: ondewo.nlu.UpdateCcaiProjectRequest
	(*UpdateCcaiProjectResponse)(nil),               // 17: ondewo.nlu.UpdateCcaiProjectResponse
	(*DeleteCcaiProjectRequest)(nil),                // 18: ondewo.nlu.DeleteCcaiProjectRequest
	(*DeleteCcaiProjectResponse)(nil),               // 19: ondewo.nlu.DeleteCcaiProjectResponse
	nil,                                             // 20: ondewo.nlu.CcaiProject.CcaiServicesMapEntry
	(*timestamppb.Timestamp)(nil),                   // 21: google.protobuf.Timestamp
	(*structpb.Struct)(nil),                         // 22: google.protobuf.Struct
	(*fieldmaskpb.FieldMask)(nil),                   // 23: google.protobuf.FieldMask
	(SortingMode)(0),                                // 24: ondewo.nlu.SortingMode
}
var file_ondewo_nlu_ccai_project_proto_depIdxs = []int32{
	20, // 0: ondewo.nlu.CcaiProject.ccai_services_map:type_name -> ondewo.nlu.CcaiProject.CcaiServicesMapEntry
	0,  // 1: ondewo.nlu.CcaiProject.ccai_project_status:type_name -> ondewo.nlu.CcaiProjectStatus
	21, // 2: ondewo.nlu.CcaiProject.created_at:type_name -> google.protobuf.Timestamp
	21, // 3: ondewo.nlu.CcaiProject.modified_at:type_name -> google.protobuf.Timestamp
	7,  // 4: ondewo.nlu.CcaiServiceList.ccai_services:type_name -> ondewo.nlu.CcaiService
	1,  // 5: ondewo.nlu.CcaiService.ccai_service_type:type_name -> ondewo.nlu.CcaiServiceType
	22, // 6: ondewo.nlu.CcaiService.ccai_service_config:type_name -> google.protobuf.Struct
	21, // 7: ondewo.nlu.CcaiService.created_at:type_name -> google.protobuf.Timestamp
	21, // 8: ondewo.nlu.CcaiService.modified_at:type_name -> google.protobuf.Timestamp
	22, // 9: ondewo.nlu.CcaiService.headers:type_name -> google.protobuf.Struct
	2,  // 10: ondewo.nlu.CcaiService.ccai_service_provider:type_name -> ondewo.nlu.CcaiServiceProvider
	5,  // 11: ondewo.nlu.CreateCcaiProjectRequest.ccai_project:type_name -> ondewo.nlu.CcaiProject
	5,  // 12: ondewo.nlu.CreateCcaiProjectResponse.ccai_project:type_name -> ondewo.nlu.CcaiProject
	3,  // 13: ondewo.nlu.GetCcaiProjectRequest.ccai_project_view:type_name -> ondewo.nlu.CcaiProjectView
	15, // 14: ondewo.nlu.GetCcaiProjectRequest.ccai_service_filter:type_name -> ondewo.nlu.CcaiServiceFilter
	23, // 15: ondewo.nlu.GetCcaiProjectRequest.field_mask:type_name -> google.protobuf.FieldMask
	23, // 16: ondewo.nlu.GetCcaiServiceRequest.field_mask:type_name -> google.protobuf.FieldMask
	3,  // 17: ondewo.nlu.ListCcaiProjectsRequest.ccai_project_view:type_name -> ondewo.nlu.CcaiProjectView
	15, // 18: ondewo.nlu.ListCcaiProjectsRequest.ccai_service_filter:type_name -> ondewo.nlu.CcaiServiceFilter
	14, // 19: ondewo.nlu.ListCcaiProjectsRequest.ccai_project_sorting:type_name -> ondewo.nlu.CcaiProjectSorting
	23, // 20: ondewo.nlu.ListCcaiProjectsRequest.field_mask:type_name -> google.protobuf.FieldMask
	5,  // 21: ondewo.nlu.ListCcaiProjectsResponse.ccai_projects:type_name -> ondewo.nlu.CcaiProject
	4,  // 22: ondewo.nlu.CcaiProjectSorting.sorting_field:type_name -> ondewo.nlu.CcaiProjectSorting.CcaiProjectSortingField
	24, // 23: ondewo.nlu.CcaiProjectSorting.sorting_mode:type_name -> ondewo.nlu.SortingMode
	1,  // 24: ondewo.nlu.CcaiServiceFilter.ccai_service_types:type_name -> ondewo.nlu.CcaiServiceType
	2,  // 25: ondewo.nlu.CcaiServiceFilter.ccai_service_providers:type_name -> ondewo.nlu.CcaiServiceProvider
	5,  // 26: ondewo.nlu.UpdateCcaiProjectRequest.ccai_project:type_name -> ondewo.nlu.CcaiProject
	15, // 27: ondewo.nlu.UpdateCcaiProjectRequest.ccai_service_filter:type_name -> ondewo.nlu.CcaiServiceFilter
	23, // 28: ondewo.nlu.UpdateCcaiProjectRequest.update_mask:type_name -> google.protobuf.FieldMask
	6,  // 29: ondewo.nlu.CcaiProject.CcaiServicesMapEntry.value:type_name -> ondewo.nlu.CcaiServiceList
	10, // 30: ondewo.nlu.CcaiProjects.GetCcaiProject:input_type -> ondewo.nlu.GetCcaiProjectRequest
	8,  // 31: ondewo.nlu.CcaiProjects.CreateCcaiProject:input_type -> ondewo.nlu.CreateCcaiProjectRequest
	18, // 32: ondewo.nlu.CcaiProjects.DeleteCcaiProject:input_type -> ondewo.nlu.DeleteCcaiProjectRequest
	12, // 33: ondewo.nlu.CcaiProjects.ListCcaiProjects:input_type -> ondewo.nlu.ListCcaiProjectsRequest
	16, // 34: ondewo.nlu.CcaiProjects.UpdateCcaiProject:input_type -> ondewo.nlu.UpdateCcaiProjectRequest
	11, // 35: ondewo.nlu.CcaiProjects.GetCcaiService:input_type -> ondewo.nlu.GetCcaiServiceRequest
	5,  // 36: ondewo.nlu.CcaiProjects.GetCcaiProject:output_type -> ondewo.nlu.CcaiProject
	9,  // 37: ondewo.nlu.CcaiProjects.CreateCcaiProject:output_type -> ondewo.nlu.CreateCcaiProjectResponse
	19, // 38: ondewo.nlu.CcaiProjects.DeleteCcaiProject:output_type -> ondewo.nlu.DeleteCcaiProjectResponse
	13, // 39: ondewo.nlu.CcaiProjects.ListCcaiProjects:output_type -> ondewo.nlu.ListCcaiProjectsResponse
	17, // 40: ondewo.nlu.CcaiProjects.UpdateCcaiProject:output_type -> ondewo.nlu.UpdateCcaiProjectResponse
	7,  // 41: ondewo.nlu.CcaiProjects.GetCcaiService:output_type -> ondewo.nlu.CcaiService
	36, // [36:42] is the sub-list for method output_type
	30, // [30:36] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_ondewo_nlu_ccai_project_proto_init() }
func file_ondewo_nlu_ccai_project_proto_init() {
	if File_ondewo_nlu_ccai_project_proto != nil {
		return
	}
	file_ondewo_nlu_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ondewo_nlu_ccai_project_proto_rawDesc), len(file_ondewo_nlu_ccai_project_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ondewo_nlu_ccai_project_proto_goTypes,
		DependencyIndexes: file_ondewo_nlu_ccai_project_proto_depIdxs,
		EnumInfos:         file_ondewo_nlu_ccai_project_proto_enumTypes,
		MessageInfos:      file_ondewo_nlu_ccai_project_proto_msgTypes,
	}.Build()
	File_ondewo_nlu_ccai_project_proto = out.File
	file_ondewo_nlu_ccai_project_proto_goTypes = nil
	file_ondewo_nlu_ccai_project_proto_depIdxs = nil
}
