// Copyright 2020-2026 ONDEWO GmbH
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.32.0
// source: ondewo/nlu/ccai_project.proto

package nlu

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CcaiProjects_GetCcaiProject_FullMethodName    = "/ondewo.nlu.CcaiProjects/GetCcaiProject"
	CcaiProjects_CreateCcaiProject_FullMethodName = "/ondewo.nlu.CcaiProjects/CreateCcaiProject"
	CcaiProjects_DeleteCcaiProject_FullMethodName = "/ondewo.nlu.CcaiProjects/DeleteCcaiProject"
	CcaiProjects_ListCcaiProjects_FullMethodName  = "/ondewo.nlu.CcaiProjects/ListCcaiProjects"
	CcaiProjects_UpdateCcaiProject_FullMethodName = "/ondewo.nlu.CcaiProjects/UpdateCcaiProject"
	CcaiProjects_GetCcaiService_FullMethodName    = "/ondewo.nlu.CcaiProjects/GetCcaiService"
)

// CcaiProjectsClient is the client API for CcaiProjects service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service to manage Call Center AI (CCAI service) Projects.
type CcaiProjectsClient interface {
	// Retrieves information about a specific CCAI service project.
	GetCcaiProject(ctx context.Context, in *GetCcaiProjectRequest, opts ...grpc.CallOption) (*CcaiProject, error)
	// Creates a new CCAI service project based on the provided request.
	CreateCcaiProject(ctx context.Context, in *CreateCcaiProjectRequest, opts ...grpc.CallOption) (*CreateCcaiProjectResponse, error)
	// Deletes a CCAI service project identified by the provided request.
	DeleteCcaiProject(ctx context.Context, in *DeleteCcaiProjectRequest, opts ...grpc.CallOption) (*DeleteCcaiProjectResponse, error)
	// Lists all CCAI service projects based on the provided request.
	ListCcaiProjects(ctx context.Context, in *ListCcaiProjectsRequest, opts ...grpc.CallOption) (*ListCcaiProjectsResponse, error)
	// Updates the information of an existing CCAI service project.
	UpdateCcaiProject(ctx context.Context, in *UpdateCcaiProjectRequest, opts ...grpc.CallOption) (*UpdateCcaiProjectResponse, error)
	// Retrieves information about a specific CCAI service.
	GetCcaiService(ctx context.Context, in *GetCcaiServiceRequest, opts ...grpc.CallOption) (*CcaiService, error)
}

type ccaiProjectsClient struct {
	cc grpc.ClientConnInterface
}

func NewCcaiProjectsClient(cc grpc.ClientConnInterface) CcaiProjectsClient {
	return &ccaiProjectsClient{cc}
}

func (c *ccaiProjectsClient) GetCcaiProject(ctx context.Context, in *GetCcaiProjectRequest, opts ...grpc.CallOption) (*CcaiProject, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CcaiProject)
	err := c.cc.Invoke(ctx, CcaiProjects_GetCcaiProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ccaiProjectsClient) CreateCcaiProject(ctx context.Context, in *CreateCcaiProjectRequest, opts ...grpc.CallOption) (*CreateCcaiProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCcaiProjectResponse)
	err := c.cc.Invoke(ctx, CcaiProjects_CreateCcaiProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ccaiProjectsClient) DeleteCcaiProject(ctx context.Context, in *DeleteCcaiProjectRequest, opts ...grpc.CallOption) (*DeleteCcaiProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCcaiProjectResponse)
	err := c.cc.Invoke(ctx, CcaiProjects_DeleteCcaiProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ccaiProjectsClient) ListCcaiProjects(ctx context.Context, in *ListCcaiProjectsRequest, opts ...grpc.CallOption) (*ListCcaiProjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCcaiProjectsResponse)
	err := c.cc.Invoke(ctx, CcaiProjects_ListCcaiProjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ccaiProjectsClient) UpdateCcaiProject(ctx context.Context, in *UpdateCcaiProjectRequest, opts ...grpc.CallOption) (*UpdateCcaiProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCcaiProjectResponse)
	err := c.cc.Invoke(ctx, CcaiProjects_UpdateCcaiProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ccaiProjectsClient) GetCcaiService(ctx context.Context, in *GetCcaiServiceRequest, opts ...grpc.CallOption) (*CcaiService, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CcaiService)
	err := c.cc.Invoke(ctx, CcaiProjects_GetCcaiService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CcaiProjectsServer is the server API for CcaiProjects service.
// All implementations must embed UnimplementedCcaiProjectsServer
// for forward compatibility.
//
// Service to manage Call Center AI (CCAI service) Projects.
type CcaiProjectsServer interface {
	// Retrieves information about a specific CCAI service project.
	GetCcaiProject(context.Context, *GetCcaiProjectRequest) (*CcaiProject, error)
	// Creates a new CCAI service project based on the provided request.
	CreateCcaiProject(context.Context, *CreateCcaiProjectRequest) (*CreateCcaiProjectResponse, error)
	// Deletes a CCAI service project identified by the provided request.
	DeleteCcaiProject(context.Context, *DeleteCcaiProjectRequest) (*DeleteCcaiProjectResponse, error)
	// Lists all CCAI service projects based on the provided request.
	ListCcaiProjects(context.Context, *ListCcaiProjectsRequest) (*ListCcaiProjectsResponse, error)
	// Updates the information of an existing CCAI service project.
	UpdateCcaiProject(context.Context, *UpdateCcaiProjectRequest) (*UpdateCcaiProjectResponse, error)
	// Retrieves information about a specific CCAI service.
	GetCcaiService(context.Context, *GetCcaiServiceRequest) (*CcaiService, error)
	mustEmbedUnimplementedCcaiProjectsServer()
}

// UnimplementedCcaiProjectsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCcaiProjectsServer struct{}

func (UnimplementedCcaiProjectsServer) GetCcaiProject(context.Context, *GetCcaiProjectRequest) (*CcaiProject, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCcaiProject not implemented")
}
func (UnimplementedCcaiProjectsServer) CreateCcaiProject(context.Context, *CreateCcaiProjectRequest) (*CreateCcaiProjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCcaiProject not implemented")
}
func (UnimplementedCcaiProjectsServer) DeleteCcaiProject(context.Context, *DeleteCcaiProjectRequest) (*DeleteCcaiProjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCcaiProject not implemented")
}
func (UnimplementedCcaiProjectsServer) ListCcaiProjects(context.Context, *ListCcaiProjectsRequest) (*ListCcaiProjectsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCcaiProjects not implemented")
}
func (UnimplementedCcaiProjectsServer) UpdateCcaiProject(context.Context, *UpdateCcaiProjectRequest) (*UpdateCcaiProjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCcaiProject not implemented")
}
func (UnimplementedCcaiProjectsServer) GetCcaiService(context.Context, *GetCcaiServiceRequest) (*CcaiService, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCcaiService not implemented")
}
func (UnimplementedCcaiProjectsServer) mustEmbedUnimplementedCcaiProjectsServer() {}
func (UnimplementedCcaiProjectsServer) testEmbeddedByValue()                      {}

// UnsafeCcaiProjectsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CcaiProjectsServer will
// result in compilation errors.
type UnsafeCcaiProjectsServer interface {
	mustEmbedUnimplementedCcaiProjectsServer()
}

func RegisterCcaiProjectsServer(s grpc.ServiceRegistrar, srv CcaiProjectsServer) {
	// If the following call panics, it indicates UnimplementedCcaiProjectsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CcaiProjects_ServiceDesc, srv)
}

func _CcaiProjects_GetCcaiProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCcaiProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CcaiProjectsServer).GetCcaiProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CcaiProjects_GetCcaiProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CcaiProjectsServer).GetCcaiProject(ctx, req.(*GetCcaiProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CcaiProjects_CreateCcaiProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCcaiProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CcaiProjectsServer).CreateCcaiProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CcaiProjects_CreateCcaiProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CcaiProjectsServer).CreateCcaiProject(ctx, req.(*CreateCcaiProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CcaiProjects_DeleteCcaiProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCcaiProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CcaiProjectsServer).DeleteCcaiProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CcaiProjects_DeleteCcaiProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CcaiProjectsServer).DeleteCcaiProject(ctx, req.(*DeleteCcaiProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CcaiProjects_ListCcaiProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCcaiProjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CcaiProjectsServer).ListCcaiProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CcaiProjects_ListCcaiProjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CcaiProjectsServer).ListCcaiProjects(ctx, req.(*ListCcaiProjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CcaiProjects_UpdateCcaiProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCcaiProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CcaiProjectsServer).UpdateCcaiProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CcaiProjects_UpdateCcaiProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CcaiProjectsServer).UpdateCcaiProject(ctx, req.(*UpdateCcaiProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CcaiProjects_GetCcaiService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCcaiServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CcaiProjectsServer).GetCcaiService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CcaiProjects_GetCcaiService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CcaiProjectsServer).GetCcaiService(ctx, req.(*GetCcaiServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CcaiProjects_ServiceDesc is the grpc.ServiceDesc for CcaiProjects service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CcaiProjects_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ondewo.nlu.CcaiProjects",
	HandlerType: (*CcaiProjectsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCcaiProject",
			Handler:    _CcaiProjects_GetCcaiProject_Handler,
		},
		{
			MethodName: "CreateCcaiProject",
			Handler:    _CcaiProjects_CreateCcaiProject_Handler,
		},
		{
			MethodName: "DeleteCcaiProject",
			Handler:    _CcaiProjects_DeleteCcaiProject_Handler,
		},
		{
			MethodName: "ListCcaiProjects",
			Handler:    _CcaiProjects_ListCcaiProjects_Handler,
		},
		{
			MethodName: "UpdateCcaiProject",
			Handler:    _CcaiProjects_UpdateCcaiProject_Handler,
		},
		{
			MethodName: "GetCcaiService",
			Handler:    _CcaiProjects_GetCcaiService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ondewo/nlu/ccai_project.proto",
}
