// Copyright 2020-2026 ONDEWO GmbH
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.32.0
// source: ondewo/nlu/operations.proto

package nlu

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The lifecycle state of a remote-operation container, mirroring the Docker container lifecycle.
type RemoteOperationContainerLifecycleState int32

const (
	// The lifecycle state could not be determined.
	RemoteOperationContainerLifecycleState_REMOTE_OPERATION_CONTAINER_LIFECYCLE_STATE_UNSPECIFIED RemoteOperationContainerLifecycleState = 0
	// No container with the recorded name exists on the recorded host (never started, already reaped,
	// or the dispatch record was garbage-collected after completion).
	RemoteOperationContainerLifecycleState_REMOTE_OPERATION_CONTAINER_LIFECYCLE_STATE_NOT_FOUND RemoteOperationContainerLifecycleState = 1
	// The container has been created but is not yet running.
	RemoteOperationContainerLifecycleState_REMOTE_OPERATION_CONTAINER_LIFECYCLE_STATE_CREATED RemoteOperationContainerLifecycleState = 2
	// The container is running.
	RemoteOperationContainerLifecycleState_REMOTE_OPERATION_CONTAINER_LIFECYCLE_STATE_RUNNING RemoteOperationContainerLifecycleState = 3
	// The container is paused.
	RemoteOperationContainerLifecycleState_REMOTE_OPERATION_CONTAINER_LIFECYCLE_STATE_PAUSED RemoteOperationContainerLifecycleState = 4
	// The container is in the process of restarting.
	RemoteOperationContainerLifecycleState_REMOTE_OPERATION_CONTAINER_LIFECYCLE_STATE_RESTARTING RemoteOperationContainerLifecycleState = 5
	// The container has exited (successfully or with an error — see <code>exit_code</code>).
	RemoteOperationContainerLifecycleState_REMOTE_OPERATION_CONTAINER_LIFECYCLE_STATE_EXITED RemoteOperationContainerLifecycleState = 6
	// The container is dead (Docker could not stop/remove it cleanly).
	RemoteOperationContainerLifecycleState_REMOTE_OPERATION_CONTAINER_LIFECYCLE_STATE_DEAD RemoteOperationContainerLifecycleState = 7
)

// Enum value maps for RemoteOperationContainerLifecycleState.
var (
	RemoteOperationContainerLifecycleState_name = map[int32]string{
		0: "REMOTE_OPERATION_CONTAINER_LIFECYCLE_STATE_UNSPECIFIED",
		1: "REMOTE_OPERATION_CONTAINER_LIFECYCLE_STATE_NOT_FOUND",
		2: "REMOTE_OPERATION_CONTAINER_LIFECYCLE_STATE_CREATED",
		3: "REMOTE_OPERATION_CONTAINER_LIFECYCLE_STATE_RUNNING",
		4: "REMOTE_OPERATION_CONTAINER_LIFECYCLE_STATE_PAUSED",
		5: "REMOTE_OPERATION_CONTAINER_LIFECYCLE_STATE_RESTARTING",
		6: "REMOTE_OPERATION_CONTAINER_LIFECYCLE_STATE_EXITED",
		7: "REMOTE_OPERATION_CONTAINER_LIFECYCLE_STATE_DEAD",
	}
	RemoteOperationContainerLifecycleState_value = map[string]int32{
		"REMOTE_OPERATION_CONTAINER_LIFECYCLE_STATE_UNSPECIFIED": 0,
		"REMOTE_OPERATION_CONTAINER_LIFECYCLE_STATE_NOT_FOUND":   1,
		"REMOTE_OPERATION_CONTAINER_LIFECYCLE_STATE_CREATED":     2,
		"REMOTE_OPERATION_CONTAINER_LIFECYCLE_STATE_RUNNING":     3,
		"REMOTE_OPERATION_CONTAINER_LIFECYCLE_STATE_PAUSED":      4,
		"REMOTE_OPERATION_CONTAINER_LIFECYCLE_STATE_RESTARTING":  5,
		"REMOTE_OPERATION_CONTAINER_LIFECYCLE_STATE_EXITED":      6,
		"REMOTE_OPERATION_CONTAINER_LIFECYCLE_STATE_DEAD":        7,
	}
)

func (x RemoteOperationContainerLifecycleState) Enum() *RemoteOperationContainerLifecycleState {
	p := new(RemoteOperationContainerLifecycleState)
	*p = x
	return p
}

func (x RemoteOperationContainerLifecycleState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RemoteOperationContainerLifecycleState) Descriptor() protoreflect.EnumDescriptor {
	return file_ondewo_nlu_operations_proto_enumTypes[0].Descriptor()
}

func (RemoteOperationContainerLifecycleState) Type() protoreflect.EnumType {
	return &file_ondewo_nlu_operations_proto_enumTypes[0]
}

func (x RemoteOperationContainerLifecycleState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RemoteOperationContainerLifecycleState.Descriptor instead.
func (RemoteOperationContainerLifecycleState) EnumDescriptor() ([]byte, []int) {
	return file_ondewo_nlu_operations_proto_rawDescGZIP(), []int{0}
}

// This resource represents a long-running operation that is the result of a network API call.
type Operation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The server-assigned name, which is only unique within the same service that
	// originally returns it. If you use the default HTTP mapping, the
	// <code>name</code> should have the format of <code>operations/some/unique/name</code>.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Service-specific metadata associated with the operation.  It typically
	// contains progress information and common metadata such as create time.
	// Some services might not provide such metadata.  Any method that returns a
	// long-running operation should document the metadata type, if any.
	Metadata *OperationMetadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// If the value is <code>false</code>, it means the operation is still in progress.
	// If true, the operation is completed, and either <code>error</code> or <code>response</code> is
	// available.
	Done bool `protobuf:"varint,3,opt,name=done,proto3" json:"done,omitempty"`
	// The operation result, which can be either an <code>error</code> or a valid <code>response</code>.
	// If <code>done</code> == <code>false</code>, neither <code>error</code> nor <code>response</code> is set.
	// If <code>done</code> == <code>true</code>, exactly one of <code>error</code> or <code>response</code> is set.
	//
	// Types that are valid to be assigned to Result:
	//
	//	*Operation_Error
	//	*Operation_Response
	Result        isOperation_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_ondewo_nlu_operations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_nlu_operations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_ondewo_nlu_operations_proto_rawDescGZIP(), []int{0}
}

func (x *Operation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Operation) GetMetadata() *OperationMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Operation) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *Operation) GetResult() isOperation_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *Operation) GetError() *status.Status {
	if x != nil {
		if x, ok := x.Result.(*Operation_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *Operation) GetResponse() *anypb.Any {
	if x != nil {
		if x, ok := x.Result.(*Operation_Response); ok {
			return x.Response
		}
	}
	return nil
}

type isOperation_Result interface {
	isOperation_Result()
}

type Operation_Error struct {
	// The error result of the operation in case of failure or cancellation.
	Error *status.Status `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

type Operation_Response struct {
	// The normal response of the operation in case of success.  If the original
	// method returns no data on success, such as <code>Delete</code>, the response is
	// <code>google.protobuf.Empty</code>.  If the original method is standard
	// <code>Get</code>/<code>Create</code>/<code>Update</code>, the response should be the resource.  For other
	// methods, the response should have the type <code>XxxResponse</code>, where <code>Xxx</code>
	// is the original method name.  For example, if the original method name
	// is <code>TakeSnapshot()</code>, the inferred response type is
	// <code>TakeSnapshotResponse</code>.
	Response *anypb.Any `protobuf:"bytes,5,opt,name=response,proto3,oneof"`
}

func (*Operation_Error) isOperation_Result() {}

func (*Operation_Response) isOperation_Result() {}

// The request message for <a href="index.html#ondewo.nlu.Operations.GetOperation">Operations.GetOperation</a>.
type GetOperationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the operation resource.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Optional. The mask to control which fields gets returned.
	FieldMask     *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperationRequest) Reset() {
	*x = GetOperationRequest{}
	mi := &file_ondewo_nlu_operations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperationRequest) ProtoMessage() {}

func (x *GetOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_nlu_operations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperationRequest.ProtoReflect.Descriptor instead.
func (*GetOperationRequest) Descriptor() ([]byte, []int) {
	return file_ondewo_nlu_operations_proto_rawDescGZIP(), []int{1}
}

func (x *GetOperationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetOperationRequest) GetFieldMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.FieldMask
	}
	return nil
}

// The request message for <a href="index.html#ondewo.nlu.Operations.ListOperations">Operations.ListOperations</a>.
type ListOperationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the operation collection.
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	// The standard list filter.
	Filter string `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	// The standard list page size.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Optional: The page token to support pagination.
	// Pagination allows you to retrieve a large result set in smaller, more manageable portions.
	// The page token is a string representing the current index and page size.
	//
	// Valid page token strings:
	// <ul>
	//   <li>&quot;&quot; (empty string) - Retrieves the first page.</li>
	//   <li>&quot;current_index-0--page_size-20&quot; - Retrieves the first page with a page size of 20.</li>
	//   <li>&quot;current_index-1--page_size-20&quot; - Retrieves the second page with a page size of 20.</li>
	// </ul>
	//
	// Index starts at 0.
	//
	// Examples of valid page token strings:
	// <ul>
	//   <li>&quot;&quot;</li>
	//   <li>&quot;current_index-0--page_size-20&quot;</li>
	//   <li>&quot;current_index-1--page_size-20&quot;</li>
	//   <li>&quot;current_index-10--page_size-20&quot;</li>
	// </ul>
	//
	// Examples of invalid page token strings:
	// <ul>
	//   <li>&quot;1&quot;</li>
	//   <li>&quot;current_index-0--page_size-20&quot;</li>
	//   <li>&quot;current_index--1--page_size-20&quot;</li>
	//   <li>&quot;current_index1--page_size-20&quot;</li>
	//   <li>&quot;current_index-1--page_size--20&quot;</li>
	// </ul>
	PageToken string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Optional. A filter to narrow the response down to operations of interest.
	OperationFilter *OperationFilter `protobuf:"bytes,5,opt,name=operation_filter,json=operationFilter,proto3" json:"operation_filter,omitempty"`
	// Optional. The mask to control which fields gets returned.
	FieldMask     *fieldmaskpb.FieldMask `protobuf:"bytes,6,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOperationsRequest) Reset() {
	*x = ListOperationsRequest{}
	mi := &file_ondewo_nlu_operations_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOperationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOperationsRequest) ProtoMessage() {}

func (x *ListOperationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_nlu_operations_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOperationsRequest.ProtoReflect.Descriptor instead.
func (*ListOperationsRequest) Descriptor() ([]byte, []int) {
	return file_ondewo_nlu_operations_proto_rawDescGZIP(), []int{2}
}

func (x *ListOperationsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListOperationsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListOperationsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListOperationsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListOperationsRequest) GetOperationFilter() *OperationFilter {
	if x != nil {
		return x.OperationFilter
	}
	return nil
}

func (x *ListOperationsRequest) GetFieldMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.FieldMask
	}
	return nil
}

// This message contains an operation filter
type OperationFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// An operationFilter can be used in some requests to return only operations matching certain filter conditions.
	//
	// All fields below are  optional. Multiple fields specified at the same time are chained via OR.
	// Match operations with any of the following project parents.
	ProjectParents []string `protobuf:"bytes,1,rep,name=project_parents,json=projectParents,proto3" json:"project_parents,omitempty"`
	// Match operation which had any of the following operation statuses.
	Statuses []OperationMetadata_Status `protobuf:"varint,2,rep,packed,name=statuses,proto3,enum=ondewo.nlu.OperationMetadata_Status" json:"statuses,omitempty"`
	// Match operation which had any of the following operation types.
	Types []OperationMetadata_OperationType `protobuf:"varint,3,rep,packed,name=types,proto3,enum=ondewo.nlu.OperationMetadata_OperationType" json:"types,omitempty"`
	// Types that are valid to be assigned to StartTimeOneof:
	//
	//	*OperationFilter_StartTime
	StartTimeOneof isOperationFilter_StartTimeOneof `protobuf_oneof:"start_time_oneof"`
	// Types that are valid to be assigned to EndTimeOneof:
	//
	//	*OperationFilter_EndTime
	EndTimeOneof isOperationFilter_EndTimeOneof `protobuf_oneof:"end_time_oneof"`
	// Match operation which had any of the following user_ids.
	UserIds       []string `protobuf:"bytes,6,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationFilter) Reset() {
	*x = OperationFilter{}
	mi := &file_ondewo_nlu_operations_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationFilter) ProtoMessage() {}

func (x *OperationFilter) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_nlu_operations_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationFilter.ProtoReflect.Descriptor instead.
func (*OperationFilter) Descriptor() ([]byte, []int) {
	return file_ondewo_nlu_operations_proto_rawDescGZIP(), []int{3}
}

func (x *OperationFilter) GetProjectParents() []string {
	if x != nil {
		return x.ProjectParents
	}
	return nil
}

func (x *OperationFilter) GetStatuses() []OperationMetadata_Status {
	if x != nil {
		return x.Statuses
	}
	return nil
}

func (x *OperationFilter) GetTypes() []OperationMetadata_OperationType {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *OperationFilter) GetStartTimeOneof() isOperationFilter_StartTimeOneof {
	if x != nil {
		return x.StartTimeOneof
	}
	return nil
}

func (x *OperationFilter) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.StartTimeOneof.(*OperationFilter_StartTime); ok {
			return x.StartTime
		}
	}
	return nil
}

func (x *OperationFilter) GetEndTimeOneof() isOperationFilter_EndTimeOneof {
	if x != nil {
		return x.EndTimeOneof
	}
	return nil
}

func (x *OperationFilter) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.EndTimeOneof.(*OperationFilter_EndTime); ok {
			return x.EndTime
		}
	}
	return nil
}

func (x *OperationFilter) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type isOperationFilter_StartTimeOneof interface {
	isOperationFilter_StartTimeOneof()
}

type OperationFilter_StartTime struct {
	// The time operation processing started.
	StartTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3,oneof"`
}

func (*OperationFilter_StartTime) isOperationFilter_StartTimeOneof() {}

type isOperationFilter_EndTimeOneof interface {
	isOperationFilter_EndTimeOneof()
}

type OperationFilter_EndTime struct {
	// The time operation processing completed.
	EndTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3,oneof"`
}

func (*OperationFilter_EndTime) isOperationFilter_EndTimeOneof() {}

// The response message for <a href="index.html#ondewo.nlu.Operations.ListOperations">Operations.ListOperations</a>.
type ListOperationsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list of operations that matches the specified filter in the request.
	Operations []*Operation `protobuf:"bytes,1,rep,name=operations,proto3" json:"operations,omitempty"`
	// The next_page_token is used to retrieve the next page of a returned result,
	// e.g. next_page_token is current_index-2
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOperationsResponse) Reset() {
	*x = ListOperationsResponse{}
	mi := &file_ondewo_nlu_operations_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOperationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOperationsResponse) ProtoMessage() {}

func (x *ListOperationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_nlu_operations_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOperationsResponse.ProtoReflect.Descriptor instead.
func (*ListOperationsResponse) Descriptor() ([]byte, []int) {
	return file_ondewo_nlu_operations_proto_rawDescGZIP(), []int{4}
}

func (x *ListOperationsResponse) GetOperations() []*Operation {
	if x != nil {
		return x.Operations
	}
	return nil
}

func (x *ListOperationsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// The request message for <a href="index.html#ondewo.nlu.Operations.CancelOperation">Operations.CancelOperation</a>.
type CancelOperationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the operation resource to be cancelled.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOperationRequest) Reset() {
	*x = CancelOperationRequest{}
	mi := &file_ondewo_nlu_operations_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOperationRequest) ProtoMessage() {}

func (x *CancelOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_nlu_operations_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOperationRequest.ProtoReflect.Descriptor instead.
func (*CancelOperationRequest) Descriptor() ([]byte, []int) {
	return file_ondewo_nlu_operations_proto_rawDescGZIP(), []int{5}
}

func (x *CancelOperationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The request message for <a href="index.html#ondewo.nlu.Operations.DeleteOperation">Operations.DeleteOperation</a>.
type DeleteOperationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the operation resource to be deleted.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOperationRequest) Reset() {
	*x = DeleteOperationRequest{}
	mi := &file_ondewo_nlu_operations_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOperationRequest) ProtoMessage() {}

func (x *DeleteOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_nlu_operations_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOperationRequest.ProtoReflect.Descriptor instead.
func (*DeleteOperationRequest) Descriptor() ([]byte, []int) {
	return file_ondewo_nlu_operations_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteOperationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The request message for <a href="index.html#ondewo.nlu.Operations.StreamRemoteOperationContainerLogs">Operations.StreamRemoteOperationContainerLogs</a>.
type StreamRemoteOperationContainerLogsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the operation resource whose container logs should be streamed.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Only stream lines at or above this loguru severity. <code>LOG_SEVERITY_UNSPECIFIED</code> (the
	// default) streams every line regardless of level.
	MinLogLevel LogSeverity `protobuf:"varint,2,opt,name=min_log_level,json=minLogLevel,proto3,enum=ondewo.nlu.LogSeverity" json:"min_log_level,omitempty"`
	// Replay at most this many of the most recent existing log lines before switching to live follow.
	// <code>0</code> (the default) starts the follow with no historical replay.
	TailLines int32 `protobuf:"varint,3,opt,name=tail_lines,json=tailLines,proto3" json:"tail_lines,omitempty"`
	// Optional. Scope the stream to a single container of the operation, identified by its docker
	// container id (as returned by <a href="index.html#ondewo.nlu.RemoteOperationContainer">RemoteOperationContainer</a>).
	// Empty (the default) streams the operation&apos;s currently-registered container, preserving the
	// legacy single-container behavior.
	ContainerId   string `protobuf:"bytes,4,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRemoteOperationContainerLogsRequest) Reset() {
	*x = StreamRemoteOperationContainerLogsRequest{}
	mi := &file_ondewo_nlu_operations_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRemoteOperationContainerLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRemoteOperationContainerLogsRequest) ProtoMessage() {}

func (x *StreamRemoteOperationContainerLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_nlu_operations_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRemoteOperationContainerLogsRequest.ProtoReflect.Descriptor instead.
func (*StreamRemoteOperationContainerLogsRequest) Descriptor() ([]byte, []int) {
	return file_ondewo_nlu_operations_proto_rawDescGZIP(), []int{7}
}

func (x *StreamRemoteOperationContainerLogsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StreamRemoteOperationContainerLogsRequest) GetMinLogLevel() LogSeverity {
	if x != nil {
		return x.MinLogLevel
	}
	return LogSeverity_LOG_SEVERITY_UNSPECIFIED
}

func (x *StreamRemoteOperationContainerLogsRequest) GetTailLines() int32 {
	if x != nil {
		return x.TailLines
	}
	return 0
}

func (x *StreamRemoteOperationContainerLogsRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

// The request message for <a href="index.html#ondewo.nlu.Operations.GetRemoteOperationContainerLogs">Operations.GetRemoteOperationContainerLogs</a>.
type GetRemoteOperationContainerLogsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the operation resource whose container logs should be returned.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Only return lines at or above this loguru severity. <code>LOG_SEVERITY_UNSPECIFIED</code> (the
	// default) returns every line regardless of level.
	MinLogLevel LogSeverity `protobuf:"varint,2,opt,name=min_log_level,json=minLogLevel,proto3,enum=ondewo.nlu.LogSeverity" json:"min_log_level,omitempty"`
	// Only return lines whose timestamp is at or after this instant. Unset returns from the start of
	// the available logs.
	StartTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// Only return lines whose timestamp is at or before this instant. Unset returns up to the latest
	// available log line.
	EndTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	// Return at most this many lines, keeping the most recent matches. <code>0</code> (the default)
	// applies a server-side safety cap.
	MaxLines int32 `protobuf:"varint,5,opt,name=max_lines,json=maxLines,proto3" json:"max_lines,omitempty"`
	// Only return lines whose message matches this regular expression (Python <code>re</code> syntax).
	// Empty (the default) disables regex filtering.
	Regex string `protobuf:"bytes,6,opt,name=regex,proto3" json:"regex,omitempty"`
	// Optional. Scope the query to a single container of the operation, identified by its docker
	// container id. Empty (the default) queries the operation&apos;s currently-registered container,
	// preserving the legacy single-container behavior. When the container has finished and been removed,
	// its persisted logs are served from the server-side log archive.
	ContainerId string `protobuf:"bytes,7,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	// Optional cursor for infinite-scroll-UP paging: return the newest lines with
	// <a href="index.html#ondewo.nlu.RemoteOperationContainerLogLine">seq</a> &lt; <code>before_seq</code>
	// (older window). <code>0</code> (the default) disables backward paging.
	BeforeSeq int64 `protobuf:"varint,8,opt,name=before_seq,json=beforeSeq,proto3" json:"before_seq,omitempty"`
	// Optional cursor for infinite-scroll-DOWN paging: return lines with <code>seq</code> &gt;
	// <code>after_seq</code> (newer window). <code>0</code> (the default) disables forward paging.
	AfterSeq      int64 `protobuf:"varint,9,opt,name=after_seq,json=afterSeq,proto3" json:"after_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRemoteOperationContainerLogsRequest) Reset() {
	*x = GetRemoteOperationContainerLogsRequest{}
	mi := &file_ondewo_nlu_operations_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRemoteOperationContainerLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRemoteOperationContainerLogsRequest) ProtoMessage() {}

func (x *GetRemoteOperationContainerLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_nlu_operations_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRemoteOperationContainerLogsRequest.ProtoReflect.Descriptor instead.
func (*GetRemoteOperationContainerLogsRequest) Descriptor() ([]byte, []int) {
	return file_ondewo_nlu_operations_proto_rawDescGZIP(), []int{8}
}

func (x *GetRemoteOperationContainerLogsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetRemoteOperationContainerLogsRequest) GetMinLogLevel() LogSeverity {
	if x != nil {
		return x.MinLogLevel
	}
	return LogSeverity_LOG_SEVERITY_UNSPECIFIED
}

func (x *GetRemoteOperationContainerLogsRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetRemoteOperationContainerLogsRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *GetRemoteOperationContainerLogsRequest) GetMaxLines() int32 {
	if x != nil {
		return x.MaxLines
	}
	return 0
}

func (x *GetRemoteOperationContainerLogsRequest) GetRegex() string {
	if x != nil {
		return x.Regex
	}
	return ""
}

func (x *GetRemoteOperationContainerLogsRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *GetRemoteOperationContainerLogsRequest) GetBeforeSeq() int64 {
	if x != nil {
		return x.BeforeSeq
	}
	return 0
}

func (x *GetRemoteOperationContainerLogsRequest) GetAfterSeq() int64 {
	if x != nil {
		return x.AfterSeq
	}
	return 0
}

// The response message for <a href="index.html#ondewo.nlu.Operations.GetRemoteOperationContainerLogs">Operations.GetRemoteOperationContainerLogs</a>.
type GetRemoteOperationContainerLogsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The matching log lines, oldest first. Secrets are redacted server-side.
	LogLines []*RemoteOperationContainerLogLine `protobuf:"bytes,1,rep,name=log_lines,json=logLines,proto3" json:"log_lines,omitempty"`
	// True when older matching lines were dropped because <code>max_lines</code> was reached.
	Truncated bool `protobuf:"varint,2,opt,name=truncated,proto3" json:"truncated,omitempty"`
	// The smallest <code>seq</code> currently available for this container (its oldest captured line).
	// A client paging up has reached the beginning when the returned lines start at this value.
	MinAvailableSeq int64 `protobuf:"varint,3,opt,name=min_available_seq,json=minAvailableSeq,proto3" json:"min_available_seq,omitempty"`
	// The largest <code>seq</code> currently available for this container (its newest captured line).
	MaxAvailableSeq int64 `protobuf:"varint,4,opt,name=max_available_seq,json=maxAvailableSeq,proto3" json:"max_available_seq,omitempty"`
	// True when older lines than the returned window still exist (i.e. the window&apos;s first
	// <code>seq</code> &gt; <code>min_available_seq</code>) — the client may keep scrolling up.
	HasMoreOlder  bool `protobuf:"varint,5,opt,name=has_more_older,json=hasMoreOlder,proto3" json:"has_more_older,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRemoteOperationContainerLogsResponse) Reset() {
	*x = GetRemoteOperationContainerLogsResponse{}
	mi := &file_ondewo_nlu_operations_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRemoteOperationContainerLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRemoteOperationContainerLogsResponse) ProtoMessage() {}

func (x *GetRemoteOperationContainerLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_nlu_operations_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRemoteOperationContainerLogsResponse.ProtoReflect.Descriptor instead.
func (*GetRemoteOperationContainerLogsResponse) Descriptor() ([]byte, []int) {
	return file_ondewo_nlu_operations_proto_rawDescGZIP(), []int{9}
}

func (x *GetRemoteOperationContainerLogsResponse) GetLogLines() []*RemoteOperationContainerLogLine {
	if x != nil {
		return x.LogLines
	}
	return nil
}

func (x *GetRemoteOperationContainerLogsResponse) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

func (x *GetRemoteOperationContainerLogsResponse) GetMinAvailableSeq() int64 {
	if x != nil {
		return x.MinAvailableSeq
	}
	return 0
}

func (x *GetRemoteOperationContainerLogsResponse) GetMaxAvailableSeq() int64 {
	if x != nil {
		return x.MaxAvailableSeq
	}
	return 0
}

func (x *GetRemoteOperationContainerLogsResponse) GetHasMoreOlder() bool {
	if x != nil {
		return x.HasMoreOlder
	}
	return false
}

// A single parsed container log line, emitted by both the streaming and the query RPCs.
type RemoteOperationContainerLogLine struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The timestamp parsed from the loguru line prefix, if present.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// The loguru severity parsed from the line, or <code>LOG_SEVERITY_UNSPECIFIED</code> if the line
	// carried no recognizable level (e.g. a continuation / traceback line).
	Level LogSeverity `protobuf:"varint,2,opt,name=level,proto3,enum=ondewo.nlu.LogSeverity" json:"level,omitempty"`
	// The log message text, with ANSI colour codes stripped and secrets redacted.
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// The docker container id this line was produced by. Lets a client attribute or group lines when an
	// operation ran several containers. Empty when the id was not captured.
	ContainerId string `protobuf:"bytes,4,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	// The docker container name this line was produced by. Empty when unavailable.
	ContainerName string `protobuf:"bytes,5,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	// The monotonically-increasing sequence number of this line within its container&apos;s captured log
	// (assigned by the server-side capture). Used as the cursor for infinite-scroll paging. <code>0</code>
	// when the line was produced by a legacy path that did not assign a sequence.
	Seq           int64 `protobuf:"varint,6,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteOperationContainerLogLine) Reset() {
	*x = RemoteOperationContainerLogLine{}
	mi := &file_ondewo_nlu_operations_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteOperationContainerLogLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteOperationContainerLogLine) ProtoMessage() {}

func (x *RemoteOperationContainerLogLine) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_nlu_operations_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteOperationContainerLogLine.ProtoReflect.Descriptor instead.
func (*RemoteOperationContainerLogLine) Descriptor() ([]byte, []int) {
	return file_ondewo_nlu_operations_proto_rawDescGZIP(), []int{10}
}

func (x *RemoteOperationContainerLogLine) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *RemoteOperationContainerLogLine) GetLevel() LogSeverity {
	if x != nil {
		return x.Level
	}
	return LogSeverity_LOG_SEVERITY_UNSPECIFIED
}

func (x *RemoteOperationContainerLogLine) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RemoteOperationContainerLogLine) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *RemoteOperationContainerLogLine) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *RemoteOperationContainerLogLine) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

// The request message for <a href="index.html#ondewo.nlu.Operations.GetRemoteOperationContainerStatus">Operations.GetRemoteOperationContainerStatus</a>.
type GetRemoteOperationContainerStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the operation resource whose container status should be returned.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Optional. Scope the status to a single container of the operation, identified by its docker
	// container id. Empty (the default) returns the status of the operation&apos;s currently-registered
	// container, preserving the legacy single-container behavior.
	ContainerId   string `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRemoteOperationContainerStatusRequest) Reset() {
	*x = GetRemoteOperationContainerStatusRequest{}
	mi := &file_ondewo_nlu_operations_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRemoteOperationContainerStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRemoteOperationContainerStatusRequest) ProtoMessage() {}

func (x *GetRemoteOperationContainerStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_nlu_operations_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRemoteOperationContainerStatusRequest.ProtoReflect.Descriptor instead.
func (*GetRemoteOperationContainerStatusRequest) Descriptor() ([]byte, []int) {
	return file_ondewo_nlu_operations_proto_rawDescGZIP(), []int{11}
}

func (x *GetRemoteOperationContainerStatusRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetRemoteOperationContainerStatusRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

// The response message for <a href="index.html#ondewo.nlu.Operations.GetRemoteOperationContainerStatus">Operations.GetRemoteOperationContainerStatus</a>.
type RemoteOperationContainerStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the operation resource this status describes.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The lifecycle state of the container.
	LifecycleState RemoteOperationContainerLifecycleState `protobuf:"varint,2,opt,name=lifecycle_state,json=lifecycleState,proto3,enum=ondewo.nlu.RemoteOperationContainerLifecycleState" json:"lifecycle_state,omitempty"`
	// The host the container was dispatched to (empty when the dispatch record is unavailable).
	HostName string `protobuf:"bytes,3,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
	// The container name (empty when the dispatch record is unavailable).
	ContainerName string `protobuf:"bytes,4,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	// The docker container id (64-hex), empty when it was not captured or the record is unavailable.
	ContainerId string `protobuf:"bytes,11,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	// The container exit code. Only meaningful when <code>lifecycle_state</code> is
	// <code>EXITED</code> or <code>DEAD</code>.
	ExitCode int32 `protobuf:"varint,5,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// True when the container was killed by the out-of-memory killer.
	OomKilled bool `protobuf:"varint,6,opt,name=oom_killed,json=oomKilled,proto3" json:"oom_killed,omitempty"`
	// The Docker healthcheck status (<code>healthy</code> / <code>unhealthy</code> / <code>starting</code>),
	// empty when the container declares no healthcheck.
	HealthStatus string `protobuf:"bytes,7,opt,name=health_status,json=healthStatus,proto3" json:"health_status,omitempty"`
	// When the container started, if known.
	StartedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	// When the container finished, if it has exited.
	FinishedAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	// When this status was observed by the server.
	ObservedAt *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	// The container&apos;s environment variables (docker <code>Config.Env</code>), as a name→value map.
	// Secret values (passwords, tokens, private keys, certificates) are redacted server-side; plain
	// non-secret values such as numeric limits remain visible.
	EnvironmentVariables map[string]string `protobuf:"bytes,12,rep,name=environment_variables,json=environmentVariables,proto3" json:"environment_variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The container&apos;s command/args (docker <code>Config.Cmd</code>).
	Command []string `protobuf:"bytes,13,rep,name=command,proto3" json:"command,omitempty"`
	// The container&apos;s hard memory limit in bytes (docker <code>HostConfig.Memory</code>).
	// <code>0</code> means unlimited.
	MemoryLimitBytes int64 `protobuf:"varint,14,opt,name=memory_limit_bytes,json=memoryLimitBytes,proto3" json:"memory_limit_bytes,omitempty"`
	// The container&apos;s CPU limit in billionths of a CPU (docker <code>HostConfig.NanoCpus</code>);
	// cores = <code>nano_cpus</code> / 1e9. <code>0</code> means unset (see <code>cpu_quota</code>).
	NanoCpus int64 `protobuf:"varint,15,opt,name=nano_cpus,json=nanoCpus,proto3" json:"nano_cpus,omitempty"`
	// The CPUs the container is pinned to (docker <code>HostConfig.CpusetCpus</code>), empty when unset.
	CpusetCpus string `protobuf:"bytes,16,opt,name=cpuset_cpus,json=cpusetCpus,proto3" json:"cpuset_cpus,omitempty"`
	// The CFS CPU quota (docker <code>HostConfig.CpuQuota</code>), the older cpu-limit form; cores =
	// <code>cpu_quota</code> / <code>cpu_period</code> when both are &gt; 0.
	CpuQuota int64 `protobuf:"varint,17,opt,name=cpu_quota,json=cpuQuota,proto3" json:"cpu_quota,omitempty"`
	// The CFS CPU period (docker <code>HostConfig.CpuPeriod</code>).
	CpuPeriod int64 `protobuf:"varint,18,opt,name=cpu_period,json=cpuPeriod,proto3" json:"cpu_period,omitempty"`
	// The docker image reference the container was started from (docker <code>Config.Image</code>).
	Image         string `protobuf:"bytes,19,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteOperationContainerStatus) Reset() {
	*x = RemoteOperationContainerStatus{}
	mi := &file_ondewo_nlu_operations_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteOperationContainerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteOperationContainerStatus) ProtoMessage() {}

func (x *RemoteOperationContainerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_nlu_operations_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteOperationContainerStatus.ProtoReflect.Descriptor instead.
func (*RemoteOperationContainerStatus) Descriptor() ([]byte, []int) {
	return file_ondewo_nlu_operations_proto_rawDescGZIP(), []int{12}
}

func (x *RemoteOperationContainerStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RemoteOperationContainerStatus) GetLifecycleState() RemoteOperationContainerLifecycleState {
	if x != nil {
		return x.LifecycleState
	}
	return RemoteOperationContainerLifecycleState_REMOTE_OPERATION_CONTAINER_LIFECYCLE_STATE_UNSPECIFIED
}

func (x *RemoteOperationContainerStatus) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *RemoteOperationContainerStatus) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *RemoteOperationContainerStatus) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *RemoteOperationContainerStatus) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *RemoteOperationContainerStatus) GetOomKilled() bool {
	if x != nil {
		return x.OomKilled
	}
	return false
}

func (x *RemoteOperationContainerStatus) GetHealthStatus() string {
	if x != nil {
		return x.HealthStatus
	}
	return ""
}

func (x *RemoteOperationContainerStatus) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *RemoteOperationContainerStatus) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *RemoteOperationContainerStatus) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *RemoteOperationContainerStatus) GetEnvironmentVariables() map[string]string {
	if x != nil {
		return x.EnvironmentVariables
	}
	return nil
}

func (x *RemoteOperationContainerStatus) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *RemoteOperationContainerStatus) GetMemoryLimitBytes() int64 {
	if x != nil {
		return x.MemoryLimitBytes
	}
	return 0
}

func (x *RemoteOperationContainerStatus) GetNanoCpus() int64 {
	if x != nil {
		return x.NanoCpus
	}
	return 0
}

func (x *RemoteOperationContainerStatus) GetCpusetCpus() string {
	if x != nil {
		return x.CpusetCpus
	}
	return ""
}

func (x *RemoteOperationContainerStatus) GetCpuQuota() int64 {
	if x != nil {
		return x.CpuQuota
	}
	return 0
}

func (x *RemoteOperationContainerStatus) GetCpuPeriod() int64 {
	if x != nil {
		return x.CpuPeriod
	}
	return 0
}

func (x *RemoteOperationContainerStatus) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

// Describes one docker container started by a remote operation. A single operation may start several
// containers sequentially (hardware-check, GPU pre-allocation, build-cache, and one training container
// per algorithm), so containers are enumerated by
// <a href="index.html#ondewo.nlu.Operations.ListRemoteOperationContainers">Operations.ListRemoteOperationContainers</a>.
type RemoteOperationContainer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The docker container id (64-hex). Empty until captured at launch.
	ContainerId string `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	// The deterministic docker container name (the <code>--name</code>).
	ContainerName string `protobuf:"bytes,2,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	// The host the container runs (or ran) on.
	HostName string `protobuf:"bytes,3,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
	// The last-known lifecycle state of the container.
	LifecycleState RemoteOperationContainerLifecycleState `protobuf:"varint,4,opt,name=lifecycle_state,json=lifecycleState,proto3,enum=ondewo.nlu.RemoteOperationContainerLifecycleState" json:"lifecycle_state,omitempty"`
	// The operation resource that started this container. May be a sub-operation of the queried
	// operation when <code>include_sub_operations</code> was set.
	OperationName string `protobuf:"bytes,5,opt,name=operation_name,json=operationName,proto3" json:"operation_name,omitempty"`
	// The docker image reference the container was started from.
	Image string `protobuf:"bytes,6,opt,name=image,proto3" json:"image,omitempty"`
	// A human-readable phase label for the container within the operation, e.g. <code>hw_check</code>,
	// <code>gpu_prealloc</code>, <code>build_cache</code>, <code>train</code>, <code>rag_crawl</code>.
	Phase string `protobuf:"bytes,7,opt,name=phase,proto3" json:"phase,omitempty"`
	// The container exit code. Only meaningful once the container has exited.
	ExitCode int32 `protobuf:"varint,8,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// True when the container was killed by the out-of-memory killer.
	OomKilled bool `protobuf:"varint,9,opt,name=oom_killed,json=oomKilled,proto3" json:"oom_killed,omitempty"`
	// When the container started, if known.
	StartedAt *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	// When the container finished, if it has exited.
	FinishedAt *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	// True when logs for this container can still be fetched — either the container is live, or its logs
	// were persisted to the server-side archive after it finished.
	LogsAvailable bool `protobuf:"varint,12,opt,name=logs_available,json=logsAvailable,proto3" json:"logs_available,omitempty"`
	// The container&apos;s environment variables (docker <code>Config.Env</code>), as a name→value map.
	// Secret values (passwords, tokens, private keys, certificates) are redacted server-side; plain
	// non-secret values such as numeric limits remain visible. Persisted at launch so it is available
	// even after the container is removed.
	EnvironmentVariables map[string]string `protobuf:"bytes,13,rep,name=environment_variables,json=environmentVariables,proto3" json:"environment_variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The container&apos;s command/args (docker <code>Config.Cmd</code>).
	Command []string `protobuf:"bytes,14,rep,name=command,proto3" json:"command,omitempty"`
	// The container&apos;s hard memory limit in bytes (docker <code>HostConfig.Memory</code>).
	// <code>0</code> means unlimited.
	MemoryLimitBytes int64 `protobuf:"varint,15,opt,name=memory_limit_bytes,json=memoryLimitBytes,proto3" json:"memory_limit_bytes,omitempty"`
	// The container&apos;s CPU limit in billionths of a CPU (docker <code>HostConfig.NanoCpus</code>);
	// cores = <code>nano_cpus</code> / 1e9. <code>0</code> means unset (see <code>cpu_quota</code>).
	NanoCpus int64 `protobuf:"varint,16,opt,name=nano_cpus,json=nanoCpus,proto3" json:"nano_cpus,omitempty"`
	// The CPUs the container is pinned to (docker <code>HostConfig.CpusetCpus</code>), empty when unset.
	CpusetCpus string `protobuf:"bytes,17,opt,name=cpuset_cpus,json=cpusetCpus,proto3" json:"cpuset_cpus,omitempty"`
	// The CFS CPU quota (docker <code>HostConfig.CpuQuota</code>); cores =
	// <code>cpu_quota</code> / <code>cpu_period</code> when both are &gt; 0.
	CpuQuota int64 `protobuf:"varint,18,opt,name=cpu_quota,json=cpuQuota,proto3" json:"cpu_quota,omitempty"`
	// The CFS CPU period (docker <code>HostConfig.CpuPeriod</code>).
	CpuPeriod     int64 `protobuf:"varint,19,opt,name=cpu_period,json=cpuPeriod,proto3" json:"cpu_period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteOperationContainer) Reset() {
	*x = RemoteOperationContainer{}
	mi := &file_ondewo_nlu_operations_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteOperationContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteOperationContainer) ProtoMessage() {}

func (x *RemoteOperationContainer) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_nlu_operations_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteOperationContainer.ProtoReflect.Descriptor instead.
func (*RemoteOperationContainer) Descriptor() ([]byte, []int) {
	return file_ondewo_nlu_operations_proto_rawDescGZIP(), []int{13}
}

func (x *RemoteOperationContainer) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *RemoteOperationContainer) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *RemoteOperationContainer) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *RemoteOperationContainer) GetLifecycleState() RemoteOperationContainerLifecycleState {
	if x != nil {
		return x.LifecycleState
	}
	return RemoteOperationContainerLifecycleState_REMOTE_OPERATION_CONTAINER_LIFECYCLE_STATE_UNSPECIFIED
}

func (x *RemoteOperationContainer) GetOperationName() string {
	if x != nil {
		return x.OperationName
	}
	return ""
}

func (x *RemoteOperationContainer) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *RemoteOperationContainer) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *RemoteOperationContainer) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *RemoteOperationContainer) GetOomKilled() bool {
	if x != nil {
		return x.OomKilled
	}
	return false
}

func (x *RemoteOperationContainer) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *RemoteOperationContainer) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *RemoteOperationContainer) GetLogsAvailable() bool {
	if x != nil {
		return x.LogsAvailable
	}
	return false
}

func (x *RemoteOperationContainer) GetEnvironmentVariables() map[string]string {
	if x != nil {
		return x.EnvironmentVariables
	}
	return nil
}

func (x *RemoteOperationContainer) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *RemoteOperationContainer) GetMemoryLimitBytes() int64 {
	if x != nil {
		return x.MemoryLimitBytes
	}
	return 0
}

func (x *RemoteOperationContainer) GetNanoCpus() int64 {
	if x != nil {
		return x.NanoCpus
	}
	return 0
}

func (x *RemoteOperationContainer) GetCpusetCpus() string {
	if x != nil {
		return x.CpusetCpus
	}
	return ""
}

func (x *RemoteOperationContainer) GetCpuQuota() int64 {
	if x != nil {
		return x.CpuQuota
	}
	return 0
}

func (x *RemoteOperationContainer) GetCpuPeriod() int64 {
	if x != nil {
		return x.CpuPeriod
	}
	return 0
}

// The request message for <a href="index.html#ondewo.nlu.Operations.ListRemoteOperationContainers">Operations.ListRemoteOperationContainers</a>.
type ListRemoteOperationContainersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the operation resource whose containers should be listed.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// When true, also include the containers of the operation&apos;s sub-operations
	// (<a href="index.html#ondewo.nlu.OperationMetadata">OperationMetadata.sub_operation_names</a>).
	IncludeSubOperations bool `protobuf:"varint,2,opt,name=include_sub_operations,json=includeSubOperations,proto3" json:"include_sub_operations,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ListRemoteOperationContainersRequest) Reset() {
	*x = ListRemoteOperationContainersRequest{}
	mi := &file_ondewo_nlu_operations_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRemoteOperationContainersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRemoteOperationContainersRequest) ProtoMessage() {}

func (x *ListRemoteOperationContainersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_nlu_operations_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRemoteOperationContainersRequest.ProtoReflect.Descriptor instead.
func (*ListRemoteOperationContainersRequest) Descriptor() ([]byte, []int) {
	return file_ondewo_nlu_operations_proto_rawDescGZIP(), []int{14}
}

func (x *ListRemoteOperationContainersRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListRemoteOperationContainersRequest) GetIncludeSubOperations() bool {
	if x != nil {
		return x.IncludeSubOperations
	}
	return false
}

// The response message for <a href="index.html#ondewo.nlu.Operations.ListRemoteOperationContainers">Operations.ListRemoteOperationContainers</a>.
type ListRemoteOperationContainersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The containers started by the operation (and, when requested, its sub-operations), oldest first.
	Containers    []*RemoteOperationContainer `protobuf:"bytes,1,rep,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRemoteOperationContainersResponse) Reset() {
	*x = ListRemoteOperationContainersResponse{}
	mi := &file_ondewo_nlu_operations_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRemoteOperationContainersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRemoteOperationContainersResponse) ProtoMessage() {}

func (x *ListRemoteOperationContainersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_nlu_operations_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRemoteOperationContainersResponse.ProtoReflect.Descriptor instead.
func (*ListRemoteOperationContainersResponse) Descriptor() ([]byte, []int) {
	return file_ondewo_nlu_operations_proto_rawDescGZIP(), []int{15}
}

func (x *ListRemoteOperationContainersResponse) GetContainers() []*RemoteOperationContainer {
	if x != nil {
		return x.Containers
	}
	return nil
}

var File_ondewo_nlu_operations_proto protoreflect.FileDescriptor

const file_ondewo_nlu_operations_proto_rawDesc = "" +
	"\n" +
	"\x1bondewo/nlu/operations.proto\x12\n" +
	"ondewo.nlu\x1a\x1cgoogle/api/annotations.proto\x1a\x19google/protobuf/any.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x17google/rpc/status.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a#ondewo/nlu/operation_metadata.proto\x1a\x17ondewo/nlu/common.proto\"\xd8\x01\n" +
	"\tOperation\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x129\n" +
	"\bmetadata\x18\x02 \x01(\v2\x1d.ondewo.nlu.OperationMetadataR\bmetadata\x12\x12\n" +
	"\x04done\x18\x03 \x01(\bR\x04done\x12*\n" +
	"\x05error\x18\x04 \x01(\v2\x12.google.rpc.StatusH\x00R\x05error\x122\n" +
	"\bresponse\x18\x05 \x01(\v2\x14.google.protobuf.AnyH\x00R\bresponseB\b\n" +
	"\x06result\"d\n" +
	"\x13GetOperationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x129\n" +
	"\n" +
	"field_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\tfieldMask\"\x82\x02\n" +
	"\x15ListOperationsRequest\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x16\n" +
	"\x06filter\x18\x01 \x01(\tR\x06filter\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x12F\n" +
	"\x10operation_filter\x18\x05 \x01(\v2\x1b.ondewo.nlu.OperationFilterR\x0foperationFilter\x129\n" +
	"\n" +
	"field_mask\x18\x06 \x01(\v2\x1a.google.protobuf.FieldMaskR\tfieldMask\"\xf6\x02\n" +
	"\x0fOperationFilter\x12'\n" +
	"\x0fproject_parents\x18\x01 \x03(\tR\x0eprojectParents\x12@\n" +
	"\bstatuses\x18\x02 \x03(\x0e2$.ondewo.nlu.OperationMetadata.StatusR\bstatuses\x12A\n" +
	"\x05types\x18\x03 \x03(\x0e2+.ondewo.nlu.OperationMetadata.OperationTypeR\x05types\x12;\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\tstartTime\x127\n" +
	"\bend_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\aendTime\x12\x19\n" +
	"\buser_ids\x18\x06 \x03(\tR\auserIdsB\x12\n" +
	"\x10start_time_oneofB\x10\n" +
	"\x0eend_time_oneof\"w\n" +
	"\x16ListOperationsResponse\x125\n" +
	"\n" +
	"operations\x18\x01 \x03(\v2\x15.ondewo.nlu.OperationR\n" +
	"operations\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\",\n" +
	"\x16CancelOperationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\",\n" +
	"\x16DeleteOperationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xbe\x01\n" +
	")StreamRemoteOperationContainerLogsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12;\n" +
	"\rmin_log_level\x18\x02 \x01(\x0e2\x17.ondewo.nlu.LogSeverityR\vminLogLevel\x12\x1d\n" +
	"\n" +
	"tail_lines\x18\x03 \x01(\x05R\ttailLines\x12!\n" +
	"\fcontainer_id\x18\x04 \x01(\tR\vcontainerId\"\xfd\x02\n" +
	"&GetRemoteOperationContainerLogsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12;\n" +
	"\rmin_log_level\x18\x02 \x01(\x0e2\x17.ondewo.nlu.LogSeverityR\vminLogLevel\x129\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x1b\n" +
	"\tmax_lines\x18\x05 \x01(\x05R\bmaxLines\x12\x14\n" +
	"\x05regex\x18\x06 \x01(\tR\x05regex\x12!\n" +
	"\fcontainer_id\x18\a \x01(\tR\vcontainerId\x12\x1d\n" +
	"\n" +
	"before_seq\x18\b \x01(\x03R\tbeforeSeq\x12\x1b\n" +
	"\tafter_seq\x18\t \x01(\x03R\bafterSeq\"\x8f\x02\n" +
	"'GetRemoteOperationContainerLogsResponse\x12H\n" +
	"\tlog_lines\x18\x01 \x03(\v2+.ondewo.nlu.RemoteOperationContainerLogLineR\blogLines\x12\x1c\n" +
	"\ttruncated\x18\x02 \x01(\bR\ttruncated\x12*\n" +
	"\x11min_available_seq\x18\x03 \x01(\x03R\x0fminAvailableSeq\x12*\n" +
	"\x11max_available_seq\x18\x04 \x01(\x03R\x0fmaxAvailableSeq\x12$\n" +
	"\x0ehas_more_older\x18\x05 \x01(\bR\fhasMoreOlder\"\x80\x02\n" +
	"\x1fRemoteOperationContainerLogLine\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12-\n" +
	"\x05level\x18\x02 \x01(\x0e2\x17.ondewo.nlu.LogSeverityR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12!\n" +
	"\fcontainer_id\x18\x04 \x01(\tR\vcontainerId\x12%\n" +
	"\x0econtainer_name\x18\x05 \x01(\tR\rcontainerName\x12\x10\n" +
	"\x03seq\x18\x06 \x01(\x03R\x03seq\"a\n" +
	"(GetRemoteOperationContainerStatusRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fcontainer_id\x18\x02 \x01(\tR\vcontainerId\"\xaa\a\n" +
	"\x1eRemoteOperationContainerStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12[\n" +
	"\x0flifecycle_state\x18\x02 \x01(\x0e22.ondewo.nlu.RemoteOperationContainerLifecycleStateR\x0elifecycleState\x12\x1b\n" +
	"\thost_name\x18\x03 \x01(\tR\bhostName\x12%\n" +
	"\x0econtainer_name\x18\x04 \x01(\tR\rcontainerName\x12!\n" +
	"\fcontainer_id\x18\v \x01(\tR\vcontainerId\x12\x1b\n" +
	"\texit_code\x18\x05 \x01(\x05R\bexitCode\x12\x1d\n" +
	"\n" +
	"oom_killed\x18\x06 \x01(\bR\toomKilled\x12#\n" +
	"\rhealth_status\x18\a \x01(\tR\fhealthStatus\x129\n" +
	"\n" +
	"started_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\x12;\n" +
	"\vobserved_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\x12y\n" +
	"\x15environment_variables\x18\f \x03(\v2D.ondewo.nlu.RemoteOperationContainerStatus.EnvironmentVariablesEntryR\x14environmentVariables\x12\x18\n" +
	"\acommand\x18\r \x03(\tR\acommand\x12,\n" +
	"\x12memory_limit_bytes\x18\x0e \x01(\x03R\x10memoryLimitBytes\x12\x1b\n" +
	"\tnano_cpus\x18\x0f \x01(\x03R\bnanoCpus\x12\x1f\n" +
	"\vcpuset_cpus\x18\x10 \x01(\tR\n" +
	"cpusetCpus\x12\x1b\n" +
	"\tcpu_quota\x18\x11 \x01(\x03R\bcpuQuota\x12\x1d\n" +
	"\n" +
	"cpu_period\x18\x12 \x01(\x03R\tcpuPeriod\x12\x14\n" +
	"\x05image\x18\x13 \x01(\tR\x05image\x1aG\n" +
	"\x19EnvironmentVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8c\a\n" +
	"\x18RemoteOperationContainer\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12%\n" +
	"\x0econtainer_name\x18\x02 \x01(\tR\rcontainerName\x12\x1b\n" +
	"\thost_name\x18\x03 \x01(\tR\bhostName\x12[\n" +
	"\x0flifecycle_state\x18\x04 \x01(\x0e22.ondewo.nlu.RemoteOperationContainerLifecycleStateR\x0elifecycleState\x12%\n" +
	"\x0eoperation_name\x18\x05 \x01(\tR\roperationName\x12\x14\n" +
	"\x05image\x18\x06 \x01(\tR\x05image\x12\x14\n" +
	"\x05phase\x18\a \x01(\tR\x05phase\x12\x1b\n" +
	"\texit_code\x18\b \x01(\x05R\bexitCode\x12\x1d\n" +
	"\n" +
	"oom_killed\x18\t \x01(\bR\toomKilled\x129\n" +
	"\n" +
	"started_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\x12%\n" +
	"\x0elogs_available\x18\f \x01(\bR\rlogsAvailable\x12s\n" +
	"\x15environment_variables\x18\r \x03(\v2>.ondewo.nlu.RemoteOperationContainer.EnvironmentVariablesEntryR\x14environmentVariables\x12\x18\n" +
	"\acommand\x18\x0e \x03(\tR\acommand\x12,\n" +
	"\x12memory_limit_bytes\x18\x0f \x01(\x03R\x10memoryLimitBytes\x12\x1b\n" +
	"\tnano_cpus\x18\x10 \x01(\x03R\bnanoCpus\x12\x1f\n" +
	"\vcpuset_cpus\x18\x11 \x01(\tR\n" +
	"cpusetCpus\x12\x1b\n" +
	"\tcpu_quota\x18\x12 \x01(\x03R\bcpuQuota\x12\x1d\n" +
	"\n" +
	"cpu_period\x18\x13 \x01(\x03R\tcpuPeriod\x1aG\n" +
	"\x19EnvironmentVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"p\n" +
	"$ListRemoteOperationContainersRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x124\n" +
	"\x16include_sub_operations\x18\x02 \x01(\bR\x14includeSubOperations\"m\n" +
	"%ListRemoteOperationContainersResponse\x12D\n" +
	"\n" +
	"containers\x18\x01 \x03(\v2$.ondewo.nlu.RemoteOperationContainerR\n" +
	"containers*\xec\x03\n" +
	"&RemoteOperationContainerLifecycleState\x12:\n" +
	"6REMOTE_OPERATION_CONTAINER_LIFECYCLE_STATE_UNSPECIFIED\x10\x00\x128\n" +
	"4REMOTE_OPERATION_CONTAINER_LIFECYCLE_STATE_NOT_FOUND\x10\x01\x126\n" +
	"2REMOTE_OPERATION_CONTAINER_LIFECYCLE_STATE_CREATED\x10\x02\x126\n" +
	"2REMOTE_OPERATION_CONTAINER_LIFECYCLE_STATE_RUNNING\x10\x03\x125\n" +
	"1REMOTE_OPERATION_CONTAINER_LIFECYCLE_STATE_PAUSED\x10\x04\x129\n" +
	"5REMOTE_OPERATION_CONTAINER_LIFECYCLE_STATE_RESTARTING\x10\x05\x125\n" +
	"1REMOTE_OPERATION_CONTAINER_LIFECYCLE_STATE_EXITED\x10\x06\x123\n" +
	"/REMOTE_OPERATION_CONTAINER_LIFECYCLE_STATE_DEAD\x10\a2\x92\t\n" +
	"\n" +
	"Operations\x12v\n" +
	"\x0eListOperations\x12!.ondewo.nlu.ListOperationsRequest\x1a\".ondewo.nlu.ListOperationsResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/{name=operations}\x12h\n" +
	"\fGetOperation\x12\x1f.ondewo.nlu.GetOperationRequest\x1a\x15.ondewo.nlu.Operation\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/{name=operations/**}\x12o\n" +
	"\x0fDeleteOperation\x12\".ondewo.nlu.DeleteOperationRequest\x1a\x16.google.protobuf.Empty\" \x82\xd3\xe4\x93\x02\x1a*\x18/v1/{name=operations/**}\x12y\n" +
	"\x0fCancelOperation\x12\".ondewo.nlu.CancelOperationRequest\x1a\x16.google.protobuf.Empty\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/v1/{name=operations/**}:cancel\x12\x8a\x01\n" +
	"\"StreamRemoteOperationContainerLogs\x125.ondewo.nlu.StreamRemoteOperationContainerLogsRequest\x1a+.ondewo.nlu.RemoteOperationContainerLogLine0\x01\x12\xba\x01\n" +
	"\x1fGetRemoteOperationContainerLogs\x122.ondewo.nlu.GetRemoteOperationContainerLogsRequest\x1a3.ondewo.nlu.GetRemoteOperationContainerLogsResponse\".\x82\xd3\xe4\x93\x02(\x12&/v1/{name=operations/**}:containerLogs\x12\xb7\x01\n" +
	"!GetRemoteOperationContainerStatus\x124.ondewo.nlu.GetRemoteOperationContainerStatusRequest\x1a*.ondewo.nlu.RemoteOperationContainerStatus\"0\x82\xd3\xe4\x93\x02*\x12(/v1/{name=operations/**}:containerStatus\x12\xb1\x01\n" +
	"\x1dListRemoteOperationContainers\x120.ondewo.nlu.ListRemoteOperationContainersRequest\x1a1.ondewo.nlu.ListRemoteOperationContainersResponse\"+\x82\xd3\xe4\x93\x02%\x12#/v1/{name=operations/**}:containersb\x06proto3"

var (
	file_ondewo_nlu_operations_proto_rawDescOnce sync.Once
	file_ondewo_nlu_operations_proto_rawDescData []byte
)

func file_ondewo_nlu_operations_proto_rawDescGZIP() []byte {
	file_ondewo_nlu_operations_proto_rawDescOnce.Do(func() {
		file_ondewo_nlu_operations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ondewo_nlu_operations_proto_rawDesc), len(file_ondewo_nlu_operations_proto_rawDesc)))
	})
	return file_ondewo_nlu_operations_proto_rawDescData
}

var file_ondewo_nlu_operations_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ondewo_nlu_operations_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_ondewo_nlu_operations_proto_goTypes = []any{
	(RemoteOperationContainerLifecycleState)(0), // 0: ondewo.nlu.RemoteOperationContainerLifecycleState
	(*Operation)(nil),                                 // 1: ondewo.nlu.Operation
	(*GetOperationRequest)(nil),                       // 2: ondewo.nlu.GetOperationRequest
	(*ListOperationsRequest)(nil),                     // 3: ondewo.nlu.ListOperationsRequest
	(*OperationFilter)(nil),                           // 4: ondewo.nlu.OperationFilter
	(*ListOperationsResponse)(nil),                    // 5: ondewo.nlu.ListOperationsResponse
	(*CancelOperationRequest)(nil),                    // 6: ondewo.nlu.CancelOperationRequest
	(*DeleteOperationRequest)(nil),                    // 7: ondewo.nlu.DeleteOperationRequest
	(*StreamRemoteOperationContainerLogsRequest)(nil), // 8: ondewo.nlu.StreamRemoteOperationContainerLogsRequest
	(*GetRemoteOperationContainerLogsRequest)(nil),    // 9: ondewo.nlu.GetRemoteOperationContainerLogsRequest
	(*GetRemoteOperationContainerLogsResponse)(nil),   // 10: ondewo.nlu.GetRemoteOperationContainerLogsResponse
	(*RemoteOperationContainerLogLine)(nil),           // 11: ondewo.nlu.RemoteOperationContainerLogLine
	(*GetRemoteOperationContainerStatusRequest)(nil),  // 12: ondewo.nlu.GetRemoteOperationContainerStatusRequest
	(*RemoteOperationContainerStatus)(nil),            // 13: ondewo.nlu.RemoteOperationContainerStatus
	(*RemoteOperationContainer)(nil),                  // 14: ondewo.nlu.RemoteOperationContainer
	(*ListRemoteOperationContainersRequest)(nil),      // 15: ondewo.nlu.ListRemoteOperationContainersRequest
	(*ListRemoteOperationContainersResponse)(nil),     // 16: ondewo.nlu.ListRemoteOperationContainersResponse
	nil,                                  // 17: ondewo.nlu.RemoteOperationContainerStatus.EnvironmentVariablesEntry
	nil,                                  // 18: ondewo.nlu.RemoteOperationContainer.EnvironmentVariablesEntry
	(*OperationMetadata)(nil),            // 19: ondewo.nlu.OperationMetadata
	(*status.Status)(nil),                // 20: google.rpc.Status
	(*anypb.Any)(nil),                    // 21: google.protobuf.Any
	(*fieldmaskpb.FieldMask)(nil),        // 22: google.protobuf.FieldMask
	(OperationMetadata_Status)(0),        // 23: ondewo.nlu.OperationMetadata.Status
	(OperationMetadata_OperationType)(0), // 24: ondewo.nlu.OperationMetadata.OperationType
	(*timestamppb.Timestamp)(nil),        // 25: google.protobuf.Timestamp
	(LogSeverity)(0),                     // 26: ondewo.nlu.LogSeverity
	(*emptypb.Empty)(nil),                // 27: google.protobuf.Empty
}
var file_ondewo_nlu_operations_proto_depIdxs = []int32{
	19, // 0: ondewo.nlu.Operation.metadata:type_name -> ondewo.nlu.OperationMetadata
	20, // 1: ondewo.nlu.Operation.error:type_name -> google.rpc.Status
	21, // 2: ondewo.nlu.Operation.response:type_name -> google.protobuf.Any
	22, // 3: ondewo.nlu.GetOperationRequest.field_mask:type_name -> google.protobuf.FieldMask
	4,  // 4: ondewo.nlu.ListOperationsRequest.operation_filter:type_name -> ondewo.nlu.OperationFilter
	22, // 5: ondewo.nlu.ListOperationsRequest.field_mask:type_name -> google.protobuf.FieldMask
	23, // 6: ondewo.nlu.OperationFilter.statuses:type_name -> ondewo.nlu.OperationMetadata.Status
	24, // 7: ondewo.nlu.OperationFilter.types:type_name -> ondewo.nlu.OperationMetadata.OperationType
	25, // 8: ondewo.nlu.OperationFilter.start_time:type_name -> google.protobuf.Timestamp
	25, // 9: ondewo.nlu.OperationFilter.end_time:type_name -> google.protobuf.Timestamp
	1,  // 10: ondewo.nlu.ListOperationsResponse.operations:type_name -> ondewo.nlu.Operation
	26, // 11: ondewo.nlu.StreamRemoteOperationContainerLogsRequest.min_log_level:type_name -> ondewo.nlu.LogSeverity
	26, // 12: ondewo.nlu.GetRemoteOperationContainerLogsRequest.min_log_level:type_name -> ondewo.nlu.LogSeverity
	25, // 13: ondewo.nlu.GetRemoteOperationContainerLogsRequest.start_time:type_name -> google.protobuf.Timestamp
	25, // 14: ondewo.nlu.GetRemoteOperationContainerLogsRequest.end_time:type_name -> google.protobuf.Timestamp
	11, // 15: ondewo.nlu.GetRemoteOperationContainerLogsResponse.log_lines:type_name -> ondewo.nlu.RemoteOperationContainerLogLine
	25, // 16: ondewo.nlu.RemoteOperationContainerLogLine.timestamp:type_name -> google.protobuf.Timestamp
	26, // 17: ondewo.nlu.RemoteOperationContainerLogLine.level:type_name -> ondewo.nlu.LogSeverity
	0,  // 18: ondewo.nlu.RemoteOperationContainerStatus.lifecycle_state:type_name -> ondewo.nlu.RemoteOperationContainerLifecycleState
	25, // 19: ondewo.nlu.RemoteOperationContainerStatus.started_at:type_name -> google.protobuf.Timestamp
	25, // 20: ondewo.nlu.RemoteOperationContainerStatus.finished_at:type_name -> google.protobuf.Timestamp
	25, // 21: ondewo.nlu.RemoteOperationContainerStatus.observed_at:type_name -> google.protobuf.Timestamp
	17, // 22: ondewo.nlu.RemoteOperationContainerStatus.environment_variables:type_name -> ondewo.nlu.RemoteOperationContainerStatus.EnvironmentVariablesEntry
	0,  // 23: ondewo.nlu.RemoteOperationContainer.lifecycle_state:type_name -> ondewo.nlu.RemoteOperationContainerLifecycleState
	25, // 24: ondewo.nlu.RemoteOperationContainer.started_at:type_name -> google.protobuf.Timestamp
	25, // 25: ondewo.nlu.RemoteOperationContainer.finished_at:type_name -> google.protobuf.Timestamp
	18, // 26: ondewo.nlu.RemoteOperationContainer.environment_variables:type_name -> ondewo.nlu.RemoteOperationContainer.EnvironmentVariablesEntry
	14, // 27: ondewo.nlu.ListRemoteOperationContainersResponse.containers:type_name -> ondewo.nlu.RemoteOperationContainer
	3,  // 28: ondewo.nlu.Operations.ListOperations:input_type -> ondewo.nlu.ListOperationsRequest
	2,  // 29: ondewo.nlu.Operations.GetOperation:input_type -> ondewo.nlu.GetOperationRequest
	7,  // 30: ondewo.nlu.Operations.DeleteOperation:input_type -> ondewo.nlu.DeleteOperationRequest
	6,  // 31: ondewo.nlu.Operations.CancelOperation:input_type -> ondewo.nlu.CancelOperationRequest
	8,  // 32: ondewo.nlu.Operations.StreamRemoteOperationContainerLogs:input_type -> ondewo.nlu.StreamRemoteOperationContainerLogsRequest
	9,  // 33: ondewo.nlu.Operations.GetRemoteOperationContainerLogs:input_type -> ondewo.nlu.GetRemoteOperationContainerLogsRequest
	12, // 34: ondewo.nlu.Operations.GetRemoteOperationContainerStatus:input_type -> ondewo.nlu.GetRemoteOperationContainerStatusRequest
	15, // 35: ondewo.nlu.Operations.ListRemoteOperationContainers:input_type -> ondewo.nlu.ListRemoteOperationContainersRequest
	5,  // 36: ondewo.nlu.Operations.ListOperations:output_type -> ondewo.nlu.ListOperationsResponse
	1,  // 37: ondewo.nlu.Operations.GetOperation:output_type -> ondewo.nlu.Operation
	27, // 38: ondewo.nlu.Operations.DeleteOperation:output_type -> google.protobuf.Empty
	27, // 39: ondewo.nlu.Operations.CancelOperation:output_type -> google.protobuf.Empty
	11, // 40: ondewo.nlu.Operations.StreamRemoteOperationContainerLogs:output_type -> ondewo.nlu.RemoteOperationContainerLogLine
	10, // 41: ondewo.nlu.Operations.GetRemoteOperationContainerLogs:output_type -> ondewo.nlu.GetRemoteOperationContainerLogsResponse
	13, // 42: ondewo.nlu.Operations.GetRemoteOperationContainerStatus:output_type -> ondewo.nlu.RemoteOperationContainerStatus
	16, // 43: ondewo.nlu.Operations.ListRemoteOperationContainers:output_type -> ondewo.nlu.ListRemoteOperationContainersResponse
	36, // [36:44] is the sub-list for method output_type
	28, // [28:36] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_ondewo_nlu_operations_proto_init() }
func file_ondewo_nlu_operations_proto_init() {
	if File_ondewo_nlu_operations_proto != nil {
		return
	}
	file_ondewo_nlu_operation_metadata_proto_init()
	file_ondewo_nlu_common_proto_init()
	file_ondewo_nlu_operations_proto_msgTypes[0].OneofWrappers = []any{
		(*Operation_Error)(nil),
		(*Operation_Response)(nil),
	}
	file_ondewo_nlu_operations_proto_msgTypes[3].OneofWrappers = []any{
		(*OperationFilter_StartTime)(nil),
		(*OperationFilter_EndTime)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ondewo_nlu_operations_proto_rawDesc), len(file_ondewo_nlu_operations_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ondewo_nlu_operations_proto_goTypes,
		DependencyIndexes: file_ondewo_nlu_operations_proto_depIdxs,
		EnumInfos:         file_ondewo_nlu_operations_proto_enumTypes,
		MessageInfos:      file_ondewo_nlu_operations_proto_msgTypes,
	}.Build()
	File_ondewo_nlu_operations_proto = out.File
	file_ondewo_nlu_operations_proto_goTypes = nil
	file_ondewo_nlu_operations_proto_depIdxs = nil
}
