// Copyright 2020-2026 ONDEWO GmbH
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.32.0
// source: ondewo/nlu/server_statistics.proto

package nlu

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ServerStatistics_GetProjectCount_FullMethodName     = "/ondewo.nlu.ServerStatistics/GetProjectCount"
	ServerStatistics_GetUserProjectCount_FullMethodName = "/ondewo.nlu.ServerStatistics/GetUserProjectCount"
	ServerStatistics_GetUserCount_FullMethodName        = "/ondewo.nlu.ServerStatistics/GetUserCount"
)

// ServerStatisticsClient is the client API for ServerStatistics service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Server project statistics
type ServerStatisticsClient interface {
	// Returns the count of projects in the CAI server
	GetProjectCount(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*StatResponse, error)
	// Returns the count of projects of a user
	GetUserProjectCount(ctx context.Context, in *GetUserProjectCountRequest, opts ...grpc.CallOption) (*StatResponse, error)
	// Returns the users count within a project
	GetUserCount(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*StatResponse, error)
}

type serverStatisticsClient struct {
	cc grpc.ClientConnInterface
}

func NewServerStatisticsClient(cc grpc.ClientConnInterface) ServerStatisticsClient {
	return &serverStatisticsClient{cc}
}

func (c *serverStatisticsClient) GetProjectCount(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*StatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatResponse)
	err := c.cc.Invoke(ctx, ServerStatistics_GetProjectCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverStatisticsClient) GetUserProjectCount(ctx context.Context, in *GetUserProjectCountRequest, opts ...grpc.CallOption) (*StatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatResponse)
	err := c.cc.Invoke(ctx, ServerStatistics_GetUserProjectCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverStatisticsClient) GetUserCount(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*StatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatResponse)
	err := c.cc.Invoke(ctx, ServerStatistics_GetUserCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServerStatisticsServer is the server API for ServerStatistics service.
// All implementations must embed UnimplementedServerStatisticsServer
// for forward compatibility.
//
// Server project statistics
type ServerStatisticsServer interface {
	// Returns the count of projects in the CAI server
	GetProjectCount(context.Context, *emptypb.Empty) (*StatResponse, error)
	// Returns the count of projects of a user
	GetUserProjectCount(context.Context, *GetUserProjectCountRequest) (*StatResponse, error)
	// Returns the users count within a project
	GetUserCount(context.Context, *emptypb.Empty) (*StatResponse, error)
	mustEmbedUnimplementedServerStatisticsServer()
}

// UnimplementedServerStatisticsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServerStatisticsServer struct{}

func (UnimplementedServerStatisticsServer) GetProjectCount(context.Context, *emptypb.Empty) (*StatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProjectCount not implemented")
}
func (UnimplementedServerStatisticsServer) GetUserProjectCount(context.Context, *GetUserProjectCountRequest) (*StatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserProjectCount not implemented")
}
func (UnimplementedServerStatisticsServer) GetUserCount(context.Context, *emptypb.Empty) (*StatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserCount not implemented")
}
func (UnimplementedServerStatisticsServer) mustEmbedUnimplementedServerStatisticsServer() {}
func (UnimplementedServerStatisticsServer) testEmbeddedByValue()                          {}

// UnsafeServerStatisticsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServerStatisticsServer will
// result in compilation errors.
type UnsafeServerStatisticsServer interface {
	mustEmbedUnimplementedServerStatisticsServer()
}

func RegisterServerStatisticsServer(s grpc.ServiceRegistrar, srv ServerStatisticsServer) {
	// If the following call panics, it indicates UnimplementedServerStatisticsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ServerStatistics_ServiceDesc, srv)
}

func _ServerStatistics_GetProjectCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerStatisticsServer).GetProjectCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServerStatistics_GetProjectCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerStatisticsServer).GetProjectCount(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerStatistics_GetUserProjectCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserProjectCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerStatisticsServer).GetUserProjectCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServerStatistics_GetUserProjectCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerStatisticsServer).GetUserProjectCount(ctx, req.(*GetUserProjectCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerStatistics_GetUserCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerStatisticsServer).GetUserCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServerStatistics_GetUserCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerStatisticsServer).GetUserCount(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ServerStatistics_ServiceDesc is the grpc.ServiceDesc for ServerStatistics service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServerStatistics_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ondewo.nlu.ServerStatistics",
	HandlerType: (*ServerStatisticsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProjectCount",
			Handler:    _ServerStatistics_GetProjectCount_Handler,
		},
		{
			MethodName: "GetUserProjectCount",
			Handler:    _ServerStatistics_GetUserProjectCount_Handler,
		},
		{
			MethodName: "GetUserCount",
			Handler:    _ServerStatistics_GetUserCount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ondewo/nlu/server_statistics.proto",
}
